### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by sstevens2** [MrOlm/drep#10]
Going to try out drep and I got stuck when I was reminded that ANIcalculator is linux only and I was installing drep on a mac.  Do you by any chance have a docker image with drep and all its dependancies?
Thanks!

**Comment by MrOlm** [comment]
Hi Sarah,

I do not have a docker image yet, but it's something that's on the To Do list.

You can still use dRep on a mac with the ANIm option, though. This uses MUMmer to calculate ANI instead of ANIcalculator. 

Let me know if you have any troubles getting it set up on your Mac!
-Matt

**Comment by sstevens2** [comment]
Well I am getting the following error when I try to run your tests.
```
Traceback (most recent call last):
  File "test_suite.py", line 527, in <module>
    test_quick()
  File "test_suite.py", line 518, in test_quick
    rerun_test()
  File "test_suite.py", line 498, in rerun_test
    QuickTests().run()
  File "test_suite.py", line 323, in run
    self.unit_tests_4()
  File "test_suite.py", line 404, in unit_tests_4
    controller.parseArguments(args)
  File "/usr/local/lib/python3.5/site-packages/drep/controller.py", line 151, in parseArguments
    self.cluster_operation(**vars(args))
  File "/usr/local/lib/python3.5/site-packages/drep/controller.py", line 56, in cluster_operation
    drep.d_cluster.d_cluster_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 287, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(Bdb, data_folder, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 118, in cluster_genomes
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 151, in run_secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 872, in compare_genomes
    df = run_pairwise_ANIn(genome_list, working_data_folder, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 925, in run_pairwise_ANIn
    df = process_deltafiles(deltafiles, org_lengths, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 784, in process_deltafiles
    tot_length, tot_sim_error = parse_delta(deltafile)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 688, in parse_delta
    for line in [l.strip().split() for l in open(filename, 'rU').readlines()]:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hillier/drep/tests/test_backend/ecoli_wd/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_faecalis_T2.fna.delta'
```
Would this be from not having gANI installed?  I also installed with pip and then just cloned the repo to run the tests if that would make a difference?

**Comment by MrOlm** [comment]
Hello,

That error could be the result of not having MUMmer installed and in your system path.

If you just try the command `mummer -h` does that work?

**Comment by sstevens2** [comment]
Yep I added mummer to the path so `mummer -h` works. 

P.S. I've started putting together a dockerfile but the pip installs are still giving me errors so I'm still working on it.

**Comment by MrOlm** [comment]
Hmmm that's strange... I wonder if it is a problem with the test suite.

If you could, would you mind trying to run the program outside of the test suite? You can still use the sample genomes provided. For example:

`$ dRep compare_wf testDir -g genomes/*`

If it works, great. If not, please send me the log file so I can troubleshoot what's going on. With the above command, the log file would be located:

`testDir/log/logger.log`

Thanks!
-Matt

**Comment by sstevens2** [comment]
Gave it a try directly.  Here is the log.

[logger.log.txt](https://github.com/MrOlm/drep/files/1049112/logger.log.txt)

**Comment by MrOlm** [comment]
Everything in the log looks great... the only think I can think of is if mummer is not working. 

Does the following command work for you? (the genomes are in the tests/genomes/ folder)

`$ nucmer -p nucmer_test Enterococcus_casseliflavus_EC20.fasta Enterococcus_faecalis_T2.fna`

It should make a file named `nucmer_test.delta`

-Matt

**Comment by sstevens2** [comment]
I did just find a problem there because I had moved the MUMmer after running `make install` and it doesn't like that.  I fixed it though and now the nucmer command above works but I still get the same error with the text suite.

**Comment by MrOlm** [comment]
What about the command run separate from the test suite? The one you sent me the logfile from?

Could you please try and run it again (ensuring that nucmer is working in the environment that you're in), and sending me the logfile again if it fails?

Thanks again for helping me troubleshoot this,
-Matt

**Comment by sstevens2** [comment]
Here is the new log file.
[logger.log.txt](https://github.com/MrOlm/drep/files/1049152/logger.log.txt)

Thanks for being so patient with my issues.  In other news, I'm making progress on the docker image though and it seems to be doing better on the `test_suite.py`.

**Comment by MrOlm** [comment]
Hey Sarah,

Good to hear about the Docker image. I've never made (or used) one before, but I'm looking forward to seeing what they're all about.

I pushed a special branch of dRep for you to download to help us troubleshoot this.

The new branch is called "sarah_fix". To download it, run:

`git clone -b sarah_fix git@github.com:MrOlm/drep.git`

Then install it with pip however you did previously. For example:

```
cd drep
pip install .
```

If successful, when you run the help you should see the following:

```
$ dRep -h

                ...::: dRep v0.5.7_SF :::...

  Choose one of the operations below for more detailed help.
  Example: dRep dereplicate_wf -h
```

Once you have this set up, go ahead and run the command again and send me the log file please! This should be the last thing we need to try.

Thanks again,
-Matt

**Comment by sstevens2** [comment]
Newest log. 
[logger.log.txt](https://github.com/MrOlm/drep/files/1049196/logger.log.txt)

Just fyi, I didn't clone the repo again though.  I just pulled down that branch and then checked it out and then installed.

**Comment by sstevens2** [comment]
I'm not an expert at Docker either.  This is my first Dockerfile (pasted below).  The final image ended up being a bit big because of all the python packages it seems. 
```
# Starting with Ubuntu - Debian didn't work for me, it had errors for installing the python packages
FROM ubuntu:16.04

# Installing all dependancies
RUN apt-get update && apt-get install -y \
		csh \ 
		git \ 
		python3 \ 
		python3-pip \ 
		unzip \ 
		wget

# mash
RUN cd /root && wget https://github.com/marbl/Mash/releases/download/v1.1.1/mash-Linux64-v1.1.1.tar.gz  && \ 
	tar -xvzf mash-Linux64-v1.1.1.tar.gz && \
	mv mash-Linux64-v1.1.1/mash /usr/local/bin/
# Mummer
RUN cd /root && wget https://svwh.dl.sourceforge.net/project/mummer/mummer/3.23/MUMmer3.23.tar.gz  && \
	tar -xvzf MUMmer3.23.tar.gz && cd MUMmer3.23/ && \
	make install 
ENV PATH="$PATH:/root/MUMmer3.23/"
# gani 
RUN cd /root && wget https://ani.jgi-psf.org/download_files/ANIcalculator_v1.tgz && \
	tar -xvzf ANIcalculator_v1.tgz && \
	mv ANIcalculator_v1/ANIcalculator /usr/local/bin/ && \
	mv ANIcalculator_v1/nsimscan /usr/local/bin/ &&  \
	chmod 755 /usr/local/bin/ANIcalculator && \
	chmod 755 /usr/local/bin/nsimscan
# prodigal
RUN cd /root && wget https://github.com/hyattpd/Prodigal/releases/download/v2.6.3/prodigal.linux && \ 
	mv prodigal.linux /usr/local/bin/prodigal && \
	chmod 755 /usr/local/bin/prodigal
# centrifuge 
RUN cd /root && git clone https://github.com/infphilo/centrifuge && \
	cd centrifuge && make && \
	make install prefix=/usr/local && \
	cd .. && rm -r centrifuge/
# drep
RUN cd /root && git clone https://github.com/MrOlm/drep.git && \
	cd drep && pip3 install .
```
I also put it on dockerhub here [sstevens/drep-genome-nocheckm](https://hub.docker.com/r/sstevens/drep-genome-nocheckm/). 

I think it is working but not 100% sure.  Is there a testing script for without checkm?   I'll keep working on it Monday but thought I'd let you know about this version.
Feel free to check it out with `docker pull sstevens/drep-genome-nocheckm` and then `docker run -i -t sstevens/drep-genome-nocheckm`.  The repo is in `/root` if you want to run the tests.
Sarah

**Comment by MrOlm** [comment]
Hi Sarah,

So the command that failed is:

`nucmer --mum -p /Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta -c 65 -g 90 /Users/hillier/drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta /Users/hillier/drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta`

Does that work when you try it on it's own?

Also thanks for the Docker image! I don't even have Docker yet, but I'm excited to try it out!

-Matt

**Comment by sstevens2** [comment]
Yep that command on its own seems to work fine.  It prints the following.

```
$nucmer --mum -p /Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta -c 65 -g 90 /Users/hillier/drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta /Users/hillier/drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "/Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta.ntref" of length 3427277
# construct suffix tree for sequence of length 3427277
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 34272 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /Users/hillier/Programs/MUMmer3.23/mummer /Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta.ntref 1.37
# reading input file "/Users/hillier/drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta" of length 3427276
# matching query-file "/Users/hillier/drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta"
# against subject-file "/Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta.ntref"
# COMPLETETIME /Users/hillier/Programs/MUMmer3.23/mummer /Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta.ntref 3.90
# SPACE /Users/hillier/Programs/MUMmer3.23/mummer /Users/hillier/drep/tests/testDir/data/ANIn_files/Enterococcus_casseliflavus_EC20.fasta_vs_Enterococcus_casseliflavus_EC20.fasta.ntref 6.64
4: FINISHING DATA
```

Let me know if you have any questions about the docker image!  I'll give installing checkm into it another shot later in the week.

**Comment by sstevens2** [comment]
Well getting a different error this time..

Here is all the printed output:
```
$dRep compare_wf testDir -g genomes/*
Step 1. Cluster
Cannot locate the program nucmer- make sure its in the system path
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
[====================] 100.00%
2b. Cluster pair-wise MASH clustering
4 primary clusters made
Step 3. Perform secondary clustering
Running 12 ANIn comparisons- should take ~ 0.7 min
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.5/site-packages/drep/controller.py", line 146, in parseArguments
    self.compare_wf_operation(**vars(args))
  File "/usr/local/lib/python3.5/site-packages/drep/controller.py", line 91, in compare_wf_operation
    drep.d_workflows.compare_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_workflows.py", line 92, in compare_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 287, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(Bdb, data_folder, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 118, in cluster_genomes
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 151, in run_secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 881, in compare_genomes
    df = run_pairwise_ANIn(genome_list, working_data_folder, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 925, in run_pairwise_ANIn
    thread_nucmer_cmds_status(cmds,p,verbose=False)
  File "/usr/local/lib/python3.5/site-packages/drep/d_cluster.py", line 1087, in thread_nucmer_cmds_status
    logging.debug(' '.join(cmd))
TypeError: sequence item 0: expected str instance, NoneType found
```

And here is the log:
[logger.log.txt](https://github.com/MrOlm/drep/files/1053218/logger.log.txt)

**Comment by MrOlm** [comment]
Hmmmm. So it seems that for whatever reason, python is not able to find the program `nucmer`.

You can see that the program is throwing that error near the top of the script (after Step 1.)

I haven't ever encountered this error before. I'm using the native python module shutil to try and find nucmer (https://docs.python.org/3.3/library/shutil.html#shutil.which).

What's weird is that I also am using that module to find Mash, which is working on your system.

Can you think of any differences in how you installed Mash vs. nucmer? Specifically ways that could make one findable in your system path, and the other not?

Just as a test, does the command `which nucmer` work? (just on the command line).

For example, when I run the command on my Mac I see the following:

``` 
$ which nucmer
/Users/mattolm/Scripts/MUMmer3.23/nucmer 
```

-Matt

**Comment by sstevens2** [comment]
So yep that was it.  When I installed them I had to add the location of mummer to my path variable where with mash I just added the executable to a location in my existing path variable.  And when I added mummer to my path, I used a relative path with `~` but I guess it doesn't like that.  I was thrown off because it seemed like nucmer was working when I called it alone above.  Something funky must have been going on there.  Now `test_suite.py` seems to be working, stops when it gets to checkm (same as the docker version).  Sorry for such a simple error.

**Comment by sstevens2** [comment]
I'm a bit confused about pyenv really but I think (could be wrong) it will be okay if I install just have `python` be 2.7.x and `python3` be 3.4.x?  My problem installing checkm in the docker container is adding the data in a reproducible way(w/docker file).  The `checkm data update` command is interactive and asks questions you have to answer for it to work.  Also adding the data doubles the size of the Docker image because the data is 1.38 GB which is a little sad.

Side question: Does this call checkm using the full reference genome tree or the reduced tree?  As the full reference genome tree requires more memory than a typical laptop/desktop has.

**Comment by sstevens2** [comment]
Well I was wrong for sure.  Get an error 
```
!!! checkM failed !!!
If using pyenv, make sure both python2 and python3 are available (for example: pyenv global 3.5.1 2.7.9)
``` 
I need to figure out how to use pyenv.  The user will still have to set the checkm root when they start up a container with this image but not the end of the world.  Will try again with pyenv tomorrow, if you have explicit directions for installing and setting it up on ubuntu that would be helpful.

**Comment by MrOlm** [comment]
I'm closing this now- happy to re-open if you have more questions!

**Comment by RiboRings** [comment]
Hello everyone! @sstevens2, I was wondering, why did you exclude checkM from the Docker image of dRep?
I'm facing issues to install and work locally with checkM on Mac and I also need to use dRep, it'd be great if I could get both at once as a Docker image. :)

**Comment by MrOlm** [comment]
Hi @RiboRings - have you checked out the automatic docker image made through conda? quay.io/biocontainers/drep:3.2.2 . I'm not positive if it has checkM installed but it might?
