### ISSUE TITLE
CLUSTERING WARNING: Primary cluster 1 has a high self-comparison value， reopen

### ISSUE THREAD

**Issue by liupfskygre** [MrOlm/drep#100]
Hi Matt, 
 this is a reopen to this issue, 
https://github.com/MrOlm/drep/issues/94#
sorry for a late reply,
1, I do this analysis on anther server with dRep (I could get the version now), and have 4 produced without any warnings,

2, the winner db looks wired for this run with 11 winners, as you can see here, for each cluster, only one with highest score, but it gave me others with lower scores, i think score is the criteria for the winner, right

here is the winner db from data_tables/Widb.csv
```
genome,score,completeness,contamination,strain_heterogeneity,size,N50,cluster,taxonomy,tax_confidence,cluster_members,closest_cluster_member,furthest_cluster_member,completeness_metric,contamination_metric
2-C20-8_bin.5.fa,91.78056647607174,NA,NA,NA,NA,NA,1_1,NA,NA,9,99.95,97.76,NA,NA
TO55_bin.84.fa,88.3105542956999,NA,NA,NA,NA,NA,1_2,NA,NA,1,NA,NA,NA,NA
TO45_bin.92.fa,87.72086500778622,NA,NA,NA,NA,NA,1_3,NA,NA,1,NA,NA,NA,NA
TO35_bin.67.fa,88.38329490128521,NA,NA,NA,NA,NA,1_4,NA,NA,1,NA,NA,NA,NA
TO65_bin.86.fa,88.38078056011803,NA,NA,NA,NA,NA,1_5,NA,NA,1,NA,NA,NA,NA
pw55_bin.61.fa,86.23031193727495,NA,NA,NA,NA,NA,2_1,NA,NA,7,99.92,99.81,NA,NA
TO45_bin.85.fa,75.29557245437816,NA,NA,NA,NA,NA,2_2,NA,NA,1,NA,NA,NA,NA
GD2_bin.40.fa,79.25927164956101,NA,NA,NA,NA,NA,3_1,NA,NA,9,98.85,98.47,NA,NA
TO55_bin.66.fa,64.98471984228358,NA,NA,NA,NA,NA,3_2,NA,NA,1,NA,NA,NA,NA
TO65_bin.11.fa,84.84733828761587,NA,NA,NA,NA,NA,3_3,NA,NA,1,NA,NA,NA,NA
G35_3_bin.32.fa,84.27587134106159,NA,NA,NA,NA,NA,4_1,NA,NA,7,99.90,98.69,NA,NA
```
not sure if it is bug or it is the case, thanks Matt.

**Comment by MrOlm** [comment]
Hello,

In the table you sent there is only one winner per cluster. 1_1 and 1_2 are different clusters.

Why do you think there are multiple winners per cluster? This table looks OK to me, I can't see any problems.

Best,
Matt

**Comment by liupfskygre** [comment]
Hi Matt,
   thanks for the quick reply. 
there two reasons I am not sure about this dataset, 1) I have run in one server I could not access now that give 4 cluster, with one representative for each cluster 1_x, 2_x, 3_x and 4_x in the table above. 2, i did ani calculation and 16S comparisons, and I know for each genomes within 1_x, 2_x, 3_x, 4_x, they share >99% ani identify, so the first run on that server should be right. not sure what's happening. I am using the clustering based on ani now before I could figure out what is going on:) 

one more basic question, which table/matrix should i look for that deRep based to gave representative genomes, the Widb or the Wdb or other index/table? 

Best,
Liu

**Comment by MrOlm** [comment]
Hi Liu,

Wdb is the best table for looking at representative genomes.

Ndb also contains the ANI values for all genome comparisons. If you see two genomes that are in the same cluster but you think shouldn't be, check Ndb to see if there's a problem.

Best,
Matt

**Comment by liupfskygre** [comment]
thanks Matt.
