### ISSUE TITLE
Is the conda version consistent with gitHub?

### ISSUE THREAD

**Issue by rainjy** [MrOlm/drep#101]
github: the latest version  2.5.4 , and  old version is 1.4.3
but conda has other version,such as 3.0.0 2.4  2.2.4

cmd: conda search drep
Loading channels: done
# Name                       Version           Build  Channel             
drep                           2.0.5          py35_0  bioconda            
drep                           2.0.5  py35h24bf2e0_2  bioconda            
drep                           2.0.5          py36_0  bioconda            
drep                           2.0.5  py36h24bf2e0_2  bioconda            
drep                           2.2.3          py35_0  bioconda            
drep                           2.2.3          py35_1  bioconda            
drep                           2.2.3          py36_0  bioconda            
drep                           2.2.3          py36_1  bioconda            
drep                           2.3.2            py_0  bioconda            
drep                           2.3.2            py_1  bioconda            
drep                           2.4.0            py_0  bioconda            
drep                           2.4.0            py_1  bioconda            
drep                           2.4.1            py_0  bioconda            
drep                           2.4.2            py_0  bioconda            
drep                           2.5.0            py_0  bioconda            
drep                           2.5.1            py_0  bioconda            
drep                           2.5.2            py_0  bioconda            
drep                           2.5.3            py_0  bioconda            
drep                           2.5.4            py_0  bioconda            
drep                           2.6.0            py_0  bioconda            
drep                           2.6.1            py_0  bioconda            
drep                           2.6.2            py_0  bioconda            
drep                           3.0.0            py_0  bioconda            
drep                           3.0.0            py_1  bioconda

**Comment by MrOlm** [comment]
The GitHub is incorrect- the newest version (which is recommended) is 3.0.0.

I'll update the GitHub now, thanks for the heads up.

-Matt
