### ISSUE TITLE
checkM failed !!!

### ISSUE THREAD

**Issue by Furaxixi** [MrOlm/drep#102]
Hi Matt, 

I have a different checkM failled error than other.

Here is my command (ran on service):
`#!/bin/bash
#SBATCH --cpus-per-task=6
#SBATCH --mem=200G
#SBATCH --partition=bigmem
#SBATCH --constraint=Intel
#SBATCH --time=3-00:00
#SBATCH -o /nfs/scratch/kuangfr/sbatch_report_files_dRep_1/dRep_%A_%a.out
#SBATCH -e /nfs/scratch/kuangfr/sbatch_report_files_dRep_1/dRep_%A_%a.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lawliet.sm@gmail.com

module load dRep/2.4.0

module load CheckM/1.1.2

dRep dereplicate /nfs/scratch/kuangfr/dRep_dep/ -g /nfs/scratch/kuangfr/genomes_FK/*.fasta --debug`

errors were found from the cmd_logs folder and upload in this issues.

[2021-01-29_01.28.24.319244.zip](https://github.com/MrOlm/drep/files/5891384/2021-01-29_01.28.24.319244.zip)
[2021-01-29_01.28.07.429541.zip](https://github.com/MrOlm/drep/files/5891385/2021-01-29_01.28.07.429541.zip)

Hope to hear from you soon.

Kind regard.
Furaxixi

**Comment by MrOlm** [comment]
Hello,

Thanks for all the debugging info. Looking at the file `2021-01-29_01.28.07.429541.stdout` tells you what the checkM error is. This is a checkM error, not a dRep error, so I won't be able to help completely, but I do have some advice.

It seems like checkM isn't set up correctly- either you don't have the database it needs, or you have the database and it's not set up correctly. See here for installation instructions - https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm . Note that you need to download and extract the database (I install and extract to `~/.checkm`), and then tell checkm where the database is by running a command like `checkm data setRoot ~/.checkm/`.

Best,
Matt
