### ISSUE TITLE
Secondary clustering

### ISSUE THREAD

**Issue by ntromas** [MrOlm/drep#105]
Hi,

When I run the following command:
dRep dereplicate dRep_wat_das_new/  -g DAS_wat_Run/_DASTool_bins/*.fa -comp 80 -con 10 -sa 95

I got this kind of pdf where the x-axis seems to be wrong and therefore I am not sure if the second clustering worked correctly. As warnings I also got this message for several clusters:

CLUSTERING WARNING: Primary cluster 1 has a high self-comparison value

[Secondary_clustering_dendrograms.pdf](https://github.com/MrOlm/drep/files/5984514/Secondary_clustering_dendrograms.pdf)

Cheers,

Nico

**Comment by MrOlm** [comment]
Hi Nico,

For `-sa`, you want `0.95`, not `95`. This number should be a fraction, not a percentage. I'm pretty sure this is the problem.

Best,
Matt

**Comment by ntromas** [comment]
🙈
Hi Matt,

Oh ok! I feel a bit dumb...
Thanks a lot!!

Nico
