### ISSUE TITLE
Can't set the ‘-comp’ 

### ISSUE THREAD

**Issue by Lily-WL** [MrOlm/drep#106]
Dear developers,

I had a collection of 135 bins. When I used the default set, only about 82% bins passed the filter. Becasue some of my bins less than 75% completeness (but more than 60%), I set the parameter “-comp 60”. However, dRep can not progress well. Seems that no bins passed the checkM filter. Can you help to fix this problem? Thank you very much!

The command and error as follows:

> [wl@ts-rd350 export_for_bin]$ dRep dereplicate dRep/W_all3_com60/ -g gtdb/Bins_less5more60_from_3sample/AA/*.faa -comp 60 -con 10 -d -p 1
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Running checkM
0.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 80, in d_cluster_wrapper
    data_folder, wd=workDirectory, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 177, in cluster_genomes
    Cdb, cluster_ret = cluster_mash_database(Mdb, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 639, in cluster_mash_database
    linkage_cutoff= P_Lcutoff)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 470, in cluster_hierarchical
    linkage = scipy.cluster.hierarchy.linkage(arr, method= linkage_method)
  File "/usr/local/lib64/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1064, in linkage
    n = int(distance.num_obs_y(y))
  File "/usr/local/lib64/python3.6/site-packages/scipy/spatial/distance.py", line 2403, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.

**Comment by Lily-WL** [comment]
Dear Developer s,

I just found that the values of "completeness" in file .../dat/checkM/checkM_outdir/storage/bin_stats_ext.tsv were zero for all the bins. Set an example as the following.

![图片](https://user-images.githubusercontent.com/18734671/109447237-3181f300-7a7e-11eb-9008-0a25a3afb6a8.png)

**Comment by MrOlm** [comment]
Hello,

It seems like you may be providing dRep with gene amino acid files (.faa) instead of genomes (.fasta, .fa, .fna). dRep needs you to provide it genomes, and it will call genes on those genomes itself. Could that be the problem?

Best,
Matt

**Comment by Lily-WL** [comment]
Thank you very much for your reply! It worked when I loaded the nt sequences. Thank you again!


WANG Li
<http://aka.ms/weboutlook>

________________________________
发件人: Matt Olm <notifications@github.com>
发送时间: 2021年3月2日 0:53
收件人: MrOlm/drep <drep@noreply.github.com>
抄送: Lily-WL <wangli_lily@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [MrOlm/drep] Can't set the ‘-comp’ (#106)


Hello,

It seems like you may be providing dRep with gene amino acid files (.faa) instead of genomes (.fasta, .fa, .fna). dRep needs you to provide it genomes, and it will call genes on those genomes itself. Could that be the problem?

Best,
Matt

―
