### ISSUE TITLE
" 'module' has no attribute 'which' "after installation

### ISSUE THREAD

**Issue by geboro** [MrOlm/drep#11]
Hello. 
The test suite is failing with:
> Traceback (most recent call last):
  File "test_suite.py", line 632, in <module>
    test_quick()
  File "test_suite.py", line 623, in test_quick
    rerun_test()
  File "test_suite.py", line 595, in rerun_test
    QuickTests().run()
  File "test_suite.py", line 404, in run
    self.setUp()
  File "test_suite.py", line 394, in setUp
    os.mkdir(self.working_wd_loc)
OSError: [Errno 2] No such file or directory: '~/Software/drep/tests/../tests/test_backend/ecoli_wd'

And I can see that subdirectory "test_backend" is indeed not in there, and not in the github repo.  

However, dRep is also failing while running the test dataset on its own as:

>/home/Software/drep/tests $ dRep compare_wf outputdir/ -g ./genomes/*fasta
Step 1. Cluster
Traceback (most recent call last):
  File "/home/Software/BioTools/Anaconda/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/home/Software/BioTools/Anaconda/lib/python2.7/site-packages/drep/controller.py", line 146, in parseArguments
    self.compare_wf_operation(**vars(args))
  File "/home/Software/BioTools/Anaconda/lib/python2.7/site-packages/drep/controller.py", line 91, in compare_wf_operation
    drep.d_workflows.compare_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/Software/BioTools/Anaconda/lib/python2.7/site-packages/drep/d_workflows.py", line 92, in compare_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/home/Software/BioTools/Anaconda/lib/python2.7/site-packages/drep/d_cluster.py", line 282, in d_cluster_wrapper
    Bdb, data_folder, kwargs = parse_arguments(workDirectory, **kwargs)
  File "/home/Software/BioTools/Anaconda/lib/python2.7/site-packages/drep/d_cluster.py", line 311, in parse_arguments
    loc = shutil.which('mash')
AttributeError: 'module' object has no attribute 'which'

I get this exact last error when running with my data too, which leads me this should be related ti an overall installation problem. I also reinstalled it through pip and have the same result. 
I am running on Ubuntu 16.04, and set pyenv to run globally with python 2.7.9 and 3.5.1... 

Any idea what might be going wrong?

**Comment by MrOlm** [comment]
Hello,

Thanks for checking out the program.

I can see from the log you pasted above that dRep is running from python2.7, while it needs to be installed in python3.

As you already have pyenv setup, this should be very easy to do, involving just two commands-

`pyenv global 3.5.1`

`pip install drep`

Please let me know if this is unclear, or if the problem still persists.

Best,
-Matt

**Comment by geboro** [comment]
Thanks for pointing that out!
It seems that if pip is installed under python2, in order to install packages under python3 then we need to either make a virtual environment under python3 or install with pip3 (for Ubuntu). I'm leaving this here as reference:

`sudo apt-get install python3-pip
sudo pip3 install .`

The test_suite is still failing, though, because the nonexistent 'test_backend/ecoli_wd' directory. I ran it manually, as suggested in another thread, and it seems to work `./bin/dRep compare_wf outputdir/ -g ./tests/genomes/*`

**Comment by MrOlm** [comment]
Great! Thank you for troubleshooting and posting the solution for others.

I'll work on getting the test_suite to work, but if it's working for you
when run it manually, everything is almost definitely working correctly.

You can also run the "check dependencies" test to make sure dRep is able to
access and call all the necessary programs for the operation you'd like to
perform.

Thanks again for help troubleshooting, and don't hesitate to post again if
you encounter any other problems.

-Matt

On Aug 10, 2017, at 12:19, German BonillaRosso <notifications@github.com>
wrote:

Thanks for pointing that out!
It seems that if pip is installed under python2, in order to install
packages under python3 then we need to either make a virtual environment
under python3 or install with pip3 (for Ubuntu). I'm leaving this here as
reference:

sudo apt-get install python3-pip sudo pip3 install .

The test_suite is still failing, though, because the nonexistent
'test_backend/ecoli_wd' directory. I ran it manually, as suggested in
another thread, and it seems to work ./bin/dRep compare_wf outputdir/ -g
./tests/genomes/*

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MrOlm/drep/issues/11#issuecomment-321512221>, or mute
the thread

**Comment by hzafeng** [comment]
Hello.
I have set the global env of python:

[zjs@www bins]$ pyenv global
anaconda-2.0.0
3.5.1

but I still fail down the step when DREP call CheckM,

 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/home/zjs/hhf/soft/CheckM-1.0.7/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/zjs/tools/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 1235, in parseOptions
    self.qa(options)
  File "/home/zjs/tools/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 396, in qa
    binIdToModels = markerSetParser.loadBinModels(hmmModelInfoFile)
  File "/home/zjs/tools/anaconda2/lib/python2.7/site-packages/checkm/markerSets.py", line 525, in loadBinModels
    with gzip.open(filename, 'rb') as f:
  File "/home/zjs/tools/anaconda2/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/home/zjs/tools/anaconda2/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/mnt/js/trimmomatic/108_need_out/done/pig1_binning_done/binning/split/bins/bins/dereplicate_wf/data/checkM/checkM_outdir/storage/checkm_hmm_info.pkl.gz'
**!!! checkM failed !!!**

How can I solve this problem?

**Comment by MrOlm** [comment]
Hello,

Has checkM been properly installed? There are some steps that have to be run for it to work properly, like running the command:

`checkm data update`

See https://github.com/Ecogenomics/CheckM/wiki/Installation for more detailed instructions.

What is the response when you try the command:

`$ checkm -h` 

?

What about the command:

`$ drep bonus test --check_dependencies`

?

Best,
-Matt

**Comment by hzafeng** [comment]
Hello,
I can run CheckM  separately.But the 'pyenv' order never  succeed. Can I separately 
 run the  CheckM and then Run the module "Choose" of dRep use the result of CheckM ?
