### ISSUE TITLE
genome information

### ISSUE THREAD

**Issue by Biofarmer** [MrOlm/drep#112]
Hi Matt,

As the formula for scoring is A*Completeness - B*Contamination + C*(Contamination * (strain_heterogeneity/100)) + D*log(N50) + E*log(size) + F*(centrality - S_ani), and only Completeness and Contamination are needed as suggested. May I ask that if only Completeness and Contamination are provided, the other parameters (C,D,E,F) will be treated as 0?

Thanks
Wang

**Comment by MrOlm** [comment]
I don't believe so- I believe dRep will still calculate size and N50 and use those by default. If you'd to treat them as 0, adjust the appropriate flags when running dRep.

Best,
Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Ok, I do not want to set them 0, just curious. How about the other parameters, like strain_heterogeneity and centrality? Will dRep also calculate them?

Thanks
Wang

**Comment by MrOlm** [comment]
strain_heterogeneity will be set to 0 if it's not provided. Centrality, length, and N50 will be automatically calculated by dRep

**Comment by Biofarmer** [comment]
Many thanks
