### ISSUE TITLE
sample name is too long to show completely in the figure

### ISSUE THREAD

**Issue by shaoyanhan** [MrOlm/drep#116]
Dear dRep team,
Thank you for your extraordinary work of this toolkit, which is really helpful in my research field!
But there is a problem interrupted me, if my input sample's name is too long, the figure seems couldn't show the full name. 
![截屏2021-04-21 上午10 55 08](https://user-images.githubusercontent.com/65232041/115492096-b37ae500-a293-11eb-8044-f21fbb57424a.png)

Therefore, when i want to insert the cluster figure in my paper, which might seems not so formal. So, is there any way to draw the name completely in the cluster figure? That will really helps me a lot.

Best wishes,
Shaoyanhan

**Comment by MrOlm** [comment]
Hi Shaoyanhan,

Thanks for the kind. Unfortunately this is a problem with matplotlib (the plotting library used by dRep to make figures), and not something I have a ton of control over. 

If you open up the .pdf file in a .pdf editor (like Inkscape, for example), you'll see that the full sample name is actually present in the text, the "canvas" of the figure is just too small. By adjusting the canvas size you should be able to show the full sample names.

Best,
Matt

**Comment by shaoyanhan** [comment]
Hi Matt,
Thank you very much for your patience and recommendation!
The Inkscape is really powerful to handle this picture scale problem, i've used several ordinary pdf reader but all of them can't show the full size, which confuse me to think it's a pdf problem. Maybe it's time to uninstall them all, LOL.
Thanks a lot again!

Best,
Shaoyanhan

**Comment by MrOlm** [comment]
Happy to help anytime- let me know if you run into any other roadblocks!

Best,
Matt
