### ISSUE TITLE
High Resolution Image

### ISSUE THREAD

**Issue by vappiah** [MrOlm/drep#117]
I used drep for my data and the output were in PDF Format. I would like to know if its possible to generate png or jpeg output. 
Also I would like to generate a high resolution output. Is it possible to specify my desired resolution?

**Comment by MrOlm** [comment]
Hello,

dRep itself doesn't have any ability to produce images besides in .pdf format. By opening up the images in a vector image editor (Inkscape, for example), you should be able to save the image in `png` or `jpeg` formats at whatever resolution you'd like. If you're on a Mac, the "Preview" application that comes pre-installed can also do this.

Best,
Matt

**Comment by vappiah** [comment]
Thanks. I will look into it.
