### ISSUE TITLE
bug in _get_run_genomeInfo()

### ISSUE THREAD

**Issue by nick-youngblut** [MrOlm/drep#118]
At least for drep 3.2, `_get_run_genomeInfo()` wraps 3 functions in `try: ... except:`, which can lead to unexpected consequences. In my case, I was providing a comma-delimited genomeInfo file but the genome names did't match the other input data. Due to the `try: ... except:` logic, the code would throw an error for `_validate_genomeInfo()` and then try to load the csv as a tab-delim table (via `pd.read_table()`), which then produced a "'completeness' not found in header error", which is a very confusing error, given that "completeness" is in the header, but the code just parsed the table with the wrong delimiter

**Comment by nick-youngblut** [comment]
I would probably help to wrap each function in a separate `try: ... except:`. For example

```
        try:
            Idb = pd.read_csv(kwargs.get('genomeInfo'))
        except PARTICULAR_ERROR:
            Idb = pd.read_table(kwargs.get('genomeInfo'))
```

**Comment by Caiyulu-818** [comment]
i also drep the genomes with the genoinfo: message (.csv) ,but it exit with the message:
07-05 20:28 INFO     100.00% of genomes passed length filtering
07-05 20:28 DEBUG    Loading provided genome quality information
07-05 20:28 DEBUG    HERE IS GENOME INFO:
07-05 20:28 DEBUG    
             genome  Completeness  Contamination
0   DRR042264_bin.1         91.98           1.65
1  DRR042264_bin.10         94.73           0.23
2  DRR042264_bin.11         30.88           0.00
3  DRR042264_bin.12          3.51           0.00
4  DRR042264_bin.13         33.49           0.00
07-05 20:28 DEBUG    There are the columns: ['genome', 'Completeness', 'Contamination']
07-05 20:28 DEBUG    HERE IS GENOME INFO:
07-05 20:28 DEBUG    
  genome,Completeness,Contamination
0        DRR042264_bin.1,91.98,1.65
1       DRR042264_bin.10,94.73,0.23
2          DRR042264_bin.11,30.88,0
3           DRR042264_bin.12,3.51,0
4          DRR042264_bin.13,33.49,0
07-05 20:28 DEBUG    There are the columns: ['genome,Completeness,Contamination']

there is no error, why it exit? how can i check the problem?

**Comment by MrOlm** [comment]
Hello,

I'm going to need more info to troubleshoot this problem. What was the output of the program to the screen when it exited? What command were you running? 

Additionally uploading the log file would be helpful (feel free to upload here or send to me at mattolm@stanford.edu)

Best,
MO

**Comment by Caiyulu-818** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi, Thanks for your reply!Here is the command I use :nohup dRep dereplicate /data1/lucy/reference/drep/testmags1 -p 10 -g /data1/lucy/reference/MAGs9000/mags_1/*.fa -comp 50 -con 10 --genomeInfo /data1/lucy/reference/MAGs9000/mags_1/blueinfo.csv --S_algorithm fastANI --multiround_primary_clustering --greedy_secondary_clustering &And attachment is the log file!Best wishesCaiyu 
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lucyncs123
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 07/7/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, Thanks for your reply!Here is the command I use :nohup dRep dereplicate /data1/lucy/reference/drep/testmags1 -p 10 -g /data1/lucy/reference/MAGs9000/mags_1/*.fa -comp 50 -con 10 --genomeInfo /data1/lucy/reference/MAGs9000/mags_1/blueinfo.csv --S_algorithm fastANI --multiround_primary_clustering --greedy_secondary_clustering &And attachment is the log file!Best wishesCaiyu 
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lucyncs123
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 07/7/2021 00:46，Matt ***@***.***> wrote： 



Hello,
I'm going to need more info to troubleshoot this problem. What was the output of the program to the screen when it exited? What command were you running?
Additionally uploading the log file would be helpful (feel free to upload here or send to me at ***@***.***)
Best,
MO

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MrOlm** [comment]
Hello,

It seems that the attachment didn't work. You may have to actually upload it on GitHub's website (https://github.com/MrOlm/drep/issues/118). I would also encourage you to make sure you're on the most up-to-date version of dRep, as some of those parameters are relatively new and have bugs in older versions. You can upgrade with `pip install drep --upgrade`

Best,
MO

**Comment by Caiyulu-818** [comment]
> Hello,
> 
> It seems that the attachment didn't work. You may have to actually upload it on GitHub's website (#118). I would also encourage you to make sure you're on the most up-to-date version of dRep, as some of those parameters are relatively new and have bugs in older versions. You can upgrade with `pip install drep --upgrade`
> 
> Best,
> MO



> Hello,
> 
> It seems that the attachment didn't work. You may have to actually upload it on GitHub's website (#118). I would also encourage you to make sure you're on the most up-to-date version of dRep, as some of those parameters are relatively new and have bugs in older versions. You can upgrade with `pip install drep --upgrade`
> 
> Best,
> MO

here is the log.file ：07-05 16:49 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
07-05 16:49 DEBUG    ***Logger started up at /data1/lucy/reference/MAGs9000/magshalf_1/drep1/log/logger.log***
07-05 16:49 DEBUG    Command to run dRep was: /data2/lcy/anaconda3/envs/dRepy3/bin/dRep dereplicate /data1/lucy/reference/MAGs9000/magshalf_1/drep1 -p 10 -g /data1/lucy/reference/MAGs9000/magshalf_1/magshalf1/DRR042462_bin.11.fa /data1/lucy/reference/MAGs9000/magshalf_1/magshalf1/DRR042462_bin.2.fa ERR1620326_bin.84.fa', '/data1/lucy/reference/MAGs9000/magshalf_1/magshalf1/ERR1620326_bin.87.fa', '/data1/lucy/reference/MAGs9000/magshalf_1/magshalf1/ERR1620326_bin.88.fa', '/data1/lucy/referen07-05 20:28 DEBUG    Filtering genomes by size
07-05 20:28 INFO     100.00% of genomes passed length filtering
07-05 20:28 DEBUG    Loading provided genome quality information
07-05 20:28 DEBUG    HERE IS GENOME INFO:
07-05 20:28 DEBUG    
             genome  Completeness  Contamination
0   DRR042264_bin.1         91.98           1.65
1  DRR042264_bin.10         94.73           0.23
2  DRR042264_bin.11         30.88           0.00
3  DRR042264_bin.12          3.51           0.00
4  DRR042264_bin.13         33.49           0.00
07-05 20:28 DEBUG    There are the columns: ['genome', 'Completeness', 'Contamination']
07-05 20:28 DEBUG    HERE IS GENOME INFO:
07-05 20:28 DEBUG    
  genome,Completeness,Contamination
0        DRR042264_bin.1,91.98,1.65
1       DRR042264_bin.10,94.73,0.23
2          DRR042264_bin.11,30.88,0
3           DRR042264_bin.12,3.51,0
4          DRR042264_bin.13,33.49,0
07-05 20:28 DEBUG    There are the columns: ['genome,Completeness,Contamination']

**Comment by Caiyulu-818** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Ok, thanks, I will load it in the GitHub, and the version of my drep is dRep v3.2.2BestLucy
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lucyncs123
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 07/8/2021 00:07，Matt ***@***.***> wrote： 



Hello,
It seems that the attachment didn't work. You may have to actually upload it on GitHub's website (#118). I would also encourage you to make sure you're on the most up-to-date version of dRep, as some of those parameters are relatively new and have bugs in older versions. You can upgrade with pip install drep --upgrade
Best,
MO

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MrOlm** [comment]
Hello,

OK- I see the problem now is that the columns `Completeness' and 'Contamination' that you have in the input file should be all lower-case (e.g. `completeness` and `contamination`).

Please let me know if that doesn't fix the problem.

Best,
MO

**Comment by Caiyulu-818** [comment]
> Hello,
> 
> OK- I see the problem now is that the columns `Completeness' and 'Contamination' that you have in the input file should be all lower-case (e.g. `completeness`and`contamination`).
> 
> Please let me know if that doesn't fix the problem.
> 
> Best,
> MO

ok, i tried it, it worked! Thank  you so much !
