### ISSUE TITLE
Comparison to binning_refiner?

### ISSUE THREAD

**Issue by franciscozorrilla** [MrOlm/drep#119]
Hi Matt,

I was wondering if you have compared the performance of dRep against other tools like binning_refiner or metaWRAP's bin refinement module? In the dRep article the focus seems to be on dereplicating MAGs from different samples, but in theory I should be able to dereplicate MAGs from the same sample yet generated by different binners/assemblers, correct?

Best wishes,
Francisco

**Comment by MrOlm** [comment]
Hi Francisco,

I haven't done any benchmarks, but I agree that it should work for that purpose. The only tool like that I've used is DAS_tool (https://github.com/cmks/DAS_Tool), which doesn't actually do genomic comparisons, it just uses "scaffold to bin" files, which makes things run faster.

Best,
Matt

**Comment by franciscozorrilla** [comment]
Fantastic, thanks!
