### ISSUE TITLE
how many genomes can the drep deal with?

### ISSUE THREAD

**Issue by Caiyulu-818** [MrOlm/drep#123]
when the genomes >5000+, i can be divided into 5000 batch, but i want to how many genomes maximum can input ?

**Comment by MrOlm** [comment]
Hello,

There's no "maximum" input, but the more genomes you have the longer it takes to run. With `--multiround_primary_clustering` and `--greedy_secondary_clustering`, I've run up to 350,000 genomes

-MO

**Comment by Caiyulu-818** [comment]
Oh thank u for your reply, I will try it. lucy ***@***.*** 签名由 网易邮箱大师 定制 On 07/02/2021 00:00, Matt Olm wrote: Hello, There's no "maximum" input, but the more genomes you have the longer it takes to run. With --multiround_primary_clustering and --greedy_secondary_clustering, I've run up to 350,000 genomes -MO — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
