### ISSUE TITLE
ValueError: The number of observations cannot be determined on an empty distance matrix.

### ISSUE THREAD

**Issue by mewu3** [MrOlm/drep#124]
Hello, 

I have the same trouble as the others with the distance matrix, there is 1760 genomes of enterovirus A in the folder. I don't know what is wrong here since my other commande line passed `dRep cluster -p 12 -sa 0.95 -nc 0.85 dRep_output/ -g enterovirus/*fasta`, though it's still running at step 3. 

**Commande line :** 
```
dRep cluster -sa 0.95 -nc 0.85 dRep_enterovirusA/ -g Enterovirus_A/*
```

**Stdout message :** 
```
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
2b. Cluster pair-wise MASH clustering
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.8/dist-packages/drep/controller.py", line 151, in parseArguments
    self.cluster_operation(**vars(args))
  File "/usr/local/lib/python3.8/dist-packages/drep/controller.py", line 56, in cluster_operation
    drep.d_cluster.d_cluster_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/drep/d_cluster.py", line 79, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(list(Bdb['location'].tolist()), \
  File "/usr/local/lib/python3.8/dist-packages/drep/d_cluster.py", line 177, in cluster_genomes
    Cdb, cluster_ret = cluster_mash_database(Mdb, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/drep/d_cluster.py", line 638, in cluster_mash_database
    Cdb, linkage = cluster_hierarchical(linkage_db, linkage_method= P_Lmethod, \
  File "/usr/local/lib/python3.8/dist-packages/drep/d_cluster.py", line 470, in cluster_hierarchical
    linkage = scipy.cluster.hierarchy.linkage(arr, method= linkage_method)
  File "/usr/lib/python3/dist-packages/scipy/cluster/hierarchy.py", line 1064, in linkage
    n = int(distance.num_obs_y(y))
  File "/usr/lib/python3/dist-packages/scipy/spatial/distance.py", line 2403, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix. 
```

Please help !

**Comment by MrOlm** [comment]
Hello,

Can you please send me the following info so I can help troubleshoot:

1) Please send me the output of the command `dRep check_dependencies`

2) Please send me your log file (in the `log` folder; please feel free to upload here to send to me at mattolm@stanford.edu)

Best,
MO

**Comment by mewu3** [comment]
Hello, 

Thank you very much for your reply, Sir. 

First of all, `dRep check_dependencies` does not work, `usage: dRep [-h] {filter,cluster,choose,analyze,bonus,evaluate,dereplicate,compare} ... dRep: error: argument operation: invalid choice: 'check_dependencies' (choose from 'filter', 'cluster', 'choose', 'analyze', 'bonus', 'evaluate', 'dereplicate', 'compare')`

As for the log, the folder has been deleted (SORRY) so I could not provide any log information. I rerun the command in the enterovirus_A folder this morning and magically the command passed. 

But I do have a question about the Cdb.csv file, I would like to arrange my genomes into different clusters according to Cdb.csv. I don't get the meaning of the 1_1 which refers to secondary_cluster and the value of the threshold. Could you please kindly explain the meaning of this file ?

``` 
genome,secondary_cluster,threshold,cluster_method,comparison_algorithm,primary_cluster
KF015732.1.fasta,1_1,0.050000000000000044,average,ANImf,1
KF812551.1.fasta,1_1,0.050000000000000044,average,ANImf,1
KX060810.1.fasta,1_1,0.050000000000000044,average,ANImf,1
MH128992.1.fasta,2_1,0.050000000000000044,average,ANImf,2
MH128993.1.fasta,2_1,0.050000000000000044,average,ANImf,2
```

**Comment by MrOlm** [comment]
OK, that just means you have an older version of dRep. You can upgrade with `pip install drep --upgrade`. You can also check your dependencies in the older version using the command `dRep bonus test --check_dependencies`. But if it's working now, there's no reason to upgrade dRep.

1_1 is just the name of the cluster. It refers to the fact that it's primary cluster 1, secondary cluster 1. Genomes in the same cluster are the "same" based on the threshold selected. The only column columns you really need from this file are `genome` and `secondary_cluster`.

Best,
Matt

**Comment by mewu3** [comment]
Thank you a lot, have a good day !
