### ISSUE TITLE
Centroid of clusters

### ISSUE THREAD

**Issue by mewu3** [MrOlm/drep#125]
Hello, sir, 

I'm wondering if dRep can find the centroid of each cluster (or the representation of cluster in another to say) ?

**Comment by MrOlm** [comment]
Hello,

You can change the way that dRep clusters the distance matrix by altering the variable `--clusterAlg `

The default is "average", but "centroid" is also an option. See here for a full list of the options and what they do: https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html

For a little more on hierarchical clustering in the context of dRep see here: https://drep.readthedocs.io/en/latest/choosing_parameters.html#oddities-of-hierarchical-clustering

Best,
MO

**Comment by mewu3** [comment]
Hello, Sir, 

Yes i'm aware of the different algorithms of clustering, the thing is i want to have a list a genomes that represent all clusters with algo average. I don't see how dRep could give me that.

**Comment by mewu3** [comment]
Hello, 

I still don't see how i can get a list of genomes the represent the output clusters like CD-HIT do ... 

Best wishes, 
MJ36

**Comment by MrOlm** [comment]
The file `Cdb.csv` in data_tables has two columns (among others): `genome` and `secondary_cluster`. This lists which cluster each genome belongs to. An example is here (https://github.com/MrOlm/drep/blob/master/tests/test_solutions/ecoli_wd/data_tables/Cdb.csv). In that file, all of the genomes are in their own clusters except `Enterococcus_faecalis_T2.fna` and `Enterococcus_faecalis_YI6-1.fna`, which are in the same cluster (cluster `1_1`).

The file `Wdb.csv` lists the representatives of each cluster. In this file we can see that `Enterococcus_faecalis_YI6-1.fna` is the representative of this cluster (https://github.com/MrOlm/drep/blob/master/tests/test_solutions/ecoli_wd/data_tables/Wdb.csv).

Does this answer your question?

-MO

**Comment by mewu3** [comment]
The Wdb.csv file I got here does not have the same format ... 
```
genome1,genome2,dist,similarity
KF990476.1.fasta,KF990476.1.fasta,0.0,1.0
KC436269.1.fasta,KF990476.1.fasta,0.191731,0.808269
JX961708.1.fasta,KF990476.1.fasta,0.295981,0.704019
FJ769381.1.fasta,KF990476.1.fasta,0.295981,0.704019
JQ946052.1.fasta,KF990476.1.fasta,0.23011,0.76989
KJ170529.1.fasta,KF990476.1.fasta,0.295981,0.704019
KJ686202.1.fasta,KF990476.1.fasta,0.203604,0.796396
JF799986.1.fasta,KF990476.1.fasta,0.191731,0.808269
JX976770.1.fasta,KF990476.1.fasta,0.149777,0.850223
KF812551.1.fasta,KF990476.1.fasta,0.210897,0.78910303
JX274980.1.fasta,KF990476.1.fasta,1.0,0.0
HM031191.1.fasta,KF990476.1.fasta,0.126974,0.873026
KJ686155.1.fasta,KF990476.1.fasta,0.203604,0.796396
KJ170498.1.fasta,KF990476.1.fasta,0.295981,0.704019
KJ686195.1.fasta,KF990476.1.fasta,0.191731,0.808269
KJ170580.1.fasta,KF990476.1.fasta,0.23011,0.76989
KJ170547.1.fasta,KF990476.1.fasta,1.0,0.0
KJ686165.1.fasta,KF990476.1.fasta,0.203604,0.796396
JQ806378.1.fasta,KF990476.1.fasta,0.203604,0.796396
```

**Comment by MrOlm** [comment]
That file is usually named `Mdb.csv`. I'm not sure how the mix-up could have happened. I would recommend upgrading to the most recent version of dRep and trying again
