### ISSUE TITLE
Interpretation of dendrograms

### ISSUE THREAD

**Issue by franciscozorrilla** [MrOlm/drep#126]
Hi Matt,

I am assembling 9 soil bacteria isolate sequencing samples using various methods, and then running `dRep` to compare and dereplicate the genomes. This is the primary clustering dendrogram generated by `dRep`:

![image](https://user-images.githubusercontent.com/35606471/127191806-a377f8d7-832f-4e1c-a9fc-b69b154fb6fc.png)

Perhaps I am interpreting the plots incorrectly, but I was quite shocked to see how different the ANIs are across samples. Does this mean that sample lane*44 has 0% similarity to all other samples? Is this even possible, or have I clearly done something wrong?

I was also wondering why sample lane*40 seems to have two distinct clusters in the primary dendrogram plot, but in the secondary dendrogram plot there is almost no difference between the genomes:

![image](https://user-images.githubusercontent.com/35606471/127198167-b7ac30ff-7d1f-4bf4-8335-5d49e5493f85.png)

I see that two distinct identity algorithms are used, is the secondary one more sensitive?

Thanks and best wishes,
Francisco

**Comment by MrOlm** [comment]
Hi Francisco,

You're exactly right that the secondary algorithm is more sensitive. The algorithm used for primary clustering (MASH) is very fast, but not very accurate or sensitive. The lowest ANI it can detect is ~75% and after that it will just report "0". Similarly it impacted by genome incompleteness. 

The secondary algorithms are slower but more accurate. In your case, with that few genomes, you don't really need to do primary clustering though. I would recommend running with the parameter `--SkipMash`, which will just just the more accurate algorithm.

Similarly you have a couple of choices for the secondary (more accurate) algorithm, which you can alter with the `--S_algorithm` parameter. See here for discussion about their differences: https://drep.readthedocs.io/en/latest/choosing_parameters.html#overview-of-genome-comparison-algorithms

Best,
Matt

**Comment by ccskas6** [comment]
Hi Matt, 

I also have a quick question about the dendrograms. I apologize if that has already been answered in a different issue. Is the actual tree file available somewhere in the output files? I would like to load the dendrogram into iTol and further annotate it. 

Thank you! 
Christina

**Comment by MrOlm** [comment]
Hello,

Unfortunately no, there is no tree file created among the outputs. Technically what is created by dRep is a dendrogram, which is different conceptually than phylogenetic trees, but it is possible to convert the distance matrix (Ndb.csv) into a tree file to load it into iTol. I've done this previously using python- if you'd like me to send some example code I'd be happy to do it.

Best,
Matt

**Comment by ccskas6** [comment]
Thank you for your reply, Matt! I will use the distance matrix for now. 

Thanks again, 
Christina
