### ISSUE TITLE
checkM quality default values

### ISSUE THREAD

**Issue by jsgounot** [MrOlm/drep#129]
Hi,

thanks for this tool, it's very useful. I would like to know how were defined the default checkm values for filtering. It does not relate to any of the MIMAG standards and I didn't find a clear explanation in your paper. 25% contamination seems  a lot to me.

Thanks !

**Comment by MrOlm** [comment]
Hello,

Thanks for the kind words. The Completeness and Contamination filters were chosen very arbitrarily; there's not a good reason for them. I would change them to whatever thresholds you'd like with confidence!

Best,
MO

**Comment by jsgounot** [comment]
Hi,

Like most of us, I don't know and don't think there are single good thresholds for all cases. That's why I was curious about your filters and wondered if they were resulting from some testing or not. Thanks for the quick answer !

Regards,
JSG
