### ISSUE TITLE
strain_heterogeneity in genomeInfo

### ISSUE THREAD

**Issue by aistBMRG** [MrOlm/drep#130]
Hi,

Thanks for developing drep !

Just a small question. As running checkM can be time-consuming, I am using the pipeline with checkM values I had already calculated. Now, it seems that this file (genomeInfo ) only needs to contain completeness and contamination estimates. However, for scoring, it seems that the formula provided in the "help" of dRep contains the component "strain_heterogeneity." Would it be possible to clarify how this works, is that part just ignored (C weight becomes zero)?

Thanks,

Dieter

**Comment by MrOlm** [comment]
Hi Dieter,

Yes that's exactly right- when genomeInfo is provided the scoring just sets "strain_heterogeneity" weight to 0. If you're interested in providing the strain_heterogeneity values there is a round-about way of doing it- just let me know if you'd like me to explain. But in general I find the strain_heterogeneity values to not be very useful anyways.

Best,
Matt

**Comment by aistBMRG** [comment]
Hi Matt,

Thanks for the prompt response. I will stick with using genome completeness/contamination only.

Best,

Dieter
