### ISSUE TITLE
The failure of secondary cluster

### ISSUE THREAD

**Issue by SarahIsme** [MrOlm/drep#131]
Hello,

I have 413 bins, and there should have less bins after dereplication according to the primary clustering dendrogram. However, after dereplication, there are still 413 bins even though "-sa" was set as 0.99.  

The command is dRep dereplicate drep/ -g bins/*.fa -comp 50 -p 150 --genomeInfo checkm.csv

Please check the attached files. 

Thanks in advance.

Sarah

[Primary_clustering_dendrogram.pdf](https://github.com/MrOlm/drep/files/7295838/Primary_clustering_dendrogram.pdf)
[Secondary_clustering_dendrograms.pdf](https://github.com/MrOlm/drep/files/7295839/Secondary_clustering_dendrograms.pdf)

[warnings.txt](https://github.com/MrOlm/drep/files/7295837/warnings.txt)

**Comment by MrOlm** [comment]
Hmm- the error you're getting is 

```Error: Multiple query file is only supported with the SAM output format
Usage: nucmer [options] ref:path qry:path+
Use --help for more information
ERROR: Could not parse delta file, /home/iwtr/HJH/drep/data/ANImf_files/S21_bin.9.fa/S21_bin.9.fa_vs_S21_bin.9.fa.delta
error no: 400
```

What version of mummer are you running? One potential way of fixing this problem would be to add `--S_algorithm fastANI` or `--S_algorithm ANIn`
'
-MO

**Comment by MrOlm** [comment]
Oh weird! Glad it's working now!
