### ISSUE TITLE
python join type error with large genome db

### ISSUE THREAD

**Issue by b-tierney** [MrOlm/drep#135]
Hi,

Thanks for putting together and managing such a stellar tool. I'm trying to dRep a pretty large genome db (refseq + the mouse MAG database, about 14K genomes) for use in kraken2 and getting an error I've never seen before. Here is the command:

#!/bin/bash
input_folder=$1
dRep dereplicate "$1"-drep_workdir \
        -g "${input_folder}"/* \
        -p 20 \
        -comp 50 \
        -pa 0.9 \
        --multiround_primary_clustering \
        -sa 0.95 \
        -nc 0.30 \
        --ignoreGenomeQuality \
        -cm larger \

And here is the output:

***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
14,431 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
  Will split genomes into 3 groups for primary clustering
Traceback (most recent call last):
  File "/home/btt4001/miniconda3/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 110, in all_vs_all_MASH
    genome_chunks = run_mash_on_genome_chunks(genome_chunks, mash_exe, sketch_folder, MASH_folder, logdir,  **kwargs)
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 173, in run_mash_on_genome_chunks
    cmds += GC.gen_sketch_cmds(mash_exe, MASH_s)
  File "/home/btt4001/miniconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 35, in gen_sketch_cmds
    file = os.path.join(self.chunk_folder, name)
  File "/home/btt4001/miniconda3/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/btt4001/miniconda3/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'float'

I haven't had any issues running on smaller subsets of genomes, so I'm thinking that there is a problem with one of my genomes. Does this error mean anything to you? Would love to know if you might know what sort of data issue it might indicate...

Thanks,
Braden

**Comment by MrOlm** [comment]
Hi Braden,

Interesting- I've never seen that error before either. It seems like it might have something to do with the naming of folders somehow? A couple of questions-

1) Can you confirm you're running the most up-to-date version of dRep?

2) Do you know how quickly this error happens? Is it like right away or does it take a while?

3) Could you try with a different, simpler work_directory name? Something just like "test" or whatever with no special characters?

4) If (3) doesn't work, could you send me the log file? (named something like `log/log.log`)

Thanks,
Matt

**Comment by b-tierney** [comment]
Thanks for the fast response!

1 -- running 3.2.2

2 -- hmm hard to say -- probably happened about 90 minutes into running, but I wasn't watching the exact time.

3 -- Trying again with simpler wd named test + removing all underscores/hyphens etc, will follow up here when it's done.

One other thing -- previously I was getting an error due to excessively long genome names, so I just cp'd and renamed everything with an incrementing bash loop:

![Screen Shot 2021-12-02 at 12 50 37 PM](https://user-images.githubusercontent.com/20242238/144476212-c2d1ff07-2ee3-4f19-bdf2-4bccd1350a9e.png)

They go all the way down to "vjb." Maybe there is some 3 character illegal filename in there?

**Comment by MrOlm** [comment]
Ah ok. I don't think that re-naming would be a problem, but in this next run we should try without it.

You can submit your genomes as a text file list to dRep using the same `-g` argument. So you can just do `ls [all genomes] > genome_names.txt`, then provide `genome_names.txt` to dRep with `-g genome_names.txt`

Best,
Matt

**Comment by b-tierney** [comment]
Got it. I'll let you know when this run finishes, still at the clustering step with no issues thus far.

To be clear, the long name issue didn't appear to be a dRep problem, I have a few genomes that are literally too long for python to open(), so in lieu of tracking them down I just renamed everything.

**Comment by b-tierney** [comment]
Same issue as before -- here are the logfile contents. Will try again appending .fna to the end of all the filenames...
[logger.log](https://github.com/MrOlm/drep/files/7644405/logger.log)

**Comment by MrOlm** [comment]
OK interesting. Could you also upload the file `Bdb.csv`, created in the `data_tables` folder? I think that should have been made before it crashed.

-Matt

**Comment by b-tierney** [comment]
So the run with .fna filenames got past the point where it was crashing, but then died due to another memory error on secondary clustering. I'm moving over to a larger machine to see if I can get it to complete. Will keep you posted! In the meantime here is that file.

[Bdb.csv](https://github.com/MrOlm/drep/files/7650516/Bdb.csv)

**Comment by b-tierney** [comment]
Update -- looks like it completed! 

So either the initial issue was an illegal 3 character name or a bizarre memory error?

Please let me know if there is anything else I can do to help get to the bottom of this, and thanks again. Will close for now but certainly can reopen if needed.
