### ISSUE TITLE
Question about d_filter.py

### ISSUE THREAD

**Issue by TJrogers86** [MrOlm/drep#142]
Hello,
Let me start by saying I love this program! That said, I have one small issue I was hoping you could resolve for me. When I run Checkm on its own on the .fa with reduced tree I get the follow:
![WhatsApp Image 2022-03-09 at 5 38 27 PM](https://user-images.githubusercontent.com/48442658/157704504-a9959bd1-55c4-47a3-a37a-c5fdc20ba63c.jpeg)

But when I run drep, I get the following:
![WhatsApp Image 2022-03-09 at 5 38 22 PM](https://user-images.githubusercontent.com/48442658/157704625-56d37733-6fcc-4b35-ba9c-aed78eaf0bf2.jpeg)

I believe the difference in the completeness and contamination are due to me using the reduced tree, when I believe you do not. Ergo your results are more correct. However, I was stumped on why the N50 should be different. Then I came across the following warning in the d_filter.py:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/48442658/157705415-1ba27fb1-8de9-4b8a-91f1-d0395003edd5.png">

I wonder if this is why my reported N50 from checkm and drep are so different? If so, why would drep run checkm on the prodigal files when I provided the .fa files? My log looks like this:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/48442658/157705925-1b5b5c9c-96f3-4cb0-b57f-d3b8e15991ab.png">

So I assume drep used the .faa for checkm? Thanks for any clarification you can give!

**Comment by TJrogers86** [comment]
Thanks for the quick response. Now my question is who's N50 value should I trust: Checkm's or dRep's? Not that this is an end all be all, its just out of curiosity as to why both programs give the same length but different N50 values. The formula to calculate N50 should be the same, no?

**Comment by MrOlm** [comment]
I've never directly compared, but I assume  that the N50 reported by checkM and the N50 calculated by dRep (available in the file "genomeInfo.csv") are the same or about the same?

Anyways, dRep's calculation is performed using the following relatively simple method:

```
def calc_n50(loc):
    '''
    Calculate the N50 of a .fasta file
    Args:
        fasta_loc: location of .fasta file.
    Returns:
        int: N50 of .fasta file.
    '''
    lengths = []


    if loc[-3:] == '.gz':
        with gzip.open(loc, "rt") as handle:
            for seq_record in SeqIO.parse(handle, "fasta"):
                lengths.append(len(seq_record))
    else:
        for seq_record in SeqIO.parse(loc, "fasta"):
            lengths.append(len(seq_record))

    # for seq_record in SeqIO.parse(loc, "fasta"):
    #     lengths.append(len(seq_record))

    half = sum(lengths)/2
    tally = 0
    for l in sorted(lengths, reverse=True):
        tally += l
        if tally > half:
            return l
```

**Comment by TJrogers86** [comment]
It should be the same, but it is different (see example above). Either way, thank you for all your help!

**Comment by MrOlm** [comment]
I see- sorry for the confusing. The N50 reported by dRep in other tables (like `Chdb.csv`) is incorrect and based on genes, so I thought that's where the problem was

-MO
