### ISSUE TITLE
Input format of "dRep dereplicate"

### ISSUE THREAD

**Issue by B-1991-ing** [MrOlm/drep#144]
Dear dRep support team,

I am trying to run the command line below. But, I want to know that could I directly use "*" to represent "*.fna" and "*.fa" under my bin_dir? Because I have two bin file types - "*.fna" and "*.fa" there.

**Command lines**
bin_dir=/home/projects/env_10000/people/binson/Current_pipeline/binning/bins_coindiv/
dRep dereplicate -p 16 ${outout_directory} -g ${bin_dir}* -comp 90 -con 5 --debug

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear dRep support team,

**Update**

I wrote the absolute directories of all bins that need to be dereplicated into one txt file (bins_coindiv.txt), then ran the command line below. It worked.

**Command lines** 
GENOMES=/home/projects/env_10000/people/binson/Current_pipeline/bins_dereplicate/**bins_coindiv.txt**
outout_directory=/home/projects/env_10000/people/binson/Current_pipeline/binning/bins_dereplicate/drep/
dRep dereplicate ${outout_directory} -g ${GENOMES} -p 16 -sa 0.99 -comp 90 -con 5 --debug

Best,

Bing

**Comment by MrOlm** [comment]
Wonderful! Just to confirm, you have no further questions or problems with using dRep?

Best,
MO

**Comment by B-1991-ing** [comment]
Hi MO,

Thank you for your reply. No other questions until now. 

Best,

Bing
