### ISSUE TITLE
ANIcalculator not being identified even when it is in the system path?

### ISSUE THREAD

**Issue by TommyH-Tran** [MrOlm/drep#146]
dRep` compare /Users/klemonlab/Downloads/Drep_Ctu_supergroup -g /Users/klemonlab/Downloads/Ctu_supergroup/*.fasta -p 6 -sa 0.98 -nc 0.6 --S_algorithm gANI
***************************************************
    ..:: dRep compare Step 1. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
1 primary clusters made
Running secondary clustering
Running 2500 gANI comparisons- should take ~ 41.7 min
Traceback (most recent call last):
  File "/Users/klemonlab/opt/anaconda3/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/controller.py", line 102, in parseArguments
    self.compare_operation(**vars(args))
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/controller.py", line 53, in compare_operation
    drep.d_workflows.compare_wrapper(kwargs['work_directory'],**kwargs)
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_workflows.py", line 89, in compare_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_cluster/controller.
py", line 35, in main
    self.run_secondary_clustering()
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_cluster/controller.py", line 140, in run_secondary_clustering
    Ndb, Cdb, c2ret = drep.d_cluster.compare_utils.secondary_clustering(self.Bdb, self.MCdb, algorithm, self.wd.get_dir('data'), wd=self.wd, **self.kwargs)
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 298, in secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_cluster/compare_utils.py", line 380, in compare_genomes
    df = drep.d_cluster.external.run_pairwise_gANI(bdb, working_data_folder, \
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/d_cluster/external.py", line 197, in run_pairwise_gANI
    gANI_exe = drep.get_exe('ANIcalculator')
  File "/Users/klemonlab/opt/anaconda3/lib/python3.9/site-packages/drep/__init__.py", line 100, in get_exe
    raise ValueError("{0} isn't working- make sure its installed".format(name))
ValueError: ANIcalculator isn't working- make sure its `installed

--------------

I am getting the error above saying ANIcalculator isn't working or installed when it is? Not sure how to fix this issue and I am on MacOS. 
<img width="704" alt="Screen Shot 2022-05-09 at 20 52 03" src="https://user-images.githubusercontent.com/60275107/167526614-dee5ba6c-a4bb-4971-b49d-590ccbfbd279.png">

**Comment by SebasSaenz** [comment]
Hi, 

I am having the same issue including mash. Were you able to fix this issue?

Cheers

**Comment by TommyH-Tran** [comment]
@SebasSaenz Did you download mash and put it in your $PATH? Are you on MacOS? No, I have not been able to fix the ANIcalculator issue, but my mash works I think.

**Comment by SebasSaenz** [comment]
@TommyH-Tran I am using a cluster with Red-hat. I followed the conda installation, however it seems that something is going wrong. I can see the dependencies in the PATH but dRep shows an error after running.


dRep check_dependencies

mash.................................... !!! ERROR !!!   (location = /beegfs/work/workspace/ws/ho_kezau83-conda-0/conda/envs/drep/bin/mash)
nucmer.................................. all good        (location = /beegfs/work/workspace/ws/ho_kezau83-conda-0/conda/envs/drep/bin/nucmer)
checkm.................................. !!! ERROR !!!   (location = None)
ANIcalculator........................... !!! ERROR !!!   (location = None)
prodigal................................ all good        (location = /beegfs/work/workspace/ws/ho_kezau83-conda-0/conda/envs/drep/bin/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ !!! ERROR !!!   (location = None)
fastANI................................. !!! ERROR !!!   (location = /beegfs/work/workspace/ws/ho_kezau83-conda-0/conda/envs/drep/bin/fastANI)

I tried to install from scratch and also:

conda update mash --force-reinstall

Nothing worked.

**Comment by MrOlm** [comment]
Hello all,

If the dependency shows up in the path with check_dependencies, the next thing to do is to run dRep  in debug mode by including the flag `-d`. This will create a folder in the log folder with the STDOUT and STDERR from all external commands dRep runs; this way you can see the exact reason why a dependency is failing. Let me know if you have any questions

-MO

**Comment by MrOlm** [comment]
Hi Johan,

With that error it would be really expected that mash would show up as not working with `dRep check_dependencies`. Indeed, in your message above, it shows mash as having `!!! ERROR !!!`. That dependency needs to be installed properly for it to work within dRep.

What happens when you run the command `/beegfs/work/workspace/ws/ho_kezau83-conda-0/conda/envs/drep/bin/mash -h`?  

-MO

**Comment by SebasSaenz** [comment]
Hi,

The command gave me the following

mash -h

bin/mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

**Comment by MrOlm** [comment]
Hi @SebasSaenz - that's your problem. I don't really understand how C++ works (the language that mash is written in), so  I cannot help troubleshoot this, but this is the reason mash isn't working. You may be able to fix this problem with mash by googling around or by asking the developers of mash directly.

Best,
MO

**Comment by SebasSaenz** [comment]
Hi,

Now it is working for me. First, I create an environment for drep, then I install mash 2.2 and finally drep. Now every dependency is working.

Maybe is a problem with mash 2.3.

Cheers,

Johan Sebastián

**Comment by MrOlm** [comment]
Great! Thank you for the update

-Matt

**Comment by EisenRa** [comment]
I also had this issue today, and was able to fix it by forcing a specific version of libgsl ([see this issue](https://github.com/ParBLiSS/FastANI/issues/96#issue-1183963894)):

` mamba install -c conda-forge gsl=2.7=he838d99_0`

@MrOlm would it be possible to update the dRep bioconda recipe to take this into account? I'm developing a snakemake pipeline that uses conda/mamba to handle dependencies, and am having to manually force the libgsl version.

**Comment by MrOlm** [comment]
Hi @EisenRa ,

I actually don't maintain the bioconda recipe (someone else uploaded it and made the dependency requirements), but I would also be hesitant to force a specific version of gsl because I'd be worried it would break other people's installations.

I do believe you could submit a pull request for ANICalculator through bioconda, though.

Best,
Matt
