### ISSUE TITLE
centrifuge :: dependency or not ?

### ISSUE THREAD

**Issue by EricDeveaud** [MrOlm/drep#148]
Hello, 

while installing and testing dRep 3.2.2 I ran dRep check_dependecies and got the following output 

```
centrifuge.............................. !!! ERROR !!!   (location = None)
```
regarding #143 centrifuge seems to be unneeded but it stills check for presence

so is centrifuge required or not ?

regards

Eric

**Comment by MrOlm** [comment]
Hello,

Centrifuge is not required for anything. `check_dependecies` gives a report on all dependencies that **might** be required, but for any one thing you want dRep to do you only need to have some subset of them installed. See here for more info- https://drep.readthedocs.io/en/latest/installation.html#dependencies

-Matt
