### ISSUE TITLE
please tag a release 

### ISSUE THREAD

**Issue by EricDeveaud** [MrOlm/drep#149]
Hello 

drep is now in version 3.2.2 while last tagged version is 3.0.0. 
can you please tag a release in order to be in sync.

regards

Eric

**Comment by MrOlm** [comment]
Hi Eric,

I make a lot of point updates on dRep and I only tag releases with major updates.

The most up-to-date release and an archive of all releases ever made is available on pypi (https://pypi.org/project/drep/)

Best,
Matt
