### ISSUE TITLE
AttributeError: 'module' object has no attribute 'which'

### ISSUE THREAD

**Issue by Klcross** [MrOlm/drep#15]
Hello,

I have tried installing dRep by first installing python3 from homebrew, then downloading pip, then downloading mummer and mash and scikit-learn (not this straightforward but ultimately got to this point upon troubleshooting things I seemed to need). 

First I was getting this error at the end of trying to install:
`error: Installed distribution numpy 1.8.0rc1 conflicts with requirement numpy>=1.9.0`

But I believe I overcame this by instead of just using '`python setup.py install`' but by linking to the python in my bin that had the numpy:
`bash-3.2# /usr/bin/python setup.py install`
and it seemed to install successfully. However I also tried to install numpy to python3 since it seemed to be missing by:
`karissas-mbp:~ ikf$ brew install numpy --with-python3 --without-python`

NOW, however, when I try 
`karissas-mbp:dRep ikf$ dRep bonus testDir --check_dependencies`
or 
`karissas-mbp:tests ikf$ python test_suite.py `
I get the same error:
```
Traceback (most recent call last):
  File "test_suite.py", line 852, in <module>
    cluster_test()
  File "test_suite.py", line 788, in cluster_test
    verifyCluster.run()
  File "test_suite.py", line 421, in run
    self.functional_test_3()
  File "test_suite.py", line 502, in functional_test_3
    controller.parseArguments(args)
  File "/Library/Python/2.7/site-packages/drep-1.4.3-py2.7.egg/drep/controller.py", line 151, in parseArguments
    self.cluster_operation(**vars(args))
  File "/Library/Python/2.7/site-packages/drep-1.4.3-py2.7.egg/drep/controller.py", line 56, in cluster_operation
    drep.d_cluster.d_cluster_wrapper(kwargs['work_directory'],**kwargs)
  File "/Library/Python/2.7/site-packages/drep-1.4.3-py2.7.egg/drep/d_cluster.py", line 53, in d_cluster_wrapper
    Bdb, data_folder, kwargs = parse_arguments(workDirectory, **kwargs)
  File "/Library/Python/2.7/site-packages/drep-1.4.3-py2.7.egg/drep/d_cluster.py", line 297, in parse_arguments
    loc = shutil.which('mash')
AttributeError: 'module' object has no attribute 'which'
```

I have a feeling that it has something to do with my pythons but I cannot seem to figure out how to get around this! 

Thank you for your time in helping me troubleshoot this.
Karissa

**Comment by MrOlm** [comment]
Hi Karissa,

I think you're right that this has to do with pythons. That error results when trying to run dRep with python2, when it's actually a python3 program.

**Comment by Klcross** [comment]
Any suggestions on how to get around this? Since MacOS tends to push towards the 2.7? 

My python3 is located at and has the following:
```
karissas-mbp:Python-3.4.1 ikf$ ls
Doc			PCbuild			libpython3.4m.a
Grammar			Parser			platform
Include			Python			pybuilddir.txt
LICENSE			README			pyconfig.h
Lib			Tools			pyconfig.h.in
Mac			build			pytest
Makefile		config.guess		python-config
Makefile.pre		config.log		python-config.py
Makefile.pre.in		config.status		python.exe
Misc			config.sub		python.exe-gdb.py
Modules			configure		setup.py
Objects			configure.ac
PC			install-sh
karissas-mbp:Python-3.4.1 ikf$ pwd
/Users/ikf/Python-3.4.1
```

But I haven't had luck trying to re-direct to this python in dRep and I am not sure if a straight download of python3 has all of the essentials (numpy?) since I had to direct to the python2 for the download. 

Even just brainstorming helps me out! If I can't get it locally I will try installing it on our servers which should bypass the Mac python problem hopefully.

Karissa

**Comment by MrOlm** [comment]
Hmmm. So as I said above, `pyenv` is probably the best option. As far as things that might work, you could try:

`pip3 install dRep`

This should install dRep and all of the dependencies (like numpy). Then to run it, you could try:

`python3 dRep -h`

-Matt

**Comment by Klcross** [comment]
I apologize the rest of your comment was cutoff when I first read it. Let me give these things a try, thanks!

Karissa

**Comment by MrOlm** [comment]
I'm closing this now- happy to re-open if you have more questions!
