### ISSUE TITLE
dRep: Argument list too long

### ISSUE THREAD

**Issue by RiversDong** [MrOlm/drep#151]
Dear Matt Olm,
I meet an error when running dRep v3.3.0 (dRep  -h indicates the version is 3.3.0), showing that "dRep: Argument list too long".
I tried the solution listing at https://github.com/MrOlm/drep/issues/42.

However, an error happened again "dRep: error: argument operation: invalid choice: 'bonus' (choose from 'dereplicate', 'compare', 'check_dependencies')".  My command is “dRep bonus /home/chuand/data/my_representatives --check_dependencies”.

I am looking forward to hearing from you.

Best

**Comment by MrOlm** [comment]
Hello,

What is the command you're trying to run? Compare or dereplicate? `Bonus` is no longer an options. You can check dependencies now just by running `dRep check_dependencies`

Best,
Matt
