### ISSUE TITLE
fastANI: FileNotFoundError: [Errno 2] No such file or directory: 'output_directory/data/fastANI_files/fastANI_out_lxsgadvcwm'

### ISSUE THREAD

**Issue by allen-zhan340** [MrOlm/drep#153]
when i run ‘"dRep dereplicate output_directory -g bin_dir/*fa", something went wrong like this:
bin_dir: all my genomes are in this directory

![1658111542564](https://user-images.githubusercontent.com/73383699/179437183-deb2dfc7-06f7-4aa7-ae47-45daca3f00f2.jpg)

my dRep version and it's dependencies are showing below:
![1658111926025](https://user-images.githubusercontent.com/73383699/179437711-e5f90567-f2c7-4572-bcae-708c5994c538.jpg)

and i check my fastANI （version--1.33） can run successully Independently.
 
thanks！

**Comment by MrOlm** [comment]
Hi @allen-zhan340 - thank you for the bug report and for figuring out the fix! I'll make sure and fix this during the next dRep update.

Thanks again,
Matt

**Comment by MrOlm** [comment]
I just confirmed that fastANI version 1.32 and 1.33 have the option --minFraction. I'm not not sure why this fixed your problem, but I'm glad it did!
