### ISSUE TITLE
Where to check the quality of the dereplicated MAGs when having genome_chunk_out dirs?

### ISSUE THREAD

**Issue by B-1991-ing** [MrOlm/drep#155]
Dear drep support team,

I ran the drep command line to remove the duplicated MAGs in my MAG set. I got 138 MAGs in the **dereplicated_genomes** folder. I don't know where to check the MAG quality of these 138 MAGs. Because I have two folders - genome_chunk_0_out and genome_chunk_1_out directories, under the folder of **data/checkM/checkM_outdir**, shown as below. 
<img width="1042" alt="Screenshot 2022-07-28 at 15 02 46" src="https://user-images.githubusercontent.com/54441633/181511676-e192b57f-c83a-4897-a202-271f33c2bed2.png">

In the genome_chunk_0_out/results.tsv, there are 2001 lines.

In the genome_chunk_1_out/results.tsv, there are 93 lines.

But, I have 138 MAGs in my dereplicated_genomes directory, so which result.csv is for me to check the 138 MAGs' quality?

Best,

Bing

**Comment by MrOlm** [comment]
Hi Bing,

Check the files in the folder `data_tables`; you shouldn't need to look in the `data` folder. See the following link for more information

https://drep.readthedocs.io/en/latest/advanced_use.html

**Comment by B-1991-ing** [comment]
Thank you very much for your reply, Matt. 

You can close the issue.

Best,

Bing
