### ISSUE TITLE
dRep facing error while installing by conda

### ISSUE THREAD

**Issue by poddarharsh15** [MrOlm/drep#156]
conda config --add channels bioconda; conda install drep

Warning: 'bioconda' already in 'channels' list, moving to the top
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
 Collecting package metadata (repodata.json): done
Solving environment: | 
 The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

Could you please suggest some ideas many thanks

**Comment by MrOlm** [comment]
Try making a new environment, e.g. with the command:

`conda create -n drep drep`

**Comment by poddarharsh15** [comment]
thanks for answering me I have executed the command, and installation finished with this -
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'defaults::scikit-learn-1.0.2-py37h51133e4_1'.
Rolling back transaction: done
 
I am getting this error now :
(drep)alifchebbi@amberjack:/tmp$ dRep check_dependencies
Command 'dRep' not found, did you mean:
Really appreciate your help.

**Comment by MrOlm** [comment]
Hello- 

Unfortunately this seems to be an error with `scikit-learn`, which I don't know how to troubleshoot.

You could try installing with pip instead? E.g.:

`pip install drep`

-Matt

**Comment by poddarharsh15** [comment]
Good evening again I have tried with pip before but when I try to execute the command I get an error of drep command not
found.

**Comment by MrOlm** [comment]
Sorry @poddarharsh15 , but I don't think I can help troubleshoot this issue any further. Something about your systems specific python setup is wrong

Best,
Matt
