### ISSUE TITLE
dRep does not generate secondary algorithm files

### ISSUE THREAD

**Issue by zjardyn** [MrOlm/drep#158]
I am running dRep v2.6.2 on 288 single amplified genomes (SAGs) and it creates a Secondary_clustering_dendrograms.pdf and Secondary_clustering_MDS.pdf figures that are blank. I had previously ran dRep on these SAGs and it had generated these figures but I reassembled them with different parameters using SPAdes and now it does not. I am wondering if the reassembled SAGs do not pass gANI criteria?

**Comment by MrOlm** [comment]
Hello,

A couple of things:

1) That's a quite old version of dRep; updating to the latest version `pip install drep --update` may fix your problem

2) If it is filtering that's a problem, you can update the filtering chritera to tell

3) In the `data_tables` folder you'll find a file called Bdb.csv that lists all the genomes that passed filtering, and a file called Ndb.csv that lists all the comparison ANI values

Best,
Matt
