### ISSUE TITLE
CheckM results in drep conflicted wtih metaWRAP::Bin_refinement module CheckM results

### ISSUE THREAD

**Issue by WoCer2019** [MrOlm/drep#159]
Hi, thanks for your tools!

I am running dRep v3.2.2 for dereplicating the genome, the input MAG was refined using the metaWRAP::Bin_refinement module (parameter -c 50 -x 10, that is to say, completion>50% and contamination<10% bins were retained), but the dRep result showed that the completion of 23 MAGs less than 50%, these MAGs were discarded.  Why does this happen?

Thanks!

**Comment by MrOlm** [comment]
I'm not positive since I'm not too familir with metaWRAP, but my guess is that it's due to a difference between using `lineage-specific workflow` and `taxonomic-specific workflow` (https://github.com/Ecogenomics/CheckM/wiki/Workflows)

-MO

**Comment by WoCer2019** [comment]
> 

Thanks for your timely reply!

I checked the log file of metaWRAP and dRep. In metaWRAP, CheckM was run with the following steps: (1) [CheckM - tree] Placing bins in reference genome tree. (2) [CheckM - lineage_set] Inferring lineage-specific marker sets. (3) [CheckM - analyze] Identifying marker genes in bins. (4) [CheckM - qa] Tabulating genome statistics. In dRep, CheckM was run with the command: checkm lineage_wf. According to the workflow introduction of CheckM ([https://github.com/Ecogenomics/CheckM/wiki/Workflows]), CheckM was run using lineage-specific workflow in metaWRAP and dRep. So, I think their results should be the same. What do you think of it?

Looking forward to your reply! Thanks!
