### ISSUE TITLE
Pass options to checkM?

### ISSUE THREAD

**Issue by lhor** [MrOlm/drep#16]
(Suggestion) I'm wondering if it would be possible to implement options for checkM as `-reduced_tree` during `lineage_wf` so it could run in machines with <40 Gb.
Thanks

**Comment by MrOlm** [comment]
Hello,

Thank you for the suggestion. As there are many options that one could potentially want to pass in to checkM, the current way that I'm handling this is by giving the user the option to run checkM on their own (with whatever options they want, including `-reduced_tree`), and then pass the results of that run on to dRep.

This is currently possible using the `--Chdb` option. To generate the table needed for this input, the two checkM commands are:

```
checkm taxonomy_wf domain Bacteria ${prodigal_output} checkM_outdir/ -f checkM_outdir/results.tsv --tab_table -g -x faa

checkm qa checkM_outdir/Bacteria.ms checkM_outdir/ -f checkM_outdir/Chdb.tsv --tab_table -o 2
```

Of course, if you're confident that you're genome are complete, you could also skip checkM entirely.

Let me know if you have any trouble!
-Matt

**Comment by lhor** [comment]
Thanks for your answer. I actually tried that before but I got an error. I'm going to open a new issue as it might help others.
