### ISSUE TITLE
Drep doesn't detect mash even if it's installed. 

### ISSUE THREAD

**Issue by SilasK** [MrOlm/drep#160]
Hello, 
We encountered the following problem. 
https://github.com/metagenome-atlas/atlas/issues/547#issuecomment-1230550503

Drep doesn't detect mash even though it is installed.

**Comment by MrOlm** [comment]
Hello,

dRep detects mash using the Linux ‘which’ command. So it needs to be in the system path and able to called from anywhere.

Best,
Matt

**Comment by SilasK** [comment]
What is strange that Dreo detects the correct path but still mentions there is an error.

**Comment by MrOlm** [comment]
Could it be that mash doesn’t have all the dependencies installed? Does running ‘mash -h’ give an error, for example?
