### ISSUE TITLE
Why the value of # scaffolds, # contigs, and Predicted genes are same?

### ISSUE THREAD

**Issue by B-1991-ing** [MrOlm/drep#163]
Hi Matt,

<img width="621" alt="Screenshot 2022-08-31 at 10 41 13" src="https://user-images.githubusercontent.com/54441633/187636197-8d572182-d75a-4cb8-80ca-e97616e7e012.png">

The column of **# Schaffolds** in my Chdb.csv file and my **Predicted genes** are the same. What went wrong there according to your experience?

Best,

Bing

**Comment by MrOlm** [comment]
Hi Bing,

DRep provides checkM with genes, not scaffolds, so checkM has no way to know the correct number of scaffolds in a genome.

The number of genes is probably correct, number of scaffolds is incorrect 

-Matt

**Comment by B-1991-ing** [comment]
Thanks for your confirmation, Matt.

I self-checked the number of **scaffolds**, **GC**, **predicted genes** using script.
