### ISSUE TITLE
dRep issue with nsimscan dependency for goANI

### ISSUE THREAD

**Issue by aforestsomewhere** [MrOlm/drep#166]
Hi Matthew,

Hope you're keeping well.

I wanted to run dRep with --S_algorithm goANI on my genomes (to be able to use your script dnds_from_drep.py), but have run into an issue with a missing dependency for NSimScan (part of QSimScan) which doesn't seem to be installed on our cluster.

Just wanted to check if there are any options beyond manually installing that (think it's a C++ distribution)  and providing the path for this to dRep manually? Using dRep v/3.2.0 but have the option to rollback to 2.2.3 or 2.6.2 if it would help.

Thanks a million,

Katie

**Comment by MrOlm** [comment]
Hi Katie,

Unfortunately the only real way for this to work will be to install QSimScan / NSimScan. There's no real way to avoid this; rolling back dRep won't help.

Best,
Matt

**Comment by aforestsomewhere** [comment]
Thanks Matt, actually it wasn't too terrible to compile it in my home folder and export the path so that dRep recognised it (in case it helps anyone else).

Anyway it is running away now (touchwood), thanks for your help and all the software tools you've put out over the years!
