### ISSUE TITLE
Versions bumps do not match the git tags used by Github to display Releases

### ISSUE THREAD

**Issue by cpauvert** [MrOlm/drep#173]
Hi,
This is a minor issue but I noticed that the [releases](https://github.com/MrOlm/drep/releases) displayed on your repository (currently 3.0.0) do not match the version bump in the commits [list](https://github.com/MrOlm/drep/commits/master) (currently 3.4.0).
If I remember correctly, Github tracks the tag to display releases, so you could add the tags (even for older commits) and push only the tags to Github (`git push --tags`). You might want to look at the help page of `git tag` (using `git help tag` as there is a nice section on "Backdating Tags").
Best,

**Comment by MrOlm** [comment]
Thanks for the heads up @cpauvert! I will definitely look into this.

Best,
Matt

**Comment by MrOlm** [comment]
Issued a new release
