### ISSUE TITLE
#qurey #fastANI

### ISSUE THREAD

**Issue by Mup12** [MrOlm/drep#175]
I am trying to install fastANI in my ubuntu system, using the code  

  "   $ conda create -n ANI -c conda-forge -c bioconda fastani  " 

But, after the successful installation I am not able to call fastANI or fastANI -help

user:~$ conda activate ANI
(ANI) user:~$ conda list
# packages in environment at /home/miniconda3/envs/ANI:
# Name                     Version               Build                        Channel
libgcc_mutex              0.1                    conda_forge             conda-forge
openmp_mutex          4.5                    2_gnu                        conda-forge
fastani                        1.33                  h0fdf51a_1                bioconda
gsl                              2.7.1                 h6e86dc7_1  
libgcc-ng                   12.2.0                h65d4601_19           conda-forge
libgomp                     12.2.0                h65d4601_19           conda-forge
libstdcxx-ng              12.2.0                 h46fd767_19            conda-forge
libzlib                        1.2.13                 h166bdaf_4              conda-forge
zlib                           1.2.13                  h166bdaf_4              conda-forge

(ANI) user:~$ fastani
fastani: command not found
(ANI) user:~$ fastani -h
fastani: command not found

**Please help me to resolve this issue.**

**Comment by MrOlm** [comment]
Hi @Mup12 -

This is a frustrating issue! But apologies, I will not be able to help troubleshoot `conda` problems like this. I'm not at all a `conda` expert. 

You could always just install fastANI manually, from their website, however? I've done this before and it's not too hard. As long as it's in your system path, it will work with dRep just fine.

Best,
Matt
