### ISSUE TITLE
ValueError: fastANI isn't working- make sure its installed

### ISSUE THREAD

**Issue by B-1991-ing** [MrOlm/drep#178]
Hi Matt,

The strange thing is that **it worked for me before many times** when dereplication. But this time, always show me error --- **ValueError: fastANI isn't working- make sure its installed**.

I checked all dependencies as shown below.
<img width="1338" alt="Screenshot 2022-12-27 at 23 52 58" src="https://user-images.githubusercontent.com/54441633/209733153-0bf0a106-0c56-4227-b971-fbdb1a7ff777.png">

**Shell script**
[genome_drep.txt](https://github.com/MrOlm/drep/files/10311066/genome_drep.txt)

Best,

Bing

**Comment by B-1991-ing** [comment]
**Update**

Hi Matt, 

Worked now.

**# Load all required modules for the job**
module load tools
module load ngs
module load anaconda3/2021.11 #dRep and others modules
module load hmmer/3.3.2 #dRep and semibin
module load prodigal/2.6.3 #dRep and semibin
**module load gcc/5.4.0 #prereq for dashing/0.4.0 #dRep!!!
module load dashing/0.4.0  #dRep!!!**
module load pplacer/1.1.alpha19 #dRep 
module load fastani/1.33 #dRep #CoverM
module load mash/2.3 #gtdbtk,dRep
module load mummer/4.0.0beta2 #dRep
module load anicalculator/1 #dRep
module load centrifuge/1.0.4-beta #dRep

The reason could be I didn't upload the necessary dependencies --- gcc/5.4.0 and dashing/0.4.0.

Best,

Bing

**Comment by MrOlm** [comment]
Hi Bing,

I'm glad you were able to get this all sorted out, and thank you a ton for including your solution here as well! Much appreciated.

Best,
Matt
