### ISSUE TITLE
too many bins?

### ISSUE THREAD

**Issue by lhor** [MrOlm/drep#18]
I ran dRep cluster and I got the following message:

Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 151, in parseArguments
    self.cluster_operation(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 56, in cluster_operation
    drep.d_cluster.d_cluster_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 59, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(Bdb, data_folder, wd=workDirectory, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 138, in cluster_genomes
    Mdb = all_vs_all_MASH(Bdb, data_folder, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_cluster.py", line 612, in all_vs_all_MASH
    dm.run_cmd(cmd, dry, shell=False, logdir=logdir)
  File "/usr/local/lib/python3.6/site-packages/drep/__init__.py", line 62, in run_cmd
    call(cmd,stdout=sto, stderr=ste)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/usr/local/bin/mash'

**Comment by MrOlm** [comment]
Hello,

Can I ask what version of dRep you're running? It should be reported with just `dRep -h`

Thanks,
-Matt

**Comment by lhor** [comment]
I'm running dRep v1.4.3

**Comment by MrOlm** [comment]
This was a problem that I believe I corrected in version 1.3.1 - if you're below that, please try updating and trying again.

**Comment by MrOlm** [comment]
OK I see the problem. It's really an OS problem, but one that I should be able to work around. The issue comes down to the command:

**Comment by MrOlm** [comment]
OK I fixed this issue in the v2 branch.

To install it, run the commands:

```
git clone -b v2 git@github.com:MrOlm/drep.git
cd drep
pip install .
```

If successful you should see the following:

```
$ dRep -h

                ...::: dRep v2.0.0_beta :::...
```

This branch should be pretty stable, but I haven't pushed it to the master yet because I want to fix up the documentation.

Let me know if you run into any other problems!
-Matt

**Comment by MrOlm** [comment]
FYI, version 2.0 has now been pushed to master

**Comment by zhiping393** [comment]
> FYI, version 2.0 has now been pushed to master

Hi ,how can I install version 2. I followed the instructions below, but it was version dRep v1.4.3

$ git clone https://github.com/MrOlm/drep.git
$ cd drep
$ pip install .

The instructions were from: https://drep.readthedocs.io/en/latest/installation.html

thank you.

**Comment by MrOlm** [comment]
Hello,

If you already have `dRep` installed, try the same thing but with the last step being `pip install . --upgrade`

Best,
Matt

**Comment by zhiping393** [comment]
> Hello,
> 
> If you already have `dRep` installed, try the same thing but with the last step being `pip install . --upgrade`
> 
> Best,
> Matt

Matt, thanks for your quick reply. For "dRep dereplicate_wf", how many bins (at most) can version 1 and 2 deal with?  thank you!!

**Comment by zhiping393** [comment]
> Hello,
> 
> If you already have `dRep` installed, try the same thing but with the last step being `pip install . --upgrade`
> 
> Best,
> Matt

Matt, thanks for your quick reply. For "dRep dereplicate_wf", how many bins (at most) can version 1 and 2 deal with? I'm trying to dereplicate about 900,000 assembled contigs. Version 1 will generate this error: bin/dRep: Argument list too long
Could this issue be resolved if I upgrade to version 2? 
thank you!

**Comment by MrOlm** [comment]
Hello,

So there are things that you could do to make dRep probably work with 900,000 contigs, but I wouldn't using dRep for contig-level de-replication. The Mash / nucmer hybrid approach that dRep uses would not work well for contigs, as they often have different sizes which does not work for Mash, and thus would bias the results. Also, because dRep is coded with the use of genomes in mind and not contigs, it would take orders of magnitude more time than should be necessary for contig-level dereplication.

I know there are other tools out there that are purpose-built for contig-level dereplication, and if that's what you want to do, I would highly encourage using those over dRep.

Best,
Matt

**Comment by zhiping393** [comment]
> Hello,
> 
> So there are things that you could do to make dRep probably work with 900,000 contigs, but I wouldn't using dRep for contig-level de-replication. The Mash / nucmer hybrid approach that dRep uses would not work well for contigs, as they often have different sizes which does not work for Mash, and thus would bias the results. Also, because dRep is coded with the use of genomes in mind and not contigs, it would take orders of magnitude more time than should be necessary for contig-level dereplication.
> 
> I know there are other tools out there that are purpose-built for contig-level dereplication, and if that's what you want to do, I would highly encourage using those over dRep.
> 
> Best,
> Matt

Matt, thanks for your honest thoughts. I used to use ClusterGenome for clustering (e.g., 95% id + 80% coverage) to populations, but it took very long time. So I'm considering if dRep will be more quickly (You suggested not). If you know other software which can cluster contigs into populations, please let me know what they are. thank you.
