### ISSUE TITLE
The log file has been stopped without any progress

### ISSUE THREAD

**Issue by Liuyuxinn** [MrOlm/drep#183]
Hello

When I use drep(v2.6.2) to deal with 1400+ eukaryotic genomes, I got 430 primary clusters.
Then I used fastANI to run secondary clustering   .

My code is dRep dereplicate -p 72 /output -g /eukaryotic genomes/*.fna -pa 0.9 -sa 0.999 -nc 0.1 --ignoreGenomeQuality --S_algorithm fastANI --run_tertiary_clustering --clusterAlg single.

This task has been done for more than a month and it is not over yet. I feel it is abnormal, and the log file has been stopped at this stage without any progress(more than 8 days,).

02-02 08:19 DEBUG    running cluster 406
02-02 08:19 DEBUG    /hl/lll/miniconda3/envs/drep/bin/fastANI --ql /hl/output/data/fastANI_files/fastANI_out_esymaqwdfg --matrix -t 72 --minFraction 0 esymaqwdfg
02-02 12:24 DEBUG    running cluster 201
02-02 12:24 DEBUG   /hl/lll/miniconda3/envs/drep/bin/fastANI --ql /hl/output/data/fastANI_files/fastANI_out_vwrkpycoks --matrix -t 72 --minFraction 0 vwrkpycoks
02-02 12:25 DEBUG    running cluster 355
02-02 12:25 DEBUG    /hl/lll/miniconda3/envs/drep/bin/fastANI --ql /hl/output/data/fastANI_files/fastANI_out_fwgcnrzhio --matrix -t 72 --minFraction 0 fwgcnrzhio
02-02 12:53 DEBUG    running cluster 357
02-02 12:53 DEBUG    /hl/lll/miniconda3/envs/drep/bin/fastANI --ql /hl/output/data/fastANI_files/fastANI_out_tlhajflynu --matrix -t 72 --minFraction 0 tlhajflynu
02-02 13:25 DEBUG    running cluster 411
02-02 13:25 DEBUG   /hl/lll/miniconda3/envs/drep/bin/fastANI --ql /hl/output/data/fastANI_files/fastANI_out_wgfnwshbib --matrix -t 72 --minFraction 0 wgfnwshbib
(END)

I'm so confused, is this normal?

Could you help me? thanks a million!

**Comment by MrOlm** [comment]
Hi @Liuyuxinn - 

Yes this is not normal- fastANI has a bug where every once in a while it just crashes and will never finish. Newer versions of dRep are better able to handle this problem. I would recommend upgrading to the lastest version of dRep (v3.4.2).

Best,
Matt
