### ISSUE TITLE
fastANI -h returns non zero exit status

### ISSUE THREAD

**Issue by dxter-zz** [MrOlm/drep#184]
Not sure what I'm doing wrong but I'm getting "ValueError: fastANI isn't working- make sure its installed" even though it's installed in the bin directory under the conda environment I installed dRep in.  I verified that shutil.which(dep) is finding it in d_bonus.find_program by adding the following line in the function:

print("file location {} is {}".format(dep,loc), file=sys.stderr)

"fastaANI -h" has an exit status of 1 so the subprocess.check_output([loc, '-h'],stderr= subprocess.STDOUT) call seems to be failing

**Comment by dxter-zz** [comment]
I installed another version of fastANI and it now seems to be working.  The original fastANI was automatically installed into a newly created conda environment called "drep" via:

conda install -n drep drep

**Comment by MrOlm** [comment]
Thanks for the update - I'll try and look into the conda recipe to see if there's an issue with fastANI
