### ISSUE TITLE
Is it possible to use dRep with checkm2 scores? 

### ISSUE THREAD

**Issue by JSSaini** [MrOlm/drep#185]
Thank you.

**Comment by MrOlm** [comment]
Right now it is possible, but you need to format the results of checkM2 into the specific format required by dRep. You can see here for more information - https://drep.readthedocs.io/en/latest/advanced_use.html#using-external-genome-quality-information

Best,
Matt

**Comment by JSSaini** [comment]
Hi Matt! 
I have prepared the file. Just two quick questions: should the genome names also include an extension (.fa or .fasta)? And do I need to select --ignoreGenomeQuality do prevent running checkm1? Thank you.

**Comment by MrOlm** [comment]
Hi @JSSaini - yes, the genome names in the input sheet do need to have the extensions associated with them. And no- you do not want to include that flag since that will make it ignore the values you gave it. dRep will know not to run checkM1 if you give it genome quality info

-Matt

**Comment by ganiatgithub** [comment]
Hi,

I'm a bit confused with the error message, I parsed `genomeInfo` with quality generated using CheckM2, but it still tried to run checkM. I'm with `dRep v3.4.2 `. Here is my call and error message. It failed since I didn't install checkm1:

```
time dRep dereplicate -g "$merged_dir"/genomes.txt -p 36 -comp 50 -con 10 -sa 0.95 -nc 0.3 --genomeInfo "$checkm2_out_dir"/quality_report.csv "$drep_out_dir"
```

```
cat merged_checkm2_dereplicate.29716824.err
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Loading genomes from a list
29,813 genomes were input to dRep
Calculating genome info of genomes
99.98% of genomes passed length filtering
Running prodigal
Running checkM
Cannot locate the program checkm- make sure its in the system path

real    44m39.423s
user    57m22.355s
sys     5m18.042s

```

Any suggestions? Thanks.
Gaofeng

**Comment by MrOlm** [comment]
Hi @ganiatgithub - can you attach the log file? And can you confirm that your file `"$checkm2_out_dir"/quality_report.csv` has the columns 'completeness', 'contamination', and 'genome'?

If dRep tries to load and validate the genomeInfo file and it doesn't work, it'll try and run checkM. Details on what it doesn't like about the  genomeInfo file can be found in the log file

**Comment by ganiatgithub** [comment]
Many thanks, found issue. Legacy script created '.fna.fa' file names in `quality_report.csv` rather than `fna.gz` as it should be. `logger.log` showing that the three columns are found, but actually the file names are wrong. Running again after this is fixed.

[genomes.txt](https://github.com/MrOlm/drep/files/11680289/genomes.txt)
[logger.log](https://github.com/MrOlm/drep/files/11680292/logger.log)
[quality_report.csv](https://github.com/MrOlm/drep/files/11680293/quality_report.csv)
