### ISSUE TITLE
Can drep be applied to the de-replicate of eukaryotic MAG?

### ISSUE THREAD

**Issue by qkqk-hub** [MrOlm/drep#190]
Hello, can drep be applied to eukaryotic MAG and "de-replicate" the genome set by selecting the best representative genome for each eukaryotic genome set?

**Comment by MrOlm** [comment]
Yes it can, but there are some things to keep in mind (mostly summarized here - https://drep.readthedocs.io/en/latest/choosing_parameters.html#comparing-and-dereplicating-non-bacterial-genomes). The biggest thing is that it's unclear what the best ANI cutoff to use is, and that the standard checkM-based genome quality metrics don't work with Eukaryotes.

Best,
Matt

**Comment by qkqk-hub** [comment]
Thank you for your reply and carefully pointing out the precautions for me. I understand
