### ISSUE TITLE
Remove redundancy from the eukaryotic genomes

### ISSUE THREAD

**Issue by weiguanyue** [MrOlm/drep#195]
I want to remove redundancy from the eukaryotic genomes, Can I skip secondary clustering and only run MASH clustering ?

**Comment by MrOlm** [comment]
Yes- the only issue you may encounter has to do with genome incompleteness. You can find more info on that here - https://drep.readthedocs.io/en/latest/choosing_parameters.html#importance-of-genome-completeness. Another thing you could do is skip the primary clustering and just cluster them all with fastANI, for example

-Matt

**Comment by weiguanyue** [comment]
HI, Matt




Thank you very much for your answer. Here I would like to make further inquiries，

because I now have over 5,000 fungal genomes, and I want to de-redundancy it. firstly I want to de-redundancy it at the strain level,  here's my code :
dRep dereplicate  drep99  -g      *.fna  -p 25  -d  -nc 0.3  -pa 0.9  -sa 0.99   --ignoreGenomeQuality   --multiround_primary_clustering   --skip_plots 
Then,  I want to do a clustering at the species level, the script is   dRep dereplicate  drep99  -g      *.fna  -p 25  -d  -nc 0.3  -pa 0.9  -sa 0.95   --ignoreGenomeQuality   --multiround_primary_clustering   --skip_plots
I would like to ask if this script is OK, the checkm is for prokaryotes, so I skip this step.  At the same time, I would like to ask if there is a faster step to deal with my needs.


Best wishes
Guanyue Wei

**Comment by MrOlm** [comment]
Hi @weiguanyue - those commands look good to me. The only thing to try and speed this up would be to add `--S_algorithm fastANI` . This is by default on newer versions of dRep, but was not the default in previous versions.

Hopefully this shouldn't take too long- it really depends on how big the fungal genomes are.

Best,
Matt

**Comment by MrOlm** [comment]
Hi @weiguanyue - huh, that's a bug I haven't encountered before. It could be a problem with fastANI not being able to handle large genomes? The two things I can think to do are 1) update fastANI and 2) if that doesn't solve it, using another algorithm (like ANImf) instead.

Best,
Matt
