### ISSUE TITLE
Error running dRep on large set of genomes

### ISSUE THREAD

**Issue by MonaLiu421** [MrOlm/drep#196]
Hello, I have been trying to run the software on a large number of genomes (over 400,000) using the --multiround_primary_clustering and --SkipSecondary. However, I encountered the following error message:
![image](https://github.com/MrOlm/drep/assets/45484925/57c3cec0-19de-4f2a-a43d-99aa4d492202)
The version is v3.2.2 and my command was dRep dereplicate /data/15.SGB_bins --genomeInfo /data/reassembled_best_bins.genomeInfo.csv -g /data/15.SGB_bins/reassembled_best_bins.list.txt --debug -p 90 -comp 50 -con 5 -nc 0.25 -pa 0.95 --multiround_primary_clustering --SkipSecondary
this error is related to the size of the unstacked DataFrame, which is too large for the int32 data type.Can you please provide some guidance on how to resolve this error and successfully run dRep on a large number of genomes?
Thank you for your time and assistance.

Best regards,
Mona

**Comment by MrOlm** [comment]
Hi Mona,

This seems to be a problem with specific versions of pandas. Please upgrade pandas to at least version 1.4, or downgrade pandas to version 0.21.

Best,
Matt

**Comment by MonaLiu421** [comment]
Thank you very much for your reply and help. I I will try it and give you feedback.
Additionally, I have another question that I would like to ask. What‘s the differences about the parameter -ms MASH_SKETCH, --MASH_sketch MASH_SKETCH and --primary_chunksize PRIMARY_CHUNKSIZE
Impacts multiround_primary_clustering. If you have more than this many genomes, process them in chunks of this size. (default: 5000).when i run the software using the --multiround_primary_clustering and --SkipSecondary,Is it possible to use only this parameter --primary_chunksize?

Thank you again for your assistance, and I look forward to hearing back from you.

Best regards,
Mona

**Comment by MrOlm** [comment]
Yes- those parameters do different things. --primary_chunksize breaks the genomes into groups for processing, which MASH_SKETCH is a measure of how long / accurate mash should be. Increasing MASH_SKETCH makes the primary comparisons take longer, but they're more accurate.

Best,
Matt
