### ISSUE TITLE
Microbial eukaryotic genome dereplication

### ISSUE THREAD

**Issue by ganiatgithub** [MrOlm/drep#198]
Hi,

I compiled a set of MAGs including bacteria, archaea and microbial eukaryotes. I notices that none of the eukaryotes were output from the dereplicated set. Is this expected?

Here is my logger if it's of any help.
[logger.log](https://github.com/MrOlm/drep/files/11714339/logger.log)

Many thanks.

**Comment by MrOlm** [comment]
Hi @ganiatgithub

Are you using checkM during your dRep run? If so, that would explain it since that tool doesn't work for Eukaryotes.

See here for some more discussion about this- https://drep.readthedocs.io/en/latest/choosing_parameters.html#comparing-and-dereplicating-non-bacterial-genomes

-MO
