### ISSUE TITLE
fastANI FileNotFoundError

### ISSUE THREAD

**Issue by yihualiued** [MrOlm/drep#199]
Hi @MrOlm,
I encountered this problem when running the latest version of dRep, installed from Bioconda.
**Issue:**
As recorded in the log file:
```
[...]
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
Running primary clustering
Running pair-wise MASH clustering
232 primary clusters made
Running secondary clustering
Running 34751 fastANI comparisons- should take ~ 80.2 min
Traceback (most recent call last):
[...]
File "/.../software/miniconda3/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '.../drep/drep/data/fastANI_files/fastANI_out_efmjoeacwz'
```
I looked at the file location, it seems the previous dRep steps generated the file but named it differently: `".../drep/drep/data/fastANI_files/fastANI_out_jylwftperv"`

**version**
* drep 3.4.3  
* python 3.11.4
* conda 23.5.0

**command line**
`dRep dereplicate -comp 90 -con 5 -sa 0.999 -p 16 --S_algorithm fastANI --genomeInfo $GENOMEINFO $OUTDIR` 

Many thanks!
Best,
Yihua

**Comment by MrOlm** [comment]
Hi @yihualiued - this is likely a problem with fastANI. I would recommend 1) updating fastANI, and 2) running dRep again with `-d`, which will create specific log files for each fastANI run to troubleshoot the problem.

Best,
Matt
