### ISSUE TITLE
TypeError: sequence item 3: expected str instance, NoneType found

### ISSUE THREAD

**Issue by palomo11** [MrOlm/drep#20]
Hi,

I'm running dereplication with dRep 2.0 version.

dRep dereplicate -p 28 dereplicate_dir -g genomes_dir/*.fasta --run_tax --genomeInfo genomeinfo.csv

Everything was running fine but it called for an error in the bonus step:

***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
99.08% of genomes passed length filtering
42.52% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
100 primary clusters made
Step 3. Perform secondary clustering
Running 11390 ANImf comparisons- should take ~ 203.4 min
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
***************************************************
    ..:: dRep dereplicate Step 4. Bonus ::..
***************************************************
    
Loading work directory
Running tax
Running Centrifuge
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_workflows.py", line 52, in dereplicate_wrapper
    drep.d_bonus.d_bonus_wrapper(wd, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 26, in d_bonus_wrapper
    run_taxonomy(wd,**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 36, in run_taxonomy
    run_centrifuge(Bdb, prod_dir, cent_dir, wd=wd, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_bonus.py", line 138, in run_centrifuge
    logging.debug(' '.join(cmd))
TypeError: sequence item 3: expected str instance, NoneType found

Any idea about what is producing the problem? 

Thanks in advance.

**Comment by MrOlm** [comment]
Hello,

The main problem here is that you are not specifying an index from centrifuge. This is required for determining taxonomy (see here https://ccb.jhu.edu/software/centrifuge/manual.shtml for instructions on how to make one), and is specified with the `--cent_index` argument.

That said, would you mind sending me your log file? The program *should* have told you that it was crashing because an index was not provided, and I'm curious why it did not.

Thank you,
-Matt

**Comment by palomo11** [comment]
Hi Matt,

Thank you for the answer. I will run it including that argument then.

Sorry I don't have the log file anymore as I deleted the output and run it again without the taxonomy argument. By the way, in this case I got another error in the analyze module (the dereplicated genomes were properly produced):

***************************************************
    ..:: dRep dereplicate Step 6. Analyze ::..
***************************************************
    
making plots 1, 2, 3, 4, 5, 6
Plotting primary dendrogram
Plotting secondary dendrograms
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/matplotlib/axes/_base.py:2961: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=0, right=0.0
  'left=%s, right=%s') % (left, right))
Plotting MDS plot
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/sklearn/manifold/mds.py:129: RuntimeWarning: divide by zero encountered in double_scalars
  old_stress = stress / dis
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/sklearn/manifold/mds.py:124: RuntimeWarning: invalid value encountered in double_scalars
  if(old_stress - stress / dis) < eps:
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/sklearn/manifold/mds.py:129: RuntimeWarning: invalid value encountered in double_scalars
  old_stress = stress / dis
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_analyze.py", line 73, in d_analyze_wrapper
    plot_secondary_mds_from_wd(wd, plot_dir, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_analyze.py", line 270, in plot_secondary_mds_from_wd
    cluster2color = cluster2color)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_analyze.py", line 1426, in _make_mds_plot
    bbox_to_anchor=(1, 0.5), prop = {'size': 10, 'style': 'italic'})
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3744, in legend
    ret = gca().legend(*args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 500, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/matplotlib/legend.py", line 583, in __init__
    for label, handle in zip(labels[:], handles[:]):
TypeError: 'dict_keys' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_workflows.py", line 68, in dereplicate_wrapper
    drep.d_analyze.d_analyze_wrapper(wd, plots = 'a', **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/drep/d_analyze.py", line 75, in d_analyze_wrapper
    logging.debug('Failed to make plot #3: ' + e)
TypeError: Can't convert 'TypeError' object to str implicitly

Another things I have observed is that there are some information missing in the file: Widb.csv

N50,closest_cluster_member,cluster,cluster_members,completeness,completeness_metric,contamination,contamination_metric,furthest_cluster_member,genome,score,size,strain_heterogeneity,tax_confidence,taxonomy
NA,100.00,1_1,11,NA,NA,NA,NA,100.00,Refiner_MB_Con1500_MyCC1750_176.ID.contigs.fasta,84.72651045356443,NA,NA,NA,NA
NA,100.00,2_1,6,NA,NA,NA,NA,100.00,Refiner_MTpB20_MB_Con_145.fasta,70.73501479308172,NA,NA,NA,NA
NA,100.00,3_1,12,NA,NA,NA,NA,100.00,Refiner_MB_Con1500_MyCC1750_30.fasta,70.2760982911671,NA,NA,NA,NA

As mentioned above I am using external genome quality information from CheckM. 
One last thing related to this, when using genomeInformation flag, that file does not contain the strain heterogeneity information, how does it affect the process?

Thank you very much  in advance.

**Comment by MrOlm** [comment]
Hello,

The issue with the plots is something I'm working on, and seems to be a problem with updated matplotlib. The issue has been somewhat addressed in the most recent dRep update (version 2.0.2), which makes it crash more gracefully and continue to make all the plots that it can.

Thank you for pointing out the issue with Widb.csv- I wasn't aware of that. I will fix it when I get a chance, but in the meantime all of the missing information should be in the file `genomeInformation.csv` in the same folder

Finally, it's no problem at all to not include strain heterogeneity information - the program will just ignore strain heterogeneity when computing genome scores.

Best,
-Matt

**Comment by palomo11** [comment]
Hi Matt,

OK, thanks for the info.

In relation to the strain heterogeneity information, If I have that info from CheckM, is there any way to include it with the genomeInformation flag? Because in the example you provide, it is not appeared:

Using external genome quality information:

genome,completeness,contamination
Enterococcus_casseliflavus_EC20.fasta,98.28,0.0

It would be good if there is the opportunity to add another column with the strain heterogeneity information

**Comment by MrOlm** [comment]
Hello,

I didn't mention it in the documentation, but if you add another column: `strain_heterogeneity`, the program will use the information :) 

I'll update the documentation to reflect this as well.

Best,
-Matt
