### ISSUE TITLE
MASH clustering error during the execution of dRep 

### ISSUE THREAD

**Issue by MrAli1582** [MrOlm/drep#200]
Hello @MrOlm, I hope this reaches you well.

So I have been running dRep for around a month now, and everything was working perfectly fine.

Except that 2 weeks ago, I started getting this weird issue that I couldn't fix myself.

It happens on the 2nd step of dRep, the MASH clustering doesn't seem to work at all! 

![drep_1](https://github.com/MrOlm/drep/assets/139212688/4615bd7a-8309-4161-9114-e62e955023ae)
![drep_2](https://github.com/MrOlm/drep/assets/139212688/a28f3fed-0e46-4cbf-afd1-7f81f01ea92b)

While before, I launched the same tool several times on different genomes of different species with no issues.

Regarding the versions im using, Python is 3.8 and drep is 3.2.2

Regarding the dependencies, there should be no problem as the tool worked completely fine before.

![drep_4](https://github.com/MrOlm/drep/assets/139212688/c3cb9818-d7fa-42cb-97ef-ff407d535344)

Here is also the log of execution of the tool dRep.

![drep_3](https://github.com/MrOlm/drep/assets/139212688/7a86b528-bbe5-4d58-ac5f-7fc7be55b5ab)

I made also sure to check that this problem wasn't due to any of the selected parameters.

Do you have any idea on what could be the issue here?

Best,

Ali

**Comment by MrOlm** [comment]
Hi Ali,

This is a bug caused by upgrading pandas without updating dRep. If you updated dRep to the latest version (v3.4.3) (for example with the command `pip install dRep --upgrade`) this bug should go away.

Best,
Matt

**Comment by MrAli1582** [comment]
Hello @MrOlm,

Thanks for your time and your suggestion! It actually solved the problem I was facing. 

Best,
