### ISSUE TITLE
 ValueError: fastANI isn't working-

### ISSUE THREAD

**Issue by marina-vn** [MrOlm/drep#203]
Hi,

I'm trying to run dRep (v3.4.3) dereplicate sith a set of almost 2.000.000 genomes. I first had problems with the size of the input but in other issue I saw the recommendation of running the program with the option "--ignoreGenomeQuality" and it solved the innitial problem.

Now I'm having issues with secondary clustering, as I get an error of the fastANI. I have reinstalled fastANI (v 2.31) and make sure that python version was over 3.9 as it seems that lower versions cause issues (Python 3.9.17), so I'm not sure how to solve this problem.

The command that I'm using and the error is displayed below and I'm attaching the log file:

_____________________________________________________________________________________________________________________________________________

 dRep dereplicate derep95L -pa 0.95 -g lista_ls_mod --ignoreGenomeQuality -d
********************************
[logger.log](https://github.com/MrOlm/drep/files/12214459/logger.log)
*******************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Loading genomes from a list
1,648,290 genomes were input to dRep
Calculating genome info of genomes
0.10% of genomes passed length filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
1375 primary clusters made
Running secondary clustering
Running 2129 fastANI comparisons- should take ~ 382.1 min
Traceback (most recent call last):
  File "/global/homes/m/mvila/.local/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_cluster/controller.py", line 35, in main
    self.run_secondary_clustering()
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_cluster/controller.py", line 140, in run_secondary_clustering
    Ndb, Cdb, c2ret = drep.d_cluster.compare_utils.secondary_clustering(self.Bdb, self.MCdb, algorithm, self.wd.get_dir('data'), wd=self.wd, **self.kwargs)
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_cluster/compare_utils.py", line 298, in secondary_clustering
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_cluster/compare_utils.py", line 368, in compare_genomes
    df = drep.d_cluster.external.run_pairwise_fastANI(genome_list, working_data_folder, **kwargs)
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/d_cluster/external.py", line 93, in run_pairwise_fastANI
    exe_loc = drep.get_exe('fastANI')
  File "/global/homes/m/mvila/.local/lib/python3.8/site-packages/drep/__init__.py", line 100, in get_exe
    raise ValueError("{0} isn't working- make sure its installed".format(name))
ValueError: fastANI isn't working- make sure its installed
_____________________________________________________________________________________________________________________________________________
[logger.log](https://github.com/MrOlm/drep/files/12214469/logger.log)

Thanks!

**Comment by MrOlm** [comment]
Hi @marina-vn - it seems that fastANI is not properly installed on your system. Before running again, you can make sure it's installed in a way that dRep knows how to access by running

`dRep check_dependencies`

Best,
Matt

**Comment by liangyong1991** [comment]
Hi @MrOlm, I got the same error message and get the following information after running `dRep check_dependencies`:
```
(base) root@43e9bfee0ad0:/tmp# dRep check_dependencies
mash.................................... all good        (location = /opt/conda/envs/drep/bin/mash)
nucmer.................................. all good        (location = /opt/conda/envs/drep/bin/nucmer)
checkm.................................. all good        (location = /opt/conda/envs/checkm/bin/checkm)
ANIcalculator........................... !!! ERROR !!!   (location = None)
prodigal................................ all good        (location = /opt/conda/envs/checkm/bin/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ !!! ERROR !!!   (location = None)
fastANI................................. !!! ERROR !!!   (location = /opt/conda/envs/drep/bin/fastANI)
```

and I can get the help information of `fastANI` by using `fastANI -h`：
```{shel}
(base) root@43e9bfee0ad0:/tmp# fastANI -h
-----------------
fastANI is a fast alignment-free implementation for computing whole-genome
Average Nucleotide Identity (ANI) between genomes
-----------------
Example usage:
$ fastANI -q genome1.fa -r genome2.fa -o output.txt
$ fastANI -q genome1.fa --rl genome_list.txt -o output.txt

Available options
-----------------
-h, --help
    Print this help page

-r <value>, --ref <value>
    reference genome (fasta/fastq)[.gz]

--refList <value>, --rl <value>
    a file containing list of reference genome files, one genome per line

-q <value>, --query <value>
    query genome (fasta/fastq)[.gz]

--ql <value>, --queryList <value>
    a file containing list of query genome files, one genome per line

-k <value>, --kmer <value>
    kmer size <= 16 [default : 16]

-t <value>, --threads <value>
    thread count for parallel execution [default : 1]

--fragLen <value>
    fragment length [default : 3,000]

--minFrag <value>
    minimum matched fragments for trusting ANI [default : 50]

--visualize
    output mappings for visualization, can be enabled for single genome to
    single genome comparison only [disabled by default]

--matrix
    also output ANI values as lower triangular matrix (format inspired from
    phylip). If enabled, you should expect an output file with .matrix
    extension [disabled by default]

-o <value>, --output <value> [required]
    output file name
```

Is there any other things to check the installation of `fastANI`?

**Comment by marina-vn** [comment]
Hi @MrOlm,

When I check the dependencies everything is installed but no "all good", how can I solve this?


*******************
 dRep check_dependencies
mash.................................... !!! ERROR !!!   (location = /global/homes/m/mvila/miniconda3/envs/inS/bin/mash)
nucmer.................................. !!! ERROR !!!   (location = /global/homes/m/mvila/miniconda3/envs/inS/bin/nucmer)
checkm.................................. !!! ERROR !!!   (location = None)
ANIcalculator........................... !!! ERROR !!!   (location = None)
prodigal................................ !!! ERROR !!!   (location = /global/homes/m/mvila/miniconda3/envs/inS/bin/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ !!! ERROR !!!   (location = None)
fastANI................................. !!! ERROR !!!   (location = /global/homes/m/mvila/miniconda3/envs/inS/bin/fastANI)
*******************

**Comment by liangyong1991** [comment]
Hi @marina-vn, it may be you do not have the correct version of these tools. In my case, it works after updating the `fastANI` to v1.3.4(from v1.1.0).

**Comment by tfaitova1** [comment]
Hi all
I was having the exact same issue and solved it with help from our server support team.
They advised to install fastANI from source, and outside miniconda environment.

I was folowing these commands:

module purge
module load pbs gsl/2.7.1
git clone -b v1.34 https://github.com/ParBLiSS/FastANI.git
mkdir fastani
cd FastANI
./bootstrap.sh
./configure --prefix=//fastani
make
make install

Then export "/fastani/bin" under your $PATH using:
export PATH=/fastani/bin:$PATH

and then run dRep check_dependencies again, it should now recognize the fastANI and say all good! :)

Hope it helps someone!

Cheers,
Tereza

**Comment by MrOlm** [comment]
Thanks, @tfaitova1 !
