### ISSUE TITLE
--genomeInfo

### ISSUE THREAD

**Issue by Sumsarium** [MrOlm/drep#206]
I have recently switched to using CheckM2 and would like to provide the genomeinfo file to dRep using the `--genomeinfo` flag. A relatively straightforward task. I have, however, noticed that the help file states that it needs the "basename" of the genome/MAG while the readthedocs states that it needs the "filename". dRep requires that latter. It would be more convenient to provide the basename as this is already embedded in the first column of the CheckM2 quality_report. In general, it would be nice if dRep was directly compatible with the CheckM2 output file (column names etc). But basenames instead filenames...

**dRep dereplicate -h:**
```
--genomeInfo GENOMEINFO
                        location of .csv file containing quality information on the genomes. Must contain: ["genome"(basename of
                        .fasta file of that genome), "completeness"(0-100 value for completeness of the genome),
                        "contamination"(0-100 value of the contamination of the genome)] (default: None)
```

**ReadtheDocs:**
```
The genomeInformation file must be in .csv format and have the columns “genome”, “completeness”, and “contamination”. Columns “completeness” and “contamination” should be 0-100, and “genome” is the filename of the genome.
```

**Comment by MrOlm** [comment]
Hi @Sumsarium -

Apologies for the confusion; it should in fact be the basename, not the filename. I'll update the docs in the next update.

-Matt

**Comment by Sumsarium** [comment]
Hi @MrOlm 

Just to clarify further. dRep looks for the "filename" in the genomeInfo file (ValueError: MAG1**.fasta** missing from GenomeInfo), i.e. it is not only a documentation issue:

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
2,307 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
Traceback (most recent call last):
  File "/opt/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_filter.py", line 147, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/opt/miniconda3/envs/drep/lib/python3.7/site-packages/drep/d_filter.py", line 221, in _validate_genomeInfo
    raise ValueError("{0} missing from GenomeInfo".format(genome))
ValueError: MAG1.fasta missing from GenomeInfo
```

CheckM and CheckM2 outputs basenames in the "genome" column (and capital letters for **C**ompletion and **C**ontamination).

**Comment by Sumsarium** [comment]
ahh yes. Sorry for the confusion/brain fart.

Hope you are able to standardize the CheckM input in the next update. Thanks for a great tool.
