### ISSUE TITLE
How do Ns in scaffolds affect clustering? 

### ISSUE THREAD

**Issue by krausfeldtle** [MrOlm/drep#207]
Hello! I was hoping to get some insight on how the presence of Ns in scaffolds are handled in calculating ANI and resulting clusters in drep? I get two very different results when using contigs (no Ns) versus scaffolds (Ns), which makes me think the Ns are influencing the final results. Thanks very much!

**Comment by MrOlm** [comment]
Hi @krausfeldtle -

Nice hearing from you and great question, but I'm not sure I know the answer. The handling of Ns is done by the secondary_algorithm; dRep just uses the resulting ANI values. Are you using fastANI? If so, you'll have to look into what that algorithm does with Ns.

Best,
Matt
