### ISSUE TITLE
Cannot locate the program checkm- 

### ISSUE THREAD

**Issue by sakuragi0109** [MrOlm/drep#208]
Hi everyone, 
I'm having problem of running drep for my binnings. It keeps giving me the error "Cannot locate the program checkm- make sure its in the system path". I thought checkm is integrate in drep already. But why it keep giving me this error. Can anyone help me with this? Thank you so much!!!

**Comment by MrOlm** [comment]
Hi @sakuragi0109 ,

It's difficult to troubleshoot system path stuff remotely, as it's very system-dependent, but I just wanted to point out that you could always work around this issue by just runing checkM outside of dRep and then provide the results to dRep - https://drep.readthedocs.io/en/latest/advanced_use.html#using-external-genome-quality-information

-Matt

**Comment by sakuragi0109** [comment]
Hi Mr. Olm, 

Thank you so much for your answer. By the way, as checkM has been updated to checkM2, do you think I can use checkM2 and provide its result to drep? Thank you so much for your help!

**Comment by MrOlm** [comment]
Yes- using checkM2 in this way shouldn't be a problem at all

-Matt
