### ISSUE TITLE
The max process of the dRep

### ISSUE THREAD

**Issue by MingyueCheng** [MrOlm/drep#213]
Dear author,

**Commend:** 
`dRep compare -p 128 -g input_MAG_list --S_algorithm fastANI -pa 0.95 -sa 0.95 -nc 0.3 --multiround_primary_clustering out`

CPU usage: resources_used.cpupercent = 2862 (28 cpus)

My server has 256 CPUs and 1.5T memory.

I wonder whether the set of processes has a cap, and if the value is set greater than the threshold, it would lead to a slower speed.

Thanks!

**Comment by MingyueCheng** [comment]
Moreover, what is the difference between dRep compare and dRep dereplicate?
They have similar parameters and output.

My task is to compare the dereplicated query mags to the other deprelicated reference mags. 
And I do not need to compare themselves with each other in the same set.

But the dRep comp will force to conduct a pair-comparison, and even between it to itself, which really cause a redundant and useless cost of resources.

I hope the author can help! Many thanks to you.

**Comment by MrOlm** [comment]
Hi @MingyueCheng,

Different steps that dRep performs have different multiprocessing efficiency. Some steps can only ever use 1 CPU, some steps just pass the number of CPUs to other programs (checkM, Mash, etc.) so it depends on what those programs can do, and other steps have overhead associated with them such that there are diminishing returns. There is no cap on the number of CPUs.

The difference between compare and dereplicate is that in dereplicate, a representative genome is chosen for each secondary cluster.

I understand what you're saying about dereplicating 2 databases forcing self-comparisons, but that's just the way it is at the moment. Someday I hope to have time to add additional code to better handle this use-case.

Best,
Matt

**Comment by MingyueCheng** [comment]
Dear Matt,

Many thanks for your help.

In the past, when comparing 20,000~30,000 MAGs, I just used the default parameters: 
`dRep compare -p 48 -g genome_list -sa 0.95 -nc 0.3 derep_comp_out`
And it would take around 1 day to finish. And the CPU resources arrived at 4800

Now, due to that I want to compare my ~10,000 MAGs to the ~80,000 MAGs in the GTDB, I have carefully read the parameters of the dRep, and investigated the parameters used in the other published paper as well.

Finally, I chose this:
`dRep compare -p 64 -g input_MAG_list --S_algorithm fastANI -pa 0.95 -sa 0.95 -nc 0.3 --multiround_primary_clustering out`

Owing to that all of the genomes were supposed to be previously dereplicated at 95% similarity, I set the pa at 0.95.
Notably, the CPU resources of this command were about 2000~3000.

As for the other parameters, I have no idea...

What do you think about my command? Are there any improvements to this for dealing with huge data sets? Thanks a lot.

Best regards,
Moon

**Comment by MrOlm** [comment]
Hi Moon,

Your command looks good. You could consider adding `--primary_chunksize 20000` if it's the last primary cluster that's taking a long time, and I'd add the `-d` parameter so that it saves intermediate output in case it crashes. The problem with running lots of genomes tends to be the last step of primary clustering, during which only 1 CPU is used and it uses a lot of RAM.

I've run it on 300,000 genomes with similar parameters and had it work, so you should be able to get ~100,000 without too much trouble. 

The most CPUs I give it is ~20, because (as you've seen) after that there's diminishing returns. There's no harm in giving it more than 20 CPUs, but it just doesn't speed it up too much.

It's been a while since I've run than many genomes, but I remember it taking a week or so. If your program is crashing / stalling, feel free to post the log and I can let you know the likely problem.

Good luck,
Matt

**Comment by MingyueCheng** [comment]
Dear Matt,

Thanks a lot!

I have improved the commend as suggested by you:

`dRep compare -p 48 -g MAG_list --S_algorithm fastANI -pa 0.95 -sa 0.95 -nc 0.3 --multiround_primary_clustering --primary_chunksize 20000 -d comp_out`

I have some questions about the `-d` :
If the program is crashed, could you just re-run the commend and will the program continue to run from the broken step?

----------
And I found when using the former commend: 
`dRep compare -p 64 -g MAG_list --S_algorithm fastANI -pa 0.95 -sa 0.95 -nc 0.3 --multiround_primary_clustering comp_out`

The program just caught in an infinite loop!
<img width="821" alt="image" src="https://github.com/MrOlm/drep/assets/34465704/18aa37ad-8ece-4fbd-b7a2-bef5442a756e">

It just repeated the "running primary clustering" over and over again. 
[logger.log](https://github.com/MrOlm/drep/files/13495943/logger.log)

Now I'm trying to use the new commend:
`dRep compare -p 48 -g MAG_list --S_algorithm fastANI -pa 0.95 -sa 0.95 -nc 0.3 --multiround_primary_clustering --primary_chunksize 20000 -d comp_out`

I will give you new log tomorrow! By the way, your dRep really helps a lot to us in microbiome field! Thanks.

Best regards,

Moon

**Comment by MrOlm** [comment]
Hi Moon,

Thanks for the kind words. In regards to your question about `-d`, yes. There are certain checkpoints during which dRep writes some output files when `-d` is enabled, and then if you run the program agian on the same output folder again with `-d` enabled, it will resume from the last checkpoint. This can be a bit buggy though, just FYI.

Interesting about the loop. The log file you sent looks different from the log file you have a screenshot of, but it's all good.

Fingers crossed that your current command works for you!

Matt
