### ISSUE TITLE
Inquiry on Optimal Workflow for Metagenomic Binning and Dereplication

### ISSUE THREAD

**Issue by rzhan186** [MrOlm/drep#217]
Hello Dr. Olm,

Sorry for posting two questions in a row ... This is not a technical issue about dRep, but more to seeking guidance on the optimal workflow to achieve accurate and comprehensive results.

To provide some context, I have utilized four different binning tools to generate bins from each metagenomic assembly, which I obtained through an individual assembly approach. My ultimate objective is to derive a de-replicated set of bins against which I can map reads from each sample. This mapping will help determine the abundance of each bin across all metagenomic samples (using tools like CoverM).

In this process, I am contemplating the use of DasTool in conjunction with dRep. Given my goal, would you recommend using DasTool prior to dRep, or should the order be reversed? Additionally, I have observed that DasTool tends to eliminate a significant number of bins. Is it feasible and advisable to bypass DasTool altogether in this workflow, focusing solely on dRep for dereplication?

Thanks for your insight!

Rui

**Comment by MrOlm** [comment]
Hi Rui,

If you running multiple binning algorithms on the same assembly, you'll probably want to run DasTool before dRep. If you run dRep first (or skip DasTool), there's a very real possibility that you'll end up with the same scaffold in multiple different bins, which will really mess with things going forward.

Hope this helps,
Matt
