### ISSUE TITLE
Halt: the pair-wise MASH clustering step

### ISSUE THREAD

**Issue by RChGO** [MrOlm/drep#221]
Hi,

When running the pair-wise MASH clustering step, I consistently encounter pauses. It often takes repeating the process a dozen or even more times for it to run successfully. What might be the cause of this issue?

Below are the results I obtained. MASH is functioning; however, it consistently pauses when processing specific genomes.

dRep dereplicate 03.drep2 -g 00.data/genomes/*fa -p 50 -pa 0.9 -sa 0.95 -nc 0.3 --S_algorithm fastANI --ignoreGenomeQuality

    ..:: dRep dereplicate Step 1. Filter ::..

Will filter the genome list
495 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering

    ..:: dRep dereplicate Step 2. Cluster ::..
    
Running primary clustering
Running pair-wise MASH clustering

**Comment by MrOlm** [comment]
Hi @RChGO ,

Interesting- I haven't encountered this before. One thing you could try would be to run dRep with `-d`, which will great lots of log files in the log folder. This could be helpful in figuring out why mash is failing on some of your input genomes.

Best,
Matt

**Comment by Wanli-HE** [comment]
i also meet same issue, and have no idea about, have you solved that

**Comment by RChGO** [comment]
> hat might be the cause of this issue?

Currently, I don't have an effective solution either. The mash step is very quick, so when calculating the mash distance between any two genomes takes longer than a minute, it often suggests a indefinite hang-up. The most effective strategy would be to terminate all original commands and remove all related files. Success is often reached after multiple attempts. Once the program indicates it has progressed to the fastANI processing phase, you can be confident that the operation has succeeded. As mentioned in my previous command, if 10 minutes pass without progressing to the fastANI processing phase, I would opt to restart the process.

**Comment by MrOlm** [comment]
I really have no idea why this happens, and I'm not sure how to fix it because it seems to be a problem with Mash. If you don't have too many genomes you could add "--SkipMash" to avoid the primary clustering entirely, or you could try updating Mash and see if that helps.

-Matt

**Comment by durubing-jn** [comment]
Probably because the mash version is too high, I lower the mash version to 1.1, and it is working!
