### ISSUE TITLE
extra_weight_table flag

### ISSUE THREAD

**Issue by reenadebray** [MrOlm/drep#222]
I would like to merge custom genomes with an existing genome database while prioritizing the custom genomes. I am aware that dRep can handle this using the extra_weight_table flag, but I can't find any information about how to choose the weights in the user-provided table. For example, should custom genomes be weighted at 1 and others downweighted to <1? What is an example of a weighting scheme that would slightly prioritize custom genomes versus one that would strongly prioritize custom genomes even when they are lower quality? Is it possible to provide example input that I can work from? Thank you!

**Comment by MrOlm** [comment]
Hi @reenadebray - 

You can look at the scoring criteria, but essentially a genome with 100% completeness and no contamination has a score of ~100.  If you want to always pick a custom MAG when available, assigning an extra weight of 100 to each custom MAG will do this. If you want to just give a slight preference, you can do something like 5. In my work I usually choose an extra weight of 20, which makes you pick custom genomes most of the time, unless the reference genome is way better.

I would send you an example file if I had one on-hand, but I don't. They're super simple though- something like:

```
genome1.fasta	20
genome2.fasta	15
genome3_with_long_name.fasta	25
```

Just make sure there are no headers in the file and that a tab is what separates genomes from scores.

Best,
Matt

**Comment by reenadebray** [comment]
Hi Matt, thanks for this example and timely answer. Can you please clarify what the actual code should look like to add this flag? I have seen --extra_weight_table, --load_extra_weight_table, and --extra_W all mentioned in documentation, but none of these options are in the list of parameters when I run dRep dereplicate -h, and they all return an "unrecognized argument" error when I try them.

**Comment by MrOlm** [comment]
Hello,

`-extraW` and  `--extra_weight_table` will both work. Make sure you've upgraded to the latest version of dRep; this is a relatively new feature.

Best,
Matt
