### ISSUE TITLE
Is there any plan to add skani as ANI calculation method?

### ISSUE THREAD

**Issue by ilnamkang** [MrOlm/drep#224]
Hi,

I'm just curious whether there is any plan to add skani as ANI calculation method of dRep?

https://doi.org/10.1038/s41592-023-02018-3
https://github.com/bluenote-1577/skani

Thanks.

**Comment by MrOlm** [comment]
Hi @ilnamkang -

This is something that I would love to do if / when I get the time, but there aren't any immediate plans for its implementation. Thank you for the suggestion, though.

Matt

**Comment by MrOlm** [comment]
Just completed in version 3.5.0
