### ISSUE TITLE
drep stoped during clustering

### ISSUE THREAD

**Issue by Wanli-HE** [MrOlm/drep#225]
Hi!

i used drep recently, and i had met some issues.

the issue is:
<img width="1054" alt="image" src="https://github.com/MrOlm/drep/assets/58076352/32ecbc8d-bad2-4bd5-bcb3-6cb9aae2cc92">

the commond is: "dRep dereplicate vamb_drep_res -p 40 -pa 0.9 -sa 0.95 -nc 0.3 -cm larger --S_algorithm fastANI -g vamb_res_fa_file/*
"
version: lastest

the workflow works:
"""There are the columns: ['genome', 'completeness', 'contamination', 'strain_heterogeneity']
Filtering genomes
1.01% of genomes passed checkM filtering
Storing resulting files
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************

Running primary clustering
Running pair-wise MASH clustering
Clustering MASH database
"""

**Comment by MrOlm** [comment]
Hello,

I believe you're using an older version of dRep that has an incompatibility with newer versions of pandas; please upgrade dRep to the newest version and this error will go away.

Best,
Matt

**Comment by Wanli-HE** [comment]
> Hello,
> 
> I believe you're using an older version of dRep that has an incompatibility with newer versions of pandas; please upgrade dRep to the newest version and this error will go away.
> 
> Best, Matt



> Hello,
> 
> I believe you're using an older version of dRep that has an incompatibility with newer versions of pandas; please upgrade dRep to the newest version and this error will go away.
> 
> Best, Matt

Hi Matt!

thanks, it`s works, 

another question, i can i get the information about clusering of every bins, it seems like only get represent bins of each cluster. for instance, bins1, bin2 belong to which cluster.

best,
wanli

**Comment by MrOlm** [comment]
Hello,

That information is located in the file `Cdb.csv` in the `data_tables` output folder.

Best,
Matt

**Comment by Wanli-HE** [comment]
> Hello,
> 
> That information is located in the file `Cdb.csv` in the `data_tables` output folder.
> 
> Best, Matt

hI AGAIN!

I checked that file, one thing i am not sure, i have over 3000 bins, but half of that was clustered into a group called: root (UID1),
![image](https://github.com/MrOlm/drep/assets/58076352/a2a475fc-2917-4114-96a6-6e7269368029),

is that normal?
and all the paremater i used are defeault.

best,
wanli

**Comment by Wanli-HE** [comment]
> I’ve never seen that before. Could you let me know the parameters you ran dRep with and show me the top of that file? (Be nice to know what the headers are)

Hi!
here is the commond line: 
dRep dereplicate vamb_drep_res -p 40 -pa 0.9 -sa 0.95 -nc 0.3 -cm larger --S_algorithm fastANI -g vamb_res_fa_file/*
[Chdb.csv](https://github.com/MrOlm/drep/files/13998827/Chdb.csv)
[Uploading Chdb (2).csv…]()

and here is the results!

**Comment by MrOlm** [comment]
Ah I see- you're looking at `Chdb.csv`, which contains taxonomy information. The clustering information is in the file `Cdb.csv`

**Comment by Wanli-HE** [comment]
> Ah I see- you're looking at `Chdb.csv`, which contains taxonomy information. The clustering information is in the file `Cdb.csv`

Hi!
that will more not  make sense, there only 35 represents genome, with default parameter, but gtdbtk have over 400 specise.

besides, i want to know the information of which bin belong to which cluster, of all bins. do drep really have the summary files?

best,
wanli

**Comment by Wanli-HE** [comment]
> > Ah I see- you're looking at `Chdb.csv`, which contains taxonomy information. The clustering information is in the file `Cdb.csv`
> 
> Hi! that will more not make sense, there only 35 represents genome, with default parameter, but gtdbtk have over 400 specise.
> 
> besides, i want to know the information of which bin belong to which cluster, of all bins. do drep really have the summary files?
> 
> best, wanli

here is another i tried, using ANI > 0.98, but still only have 34 clusters,  
<img width="621" alt="image" src="https://github.com/MrOlm/drep/assets/58076352/35fbe996-bebf-437d-814b-8fd9c8d71315">
