### ISSUE TITLE
dRep: Argument list too long

### ISSUE THREAD

**Issue by jianhuang525** [MrOlm/drep#228]
My MAGs have 71,000 bins.   it too many~
when i run 
dRep dereplicate drep/ -g test/*.fa -sa 0.95 -nc 0.30 -p 256  -pa 0.9 -cm larger
it error 
dRep: Argument list too long

how can i cope with it >.<

**Comment by MrOlm** [comment]
You can provide a text file listing the location of each genome to the `-f` argument; that way it will get around the argument limit of your system.

Best,
Matt

**Comment by jianhuang525** [comment]
> You can provide a text file listing the location of each genome to the `-f` argument; that way it will get around the argument limit of your system.
> 
> Best, Matt

when i make the genome list ,  it seed the same error. 
 ls refinem/*fa > bin_list.txt
-bash: /usr/bin/ls: Argument list too long
i will try to batch settlement to make genome list.

**Comment by MrOlm** [comment]
You’ll just need to use “find” rather than “ls” to make the genome list.

Best,
Matt
