### ISSUE TITLE
stuck on checkm

### ISSUE THREAD

**Issue by francesco-ricci** [MrOlm/drep#229]
Hello there,

while running dRep my command gets stuck on check ddplacer step, precisely: 

[2024-04-12 14:58:27] INFO: Placing 4 bins into the genome tree with pplacer (be patient).

The command doe not return an error but it stays stuck there forever.

Thanks for your help!

**Comment by MrOlm** [comment]
Hi @francesco-ricci -

Urg, checkM can be frustrating to run, especially pplacer. I'd recommend either 1) running in taxonomy mode, which avoids pplacer, 2) reaching out to the checkM developers to see if they have a solution, or 3) running checkM outside of dRep (you could also try checkM2?) and just provding the results to dRep as external_genome_quality_information.

Best,
Matt
