### ISSUE TITLE
Question abunt the output of dRep

### ISSUE THREAD

**Issue by quliping** [MrOlm/drep#230]
dRep is a good software and very useful in my research. However, I have some problems. The docs of dRep said a figure named 'Cluster_scoring.pdf'  will be produced under the folder 'figures' in the output dir. However, I didn't found this figure in my output dir. No  warnning was produced by dRep.  By the way, the file 'Winning_genomes.pdf' wa also could not be opened. 

![image](https://github.com/MrOlm/drep/assets/39583607/2cb9e2c5-e7af-4356-82a9-63eab040d07c)

I also have the other question. this two genomes have ANI lower than the threshold 95%, and both of them was markered as represent genome, but why they have the same leaf color? Maybe they should in different colors?
<img width="758" alt="ff3782a6e792fb49eb6fc6129ea044b" src="https://github.com/MrOlm/drep/assets/39583607/febd4e8a-17e6-4a94-a4bd-3e7a77d831ff">

**Comment by MrOlm** [comment]
Hi @quliping -

Thanks for the kind words about dRep. To figure out why the figures aren't working, please 1) make sure you're using the most up-to-date version of dRep, and 2) run with `-d`, which will tell you the error as to why the figures aren't working.

That's also a good point about the colors- I agree that in this circumstance they should be different colors. I'm not sure what caused that problem; let me know if it persists for you (it could be that those are different colors, they're just very very similar)

Best,
Matt
