### ISSUE TITLE
checkM overwriting itself?

### ISSUE THREAD

**Issue by biojiangke** [MrOlm/drep#233]
I've experienced a strange issue with the dRep process with "--checkM_method taxonomy_wf" option. It has been working fine with smaller number of genomes (<1,000), but on a larger collection of genomes (~10,000), the process stopped at checkM stage. Checking the error log, I noticed that checkM had been running in chunks (7 chunks), until it stopped at chunk 4, and restarted from the beginning, at which point giving me the error message "FileExistsError: [Errno 17] File exists: 'XXXX_drep/data/checkM/checkM_outdir/genome_chunk_0_out/'". Apparently this was the first checkM chunk output from the previous round and a new checkM process cannot overwrite it. Is this due to the first round of checkM crashing (memory issues?) or something else? Any advice would be very helpful! Thanks!

**Comment by MrOlm** [comment]
Huh- I've never encountered that before. One potential workaround could be to add `--checkm_group_size 20000` to your command in order to make dRep run as one group? You could also run checkM yourself outside of dRep and provide the results to dRep.

Best,
Matt

**Comment by biojiangke** [comment]
Great! I'll give this a try and come back with updates. Thanks!

**Comment by biojiangke** [comment]
I can confirm adding the option "--checkm_group_size 20000" worked. It took all genomes in one chunk and finished without problem. Thanks for the help!

**Comment by MrOlm** [comment]
Beautiful- thanks for the update!
