### ISSUE TITLE
A new dRep BUG

### ISSUE THREAD

**Issue by LiHao1995** [MrOlm/drep#250]
(drep) llhei@X:/media/llhei/My Passport/drep$ dRep dereplicate ./drep -g dreplicated_bin/*.fa metawrap_50_10_bins/*.fa -sa 0.95 -nc 0.30 -p 8 --genomeInfo output.csv --checkm_group_size 55
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
549 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Past prodigal runs found- will not re-run
Running checkM
Running checkM in 10 chunks
Running checkM chunk 0
!!! checkM failed !!!
See https://drep.readthedocs.io/en/latest/advanced_use.html#troubleshooting-checkm for help troubleshooting
(drep) llhei@X:/media/llhei/My Passport/drep$ head output.csv
genome,completeness,contamination
bin.1009,80.59,5.81
bin.1014,72.63,7.49
bin.1026,70.98,9.55
bin.1027,87.55,1.34
bin.1039,83.41,1.68
bin.105,90.13,2.20
bin.1062,98.66,0.67
bin.1069,75.27,5.19
bin.107,76.62,0.13
(drep) llhei@X:/media/llhei/My Passport/drep$ dRep check_dependencies
mash.................................... all good        (location = /home/llhei/anaconda3/envs/drep/bin/mash)
nucmer.................................. all good        (location = /home/llhei/anaconda3/envs/drep/bin/nucmer)
checkm.................................. all good        (location = /home/llhei/anaconda3/envs/drep/bin/checkm)
ANIcalculator........................... all good        (location = /home/llhei/anaconda3/envs/drep/bin/ANIcalculator)
prodigal................................ all good        (location = /home/llhei/anaconda3/envs/drep/bin/prodigal)
centrifuge.............................. all good        (location = /home/llhei/anaconda3/envs/drep/bin/centrifuge)
nsimscan................................ all good        (location = /home/llhei/anaconda3/envs/drep/bin/nsimscan)
fastANI................................. all good        (location = /home/llhei/anaconda3/envs/drep/bin/fastANI)
skani................................... all good        (location = /home/llhei/anaconda3/envs/drep/bin/skani)

As mentioned above, my dRep 3.5.0 has turned into a low-performing tool that cannot call CheckM, yet I haven't received any useful error messages. Has anyone encountered this issue?

**Comment by MrOlm** [comment]
Hi @LiHao1995 - run dRep in debug mode (with `-d`) and look in the output `log` folder. You'll see the logs that checkM produces as it crashes. You could also just run checkM yourself and provide the results to dRep as externalGenomeQualityInformation.

Best,
Matt

**Comment by LiHao1995** [comment]
感谢您的建议。我已经排查了故障，那是因为路径中某个目录的名称存在空格导致的。祝您圣诞快乐😁😁😁😁😁



---- Replied Message ----
| From | Matt ***@***.***> |
| Date | 12/25/2024 22:50 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MrOlm/drep] A new dRep BUG (Issue #250) |

Hi @LiHao1995 - run dRep in debug mode (with -d) and look in the output log folder. You'll see the logs that checkM produces as it crashes. You could also just run checkM yourself and provide the results to dRep as externalGenomeQualityInformation.

Best,
Matt
