### ISSUE TITLE
what is threshold of checkm to pass genomes?

### ISSUE THREAD

**Issue by diego00012138** [MrOlm/drep#251]
Hi,
     Your work is really great, however drep seems to abandon some of my concerned genomes because of the checkm. But there must be some rules to do that cus the input genomes were pre-checked by checkm within metaWRAP pipeline and the completeness is 69.13 with contamination as 2.362,which to some extent are not bad. I  notice that you mentioned the parameter --ignoreGenomeQuality can prevent this checkm issue, but  I just want to know the threshold.
Sincerely

**Comment by MrOlm** [comment]
If you run `dRep dereplicate -h`, you will find the GENOME FILTERING OPTIONS. That list these details. They can also be adjusted. Text below.

Best,
Matt

```
GENOME FILTERING OPTIONS:
  -l LENGTH, --length LENGTH
                        Minimum genome length (default: 50000)
  -comp COMPLETENESS, --completeness COMPLETENESS
                        Minimum genome completeness (default: 75)
  -con CONTAMINATION, --contamination CONTAMINATION
                        Maximum genome contamination (default: 25)
```
