### ISSUE TITLE
Hard-code colors in the pie charts

### ISSUE THREAD

**Issue by fungs** [MrOlm/drep#27]
Hi, I'd recommend an improvement: the categories in the pie charts (winning genomes) are fixed, so it would make sense to pick a nice palette and stick to it. Right now, the colors swap between different runs and are thus more difficult to compare.

Best,
Johannes

**Comment by MrOlm** [comment]
Hello,

I agree that is would be a useful thing to do but I simply don't have the time. I would be happy to accept a pull request with these changes if anyone else would like to implement them.

Best,
Matt
