### ISSUE TITLE
'missing' genome

### ISSUE THREAD

**Issue by camillaln** [MrOlm/drep#30]
Hi,

I ran dRep on a bunch or MAGs. If I am reading your explanations right, genomes with > 75% completness and < 24% redundancy (contamination) should be kept. Yet, I found that some MAGs with completness at 83 - 89 (and contamination 3.6 - 3.9) according to CheckM are not included among the winning dereplicated MAGs. Is there something about these MAGs that excludes them that I missed while reading the documents?

I ran this analysis in febrauary on the previous dRep version that was up. I recently updated, so I will re-run the analysis if this has been addressed already.

Camilla
The bins in fasta (added .txt to name to upload them)
[UASBVU0Maxbin.001.fasta.txt](https://github.com/MrOlm/drep/files/1989285/UASBVU0Maxbin.001.fasta.txt)
[UASBVU03megahit.metabat.bin.41.fasta.txt](https://github.com/MrOlm/drep/files/1989286/UASBVU03megahit.metabat.bin.41.fasta.txt)

**Comment by MrOlm** [comment]
Hi Camilla,

Genomes that aren't filtered out based on genome completeness / contamination could have been excluded from the de-replicated genome set if they were similar to other genomes that were included in the final genome set. That is, if they were the "same" as another better genome.

Are the genomes included in the files `Bdb.csv` and `Cdb.csv`, in the data_tables folder? If so, this is probably the case. If not, could you please send me the `GenomeInformation.csv` file?

Thank you,
-Matt

**Comment by camillaln** [comment]
Hi
Thanks for getting back to me.
These genomes have no other very similar genomes among the ones I am de-replicating. They are not in the Mdb.csv file.
They are also not in Bdb.csv or in Cdb.csv.
I could not find the GenomeInformation.csv file. However, in the Chdb.tsv file I see they have high level of Strain heterogeneity - will this cause them to be filtered out?
Thanks agian for your input. I appreciate it!
Camilla
[Chdb.tsv.txt](https://github.com/MrOlm/drep/files/1989875/Chdb.tsv.txt)

**Comment by MrOlm** [comment]
Ahh yes. Depending on the version of dRep used, strain heterogeneity can be used as another filtering metric.

You can adjust the maximum strain-heterogeneity allowed, but I would recommend updating to the latest version of dRep with `pip install drep --update`. The latest dRep version doesn't even allow filtering by strain-heterogeneity, so that definitely won't happen.

Best,
-Matt

**Comment by camillaln** [comment]
Great! I am re-running with the new version :)
