### ISSUE TITLE
Bin made drep crash

### ISSUE THREAD

**Issue by camillaln** [MrOlm/drep#34]
Heia,

I had issues with dRep not doing the third CheckM run. 
Our systems-person
[DGG1DGG0PEPACbiospadesmb.bin.40.fa.txt](https://github.com/MrOlm/drep/files/2167076/DGG1DGG0PEPACbiospadesmb.bin.40.fa.txt)
 looked at it for me - and found that it could be due to one 'problematic' bin (see below).  I looked at  DGG1DGG0PEPACbiospadesmb.bin.40.fa and its just one large contig, with N's in the middle.
I removed DGG1DGG0PEPACbiospadesmb.bin.40.fa and dRep completed.
I have attached the bin. Do you know what the problem with the bin can be? I dont think its the N's since many other bins also have there.

Thanks
Camilla

This is what Dean reported to me:
I am not sure how checkm works, but dRep is using it fine, there is a log file in your “FeiBinDrep” directory that shows two checkm calls that worked fine, and then the third one fails:

07-03 13:46 DEBUG Starting the dereplicate operation
07-03 13:46 INFO ***************************************************
..:: dRep dereplicate Step 1. Filter ::..
***************************************************

07-03 13:46 DEBUG Loading work directory in filter
07-03 13:46 DEBUG Located: /nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep
Datatables: []
Cluster files: []
Arguments: []
07-03 13:46 DEBUG Validating filter arguments
07-03 13:46 INFO Will filter the genome list
07-03 13:46 INFO Calculating genome info of genomes
07-03 13:48 DEBUG Filtering genomes by size
07-03 13:48 INFO 100.00% of genomes passed length filtering
07-03 13:48 DEBUG Running CheckM
07-03 13:48 INFO Running prodigal
07-03 15:39 INFO Running checkM
07-03 15:39 DEBUG Running CheckM with command: ['/usr/local/bin/checkm', 'lineage_wf', '/nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/prodigal/', '/nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/checkM/checkM_outdir/', '-f', '/nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/checkM/checkM_outdir//results.tsv', '--tab_table', '-t', '6', '--pplacer_threads', '6', '-g', '-x', 'faa']
07-03 15:47 DEBUG Running CheckM with command: ['/usr/local/bin/checkm', 'qa', '/nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/checkM/checkM_outdir/lineage.ms', '/nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/checkM/checkM_outdir/', '-f', '/nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/checkM/checkM_outdir/Chdb.tsv', '-t', '6', '--tab_table', '-o', '2']
07-03 15:47 ERROR !!! checkM failed !!!

There were no files created for the second command, so it failed, I ran the first command and it failed for not being able to find “guppy” I found some guppys on the system and placed it in the path.

*******************************************************************************
[CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

Identifying marker genes in 1028 bins with 6 threads:
Finished processing 1028 of 1028 (100.00%) bins.
Saving HMM info to file.

Calculating genome statistics for 1028 bins with 6 threads:
Finished processing 1028 of 1028 (100.00%) bins.

Extracting marker genes to align.
Parsing HMM hits to marker genes:
Finished parsing hits for 1028 of 1028 (100.00%) bins.
Extracting 43 HMMs with 6 threads:
Finished extracting 43 of 43 (100.00%) HMMs.
Aligning 43 marker genes with 6 threads:
Finished aligning 43 of 43 (100.00%) marker genes.

[Error] Make sure guppy, which is part of the pplacer package, is on your system path.

Controlled exit resulting from an unrecoverable error or warning.

Running the command:
/usr/local/bin/checkm lineage_wf /nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/prodigal/ /nfs/groups/edwards/camilla/Fei/allDGGBins
/Bins/FeiBinDrep/data/checkM/checkM_outdir/ -f /nfs/groups/edwards/camilla/Fei/allDGGBins/Bins/FeiBinDrep/data/checkM/checkM_outdir//results.tsv --tab_table -t 6 --pplacer_threads 6 -g -x faa

Gives an error with a file DGG1DGG0PEPACbiospadesmb.bin.40.fa . Are you able to see what that issue maybe, or can that set be removed and see if it works?

*******************************************************************************
[CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

Identifying marker genes in 1028 bins with 6 threads:
Finished processing 383 of 1028 (37.26%) bins.
Finished processing 387 of 1028 (37.65%) bins.
Finished processing 1028 of 1028 (100.00%) bins.
Saving HMM info to file.

Calculating genome statistics for 1028 bins with 6 threads:
Finished processing 1028 of 1028 (100.00%) bins.

Extracting marker genes to align.
Parsing HMM hits to marker genes:
Finished parsing hits for 1028 of 1028 (100.00%) bins.
Extracting 43 HMMs with 6 threads:
Finished extracting 43 of 43 (100.00%) HMMs.
Aligning 43 marker genes with 6 threads:
Finished aligning 43 of 43 (100.00%) marker genes.

Reading marker alignment files.
Concatenating alignments.
Placing 1028 bins into the genome tree with pplacer (be patient).

{ Current stage: 0:50:32.227 || Total: 0:50:32.227 }

*******************************************************************************
[CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

Reading HMM info from file.
Parsing HMM hits to marker genes:
Finished parsing hits for 1028 of 1028 (100.00%) bins.

Determining marker sets for each genome bin.
Finished processing 245 of 1028 (23.83%) bins (current: DGG1DGG0PEPACbiospadesmb.bin.40.fa).
Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
File "/usr/local/bin/checkm", line 712, in <module>
checkmParser.parseOptions(args)
File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1245, in parseOptions
self.lineageSet(options)
File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 230, in lineageSet
resultsParser, options.unique, options.multi)
File "/usr/local/lib/python2.7/dist-packages/checkm/treeParser.py", line 515, in getBinMarkerSets
domainNode = self.__findDomainNode(node)
File "/usr/local/lib/python2.7/dist-packages/checkm/treeParser.py", line 244, in __findDomainNode
if curNode.label:
AttributeError: 'NoneType' object has no attribute 'label'
nesbocam@silicon:/groups/edwards/camilla/Fei/allDGGBins/Bins$

A section of file 40 has :

ACAGATTAAACAAATCCGACGGGAATAAACATAACCCATAAACGAGTANNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNAAGTGGGTAGCGCTCAAATTGTAGGTGGAACA
Maybe the “N”s are the issue?"

**Comment by MrOlm** [comment]
Hi Camilla,

That's an interesting error, and not something that I've ever run into before.

From a little bit of googling around, it seems like this is a bug in checkM that was fixed is the most recent version https://github.com/Ecogenomics/CheckM/issues/117

I would try and update checkm to the most recent version (anything above v1.0.8) and try again- it seems like that should work.

Best,
-Matt
