### ISSUE TITLE
Primary clustering figure labels are out of order when many genomes are compared

### ISSUE THREAD

**Issue by brymerr921** [MrOlm/drep#37]
Hi, I am using dRep (v2.2.2, installed using `pip install drep`) to cluster and then analyze a few hundred genomes at a time, and noticed that the labels on plot 1 (`Primary_clustering_dendrogram.pdf`) were all out of order.  The steps I took were:

1. Download a few hundred genomes. For example, all _Prevotella_. https://www.ncbi.nlm.nih.gov/assembly/?term=prevotella (Click "Download Assemblies", source = GenBank, file type = Genomic FASTA)
2. `tar -xf` the archive and `gunzip` the files within the folder
3. Run `dRep cluster out_dir -p 14 --SkipSecondary -g *.fna`
4. Run `dRep analyze out_dir --plots 1`

The files `Mdb.csv` and `Cdb.csv` appear to be correct, however. Doing steps 3-4 with just a handful (~20) genomes doesn't seem to cause an error with misplaced labels. I'm not sure where the upper bound is where this becomes a problem.

Here's a snippet of a tree with labels that are out of order:
![image](https://user-images.githubusercontent.com/7491066/46778791-23bf4d80-ccca-11e8-9ef8-fb3cad244293.png)

**Comment by MrOlm** [comment]
Hi Bryan,

Thanks for the super-thorough bug report. Following your instructions I was able to re-create the bug on my machine.

Thanks again, and I'll let you know when there's a new version available with the fix.

-Matt

**Comment by MrOlm** [comment]
Bug is fixed in version 2.2.3. Get the newest version using the command `pip install drep --upgrade`.

Thanks again for the bug report!
-Matt

**Comment by brymerr921** [comment]
It works great!!! Thanks so much for the fix.
