### ISSUE TITLE
Program checkm is not working!! Im going to crash now

### ISSUE THREAD

**Issue by jolespin** [MrOlm/drep#38]
I have my `checkm` working correctly and my `dRep` installed.  I switched the shebang so it correctly calls `checkm`.  I don't understand how to fix this error.

**Comment by MrOlm** [comment]
I'm not sure what you mean by switching the shebang.

A difficulty is that `checkm` is written in python2, whereas `dRep` is written in python3. At the moment to get around this you can either 1) use a python environment manager like `pyenv` to allow dRep to make an external call to `checkm`, or 2) run `checkm` on your genomes on your own and provide the results to dRep.

Instructions on how to do both of these things are available in the online documentation (https://drep.readthedocs.io/en/latest/), but let me know if you have any questions about how to do either of those things.

-Matt

**Comment by jolespin** [comment]
Thanks! I will attempt the latter b/c I have to use a weird translation table for my bins.
