### ISSUE TITLE
sort Cluster_scoring barplots in winner order

### ISSUE THREAD

**Issue by brooksomics** [MrOlm/drep#4]
In the Cluster_scoring.pdf the y-axis sorts genomes alphabetically. I think it would be more useful to sort by score. I realize I could parse the data_tables/ but think you should consider making this default. I also just wanted to be the first person to put an issue on your issue tracker for drep ;)

**Comment by MrOlm** [comment]
This is a good idea. I will assign it to a co-author for implementation
