### ISSUE TITLE
"Argument list too long" when running w/ 45k bins

### ISSUE THREAD

**Issue by defleury** [MrOlm/drep#42]
Hi @MrOlm ,

I'm trying to run dRep on a very large set of bins and reference genomes, totalling ~45k. No matter how I attempt to set up the script, I get the following error:

```
run.dRep.sh: line 1: [...]/bin/dRep: Argument list too long
```

I'm running dRep `v2.2.3`, in a conda environment.

Is this an OS issue, or do you somehow have a hard cutoff on how many genomes/bins will be processed?

Edit. Re the command line I'm using, nothing fancy there. I have pre-filtered the genome list based on my own checkM run, so here's what I do:

```
dRep dereplicate [path_to_wd] -p 24 --noQualityFiltering --genomes [genome_1.fa genome_2.fa ...]
```

**Comment by MrOlm** [comment]
Hi @defleury ,

This is an OS issue- most OSs just can't handle argument lists that long. In the absence of a better solution, there is an easy hacky way to get around this. It involves making a datatable of your genome locations and putting it in the internals of the work directory. It's easy to do but finicky, so I've tried to spell out the instructions as completely as possible.

1) Make a `.csv` file of your genome locations and call it `Bdb.csv`. This file must have exactly 2 columns- one named "genome" and the other named "location". The column `location` must contain the full path to each genome, and the column `genome` must contain the basename of each genome. Your Bdb.csv will have 45k rows. Here's an example:

```
$ head Bdb.csv
genome,location
GCF_000744065.1.fasta,/data1/bio_db/refseq/parsed/group_4/GCF_000744065.1.fasta
GCF_001007995.1.fasta,/data1/bio_db/refseq/parsed/group_6/GCF_001007995.1.fasta
GCF_001307505.1.fasta,/data1/bio_db/refseq/parsed/group_9/GCF_001307505.1.fasta
GCF_000160075.2.fasta,/data1/bio_db/refseq/parsed/group_2/GCF_000160075.2.fasta
GCF_001815865.1.fasta,/data1/bio_db/refseq/parsed/group_13/GCF_001815865.1.fasta
GCF_000376245.1.fasta,/data1/bio_db/refseq/parsed/group_1/GCF_000376245.1.fasta
GCF_000018105.1.fasta,/data1/bio_db/refseq/parsed/group_0/GCF_000018105.1.fasta
GCF_000238775.1.fasta,/data1/bio_db/refseq/parsed/group_0/GCF_000238775.1.fasta
GCF_900103835.1.fasta,/data1/bio_db/refseq/parsed/group_13/GCF_900103835.1.fasta
```

2) Make an empty dRep work directory. The easiest way to do this is with the command `dRep bonus [path_to_wd] --check_dependencies`. You'll see that [path_to_wd] now exists and as a couple of folders in it.

3) Put the file `Bdb.csv` inside the folder `data_tables` in this new [path_to_wd] 

4) Run the command as you normally would using the [path_to_wd] that you just made, without using any argument for `--genomes`. dRep will recognize that there's a list of genomes to use in the `Bdb.csv` file and use those, getting around the need to pass dRep a huge argument list. Your command, for example, would be:

`dRep dereplicate [path_to_wd] -p 24 --noQualityFiltering`

I hope this answers your question and let me know if you run into any snags. 45k is on the upper limit of genomes that I've run with dRep but it should work. More recent versions of dRep (including the version you have) have specific changes that make it handle huge numbers of genomes better.

Best,
-Matt

**Comment by defleury** [comment]
Great, this works :-)

Thanks a lot for your quick and constructive reply!

Best,


Sebastian

**Comment by nick-youngblut** [comment]
It would be nice if dRep accepted a csv as mentioned above instead of the requirement for a long list of fasta file arguments in the command. This will keep users from having to dig through closed issues for this hack.

**Comment by MrOlm** [comment]
As of version 2.5.0, dRep now accepts a text file with a list of genomes as an input

**Comment by nick-youngblut** [comment]
Awesome! Thanks! Any timeline for when bioconda will be updated?
