### ISSUE TITLE
change secondary ANI but the same results

### ISSUE THREAD

**Issue by zyyalice** [MrOlm/drep#44]
Hi Matt 
   
Genome de-replication by commond: dRep dereplicate out_dir -g genome/*.fasta
and then i want to change the threshold of ANI with commands as follows:
      dRep dereplicate out_dir -sa 0.95 -g genome/*.fasta
but i got the same results with two commands above.  
then i  tried to use the Single operations step by step
    1. dRep filter out_dir -g genome/*.fasta
    2. dRep cluster out_dir -sa 0.95
    3. dRep choose out_dir
    4. dRep bonus out_dir
    5. dRep evaluate out_dir -e a
    6. dRep analyze out_dir -pl a 
There are no error in the process. but the results are the same with these three command. 

   Did i use the wrong command ? 
   Could you help me?
   Thank you very much!

Best 
Alice

**Comment by zyyalice** [comment]
Hi Matt 

Thank you very much for your reply!

1. I have checked the figure "Secondary_clustering_dendrograms.pdf", the threshold was changed to 0.95. but the de-replicate genomes choosen was the same in dereplicate genome directory, even when i changed the threshod to 0.90. therefore, its a normal results ?? 
2. Sorry for my unclear expression. the same i mentioned means that when i change the threshold, the dereplicate genomes were the same.
3. I have make a new out_dir when running dRep with a different threshold.

Best
Alice

**Comment by MrOlm** [comment]
Hi Alice,

it sounds like, for your particular community, 0.99, 0.95, and 0.9 yield the same number of de-replicated genomes. This is possible if all of your genomes are either very different or very similar to each other.

You can check this for sure by looking at the "Secondary_clustering_dendrograms.pdf" figure for your 0.9 result. Changing the threshold essentially just moves the line to the left. If moving the line to the left doesn't result in splitting up clusters, it won't result in more de-replicated genomes.

Does this make sense? Some more info on this can be found at the following link:

https://drep.readthedocs.io/en/latest/example_output.html#figures

Best,
-Matt
