### ISSUE TITLE
New checkM db needs to be made

### ISSUE THREAD

**Issue by housw** [MrOlm/drep#45]
Hi Matt, 

`dRep` worked in one of my projects, but failed in another one with this error message: ` New checkM db needs to be made`, and here is the detailed info:
 
```
02-04 08:21 DEBUG    Starting the dereplicate operation
02-04 08:21 INFO     ***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
02-04 08:21 DEBUG    Loading work directory in filter
02-04 08:21 DEBUG    Located: /mnt/redundans_dRep/derep
Datatables: []
Cluster files: []
Arguments: []
02-04 08:21 DEBUG    Validating filter arguments
02-04 08:21 INFO     Will filter the genome list
02-04 08:21 INFO     Calculating genome info of genomes
02-04 08:21 DEBUG    Filtering genomes by size
02-04 08:21 INFO     95.23% of genomes passed length filtering
02-04 08:21 DEBUG    Running CheckM
02-04 08:21 INFO     Running prodigal
02-04 08:30 INFO     Running checkM
02-04 08:30 DEBUG    Running CheckM with command: ['/usr/local/bin/checkm', 'lineage_wf', '/mnt/redundans_dRep/derep/data/prodigal/', '/mnt/redundans_dRep/derep/data/checkM/checkM_outdir/', '-f', '/mnt/re
dundans_dRep/derep/data/checkM/checkM_outdir//results.tsv', '--tab_table', '-t', '6', '--pplacer_threads', '6', '-g', '-x', 'faa']
02-04 10:43 DEBUG    Running CheckM with command: ['/usr/local/bin/checkm', 'qa', '/mnt/redundans_dRep/derep/data/checkM/checkM_outdir/lineage.ms', '/mnt/redundans_dRep/derep/data/checkM/checkM_outdir/', 
'-f', '/mnt/redundans_dRep/derep/data/checkM/checkM_outdir/Chdb.tsv', '-t', '6', '--tab_table', '-o', '2']
02-04 10:45 ERROR    BinSanity.213.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    concoct.140.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    concoct.227.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    maxbin2.095.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    maxbin2.610.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2036.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2158.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2176.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2303.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2361.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2410.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2490.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2613.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2730.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.2808.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.282.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3004.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3009.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3083.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3284.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3338.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3407.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.347.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3510.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3543.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3852.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.3893.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.4098.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.4279.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.4802.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.4924.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.5154.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.647.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.771.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    vamb.911.contigs.filtered.filtered.filtered.fa is not in checkM db
02-04 10:45 ERROR    New checkM db needs to be made
```

So is it a controlled exit or have I missed anything? I'm using docker, you can pull the image via `docker push shengwei/drep:latest`, the source code of the docker image is here: https://github.com/housw/docker/tree/master/dRep

Thanks in advance.

Best,
Shengwei

**Comment by housw** [comment]
Hi Matt, 

thanks a lot for your prompt reply. I finally realize that's a storage problem, `checkM` writes some intermediate temporary results to `/tmp` by default, and by default the spawned docker container works at `/var/lib/docker/`. Unfortunately, we have limited storage under `/`, so in the end `checkM` run out of storage space and quit, resulting in incomplete `checkM` results.

In case someone else having the same error, the solution is 
* changing the default tmp direcotory in checkM via `--tmpdir`
* mounting a different storage area to `/tmp` of the container if you're using docker

Sorry for bugging you, Matt. Please close it. 

Best, 
Shengwei

**Comment by MrOlm** [comment]
Great! Glad you were able to get it working, Shengwei, and thanks a ton for posting a detailed solution in case others run into the same issue.

Best,
Matt

**Comment by Naima16** [comment]
Hi Matt
I have exactly the same error, I cant figure out how to change the checkM default tmp directory since it is implicitly called by dRep?

**Comment by MrOlm** [comment]
Hello,

I'll try and add support for this in the next dRep update. In the meantime it seems like you'll need to run dRep and checkM  separately. If you run checkM on your own, you can provide the results to dRep with the `--genomeInfo` flag. Is that what you did @housw ?

**Comment by Naima16** [comment]
Hi Matt

No, I did not provide checkM results to dRep, even if I have  them. I can’t find the right output with the bins id, completeness and contamination in any of the output folders from checkM, 
Instead of that, I have them mixed with all debug info in the slurm file and it will be so hard to extract only the info I need from all the big file, 
may be I missed a parameter in checkM command which may produce a nice table file ?
Thanks again

All the best,
Naïma

**Comment by MrOlm** [comment]
Sorry @Naima16 - the question of "is that you did it?" was meant for @housw 

If you run inStrain in debug mode (`-d`),  the folder `log/cmd_logs/` will contain a file listing the checkM command dRep tried to call. Based on the solution provided by @housw , it seems like you could modify that command by adding a new `--tmpdir` flag to the checkM command. It should then succeed and produce a nice table file that you can pass to dRep.

Best,
Matt

**Comment by housw** [comment]
Hi Matt, hi Naïma, 

the solution I provided was for the Python2 version `checkM` and `dRep` v2.2.3, it should work with the docker image if the server isn't limited by storage where `/tmp` is mounted. If the `/tmp` directory was mounted to a small partition, `checkM` might use up all the storage and raise the above errors. In that case, you can spawn a new docker container with `/tmp` mounted to a larger partition. 

If you have the same error while running `checkM`, it can be solved by changing the `--tmpdir` as well, basically the same issue. I haven't tested using `checkM` output as `dRep` input. In theory, it should work if you can run them separately, the command you're looking for might be [`checkm qa`](https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa).

Best, 
Shengwei

**Comment by Naima16** [comment]
Hi,

Thank you for the answer !

I am working on a cluster and I have no rights to play with disk partitions !! 

increasing the requested memory for the job solved my problem !!

Thanks again !

All the best,

Naïma

**Comment by housw** [comment]
That's fantastic, Naïma, thanks for the update!
