### ISSUE TITLE
genomeInfo.csv and strain_heterogeneity

### ISSUE THREAD

**Issue by nigiord** [MrOlm/drep#47]
Hi there,

I appreciate the fact that you provided a way to skip the checkM step by providing a csv file with external quality information. dRep documentation for the dereplicate workflow states:

```
  --genomeInfo GENOMEINFO
                        location of .csv file containing quality information
                        on the genomes. Must contain: ["genome"(basename of
                        .fasta file of that genome), "completeness"(0-100
                        value for completeness of the genome),
                        "contamination"(0-100 value of the contamination of
                        the genome)] (default: None)
```
But in other parts of the workflow, it seems dRep also uses the strain heterogeneity to compute a score and select "winner" genomes. I do not understand then why only completeness and contamination are asked for in the csv file provided.

I have a list of genomes on which I've already run checkM: is it possible for me to provide completeness, contamination and strain heterogeneity using `--genomeInfo`? Or will dRep ignore the strain heterogeneity criteria?

Cheers,
Nils

**Comment by MrOlm** [comment]
Hi Niles,

If your input dataframe has a column titled `strain_heterogeneity` dRep will validate the column and use it the same as it would had you run checkM natively. Sorry for the unclear help documentation!

-Matt
