### ISSUE TITLE
installing from github gives dRep v1.4.3

### ISSUE THREAD

**Issue by Jtrachsel** [MrOlm/drep#54]
Hello, 

when I install from github using the following commands, i get dRep v1.4.3
```
$ git clone https://github.com/MrOlm/drep.git
$ cd drep
$ pip install .
```
When i install  with `pip install drep`  i get version 2.0.

is the code on this github the latest version of dRep?

**Comment by MrOlm** [comment]
Hi Jtrachsel,

That is odd- both on GitHub and on pypi should have dRep version 2.3.2 (the latest version).

I just tried on my own machine, following the same steps listed above, and ended up with the most up-to-date version.

Is it possible that you have an old version of dRep floating around somewhere on your machine? I've encountered this problem several times. The only way I've figured out of fixing it is by continually trying `which dRep` and/or `pyenv which dRep` to identify where dRep is in installed, and manually removing those files and related files until dRep is no longer anywhere in my system path. 

Then, reinstalling dRep (using the steps you listed above) should work.

As a last sanity check, you can see the version of dRep that you cloned from GitHub in the file `dRep/VERSION`. It should say 2.3.2.

Best,
Matt

**Comment by Jtrachsel** [comment]
Thank you for the quick response.  You are correct, the pip installation from the git repo and pypi both give me dRep 2.3.2 so all is well. 

I think i found the source of my confusion, in the `drep/bin/` directory there is an executable named dRep,  when i use this executable to call dRep (with `cd drep/bin` and then `./dRep`) it tells me that it's dRep 1.4.3.  If i use the executable that pip places for me there are no issues.

and thanks for the software, its been very handy recently.
