### ISSUE TITLE
ANImf - how is filtering done?

### ISSUE THREAD

**Issue by bsiranosian** [MrOlm/drep#55]
Hi, I can't find any details on the filtering done with the ANImf algorithm on your read the docs page. What do you do? This also might be good to add to the documentation. 

Thanks!

**Comment by MrOlm** [comment]
Hi Brian,

This is done using the mummer command `delta-filter -r -q` (http://mummer.sourceforge.net/manual/#filter). Thanks for the question, and I will add this information to the documentation

Best,
Matt
