### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lavik17** [MrOlm/drep#6]
It would be great if a user could add information regarding the sample from which each genome came from and the output would show which genome is the best for each sample in each cluster. Something along the lines of:

cluster 1: Best genome, best genome from sample 1, best genome from sample 2 etc...

**Comment by MrOlm** [comment]
This is something I considered for a while, but ultimately decided against implementing for a couple of reasons: 

1) it would require significant complication of input (how would the user provide this information? in a table?) the program already has so many command-line arguments that I'm weary of adding more

2) it would require a number of internal changes to many modules to handle this information, i.e. a signifiant coding-time investment when there are other, arguably more important changes that could be made first

3) most importantly, it's relatively easy for the user to work-around this issue. Some possible solutions are:

- first run dRep on each sample, take the resulting "dereplicated genomes" from each sample, and then fun dRep again on all of them

- using the data tables "Sdb" and "Cdb", this should be relatively easy for the user to implement themself in R or excel. This way they can parse their genome names to figure out where it came from using whatever method they came up with, under an arbitrary number of groupings. Sdb contains the score of each genome, and Cdb lists each genome's secondary cluster.

Thank you for the suggestion, and please let me know if you have any others! :)
