### ISSUE TITLE
Completeness and redundancy using DAS Tools approach?

### ISSUE THREAD

**Issue by adityabandla** [MrOlm/drep#60]
I have been using DAS Tool for aggregating results from different binning tools and it provides a summary of completeness & redundancy. Can this be used in place of checkm?

**Comment by MrOlm** [comment]
Hi Aditya,

That's a great question that I've never considered before. Currently the only way of doing this is to convert the final output of dasTool (ending in `.summary.txt`) into a .csv file with the attributes `genome,completeness,comtamination`. This file can then be passed into dRep with the parameter `--genomeInfo`. See the following for more information: https://drep.readthedocs.io/en/latest/advanced_use.html#using-external-genome-quality-information 

I'll consider adding native integration with dasTool in the future, as it is a good idea, but I'm a bit swamped at the moment

Thanks for the suggestion,
-Matt

**Comment by MrOlm** [comment]
This is a good idea but I've officially conceded that I don't have time to implement, especially given that it's already possible to do this in the hacky way described above. Closing
