### ISSUE TITLE
Effect of contamination on gANI

### ISSUE THREAD

**Issue by adityabandla** [MrOlm/drep#63]
Hi Matt,
My redundant set of MAGs have contamination ranging from 0-60% 
I am trying to obtain a strain-resolved non-redundant set and thus I am using a gANI cutoff of 99.9%
Given the range of contamination, does gANI still give robust results when pushed to its limit?
Cheers,
Adi

**Comment by MrOlm** [comment]
Hi Adi,

I haven't tested this exactly, but my intuition is that it should be fine. The parameter you'll want to watch out for is `nc`, or the minimum coverage of the alignment. With `gANI`, the alignment coverage is the percentage of the proteins that align. So as long as 10% (default `nc` value) of the proteins in each genome align to each others, ANI should still function and just ignore the proteins that don't align (which hopefully would be all of the contaminating genes)

Best,
Matt

**Comment by adityabandla** [comment]
Thanks, Matt!
Does 10 % nc still work when gANI is pushed to >99.9% to collapse identical (more or less) genomes or is it better to increase nc when pushing gANI beyond 99%?

Also, is there a specific reason why you limit strain heterogeneity to 25% as default?

**Comment by adityabandla** [comment]
Hi Matt

Thanks for clarifying. Plotting alignment coverage from Ndb.csv was really helpful for judging how the dereplication went

I think the documentation needs to be updated to reflect this change. Under module descriptions, the filter command is said to have this option with default as 25

Cheers,
Adi

**Comment by MrOlm** [comment]
Documentation has been updated to reflect this. Thanks for pointing out!
