### ISSUE TITLE
Support for fastANI

### ISSUE THREAD

**Issue by adityabandla** [MrOlm/drep#64]
Hi Matt 

Is it possible to add support for fastANI?
ANI calculator seems to be slow when there a large number of pairwise comparisons to be made using gANI

Cheers,
Adi

**Comment by MrOlm** [comment]
Hey Adi,

Yes, this is possible and something that I've been meaning to do for a bit. I'll see what I can do for the next dRep release.

Best,
-Matt

**Comment by MrOlm** [comment]
fastANI is now an option in dRep version 2.5.0
