### ISSUE TITLE
Dereplicating assemblies?

### ISSUE THREAD

**Issue by franciscozorrilla** [MrOlm/drep#65]
Hi, I am wondering if it would be possible to use dRep to reconcile the assembly output of different assemblers for a given sample? Im thinking something similar to what the metaWRAP bin refinement module does, but for assemblies instead of for bins?

Let me know if you think this would be possible or even useful.
Best,
Francisco

**Comment by MrOlm** [comment]
Hi Francisco,

dRep would probably not work well for this job, but this is also a more difficult problem than it seems at first glance, as defining whether scaffolds are the same vs. different is a surprisingly complicated. I believe that I've seen people in the past use overlap assemblers for this type of problem, which seems reasonable to me, but I don't have any experience doing this myself.

Good luck!
-Matt
