### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by TarsLi** [MrOlm/drep#66]
Hi,
I have recovered about 150k genome bins from the metagenomes and try to cluster them using dRep. There is no problem when i cluster about 9k genomes using dRep. However, there is an error occurred when i cluster all 150k genomes. 
my command is "dRep cluster ./ -p 10 -pa 0.8 --SkipSecondary -g ./*.fa"
And i got an error "-bash: /home/lenovo/.pyenv/shims/dRep: Argument list too long". 
Is there a limitation of the genome number? Do you have any suggestion? Thanks!

**Comment by MrOlm** [comment]
Hi Tars Li,

This is a known issue that I'm working on fixing. In the meaning, here is a link to a hack-y solution that will make it work for now.

https://github.com/MrOlm/drep/issues/42

Best,
Matt

**Comment by MrOlm** [comment]
FYI- As of version 2.5.0, dRep now accepts a text file with a list of genomes as an input

**Comment by Biofarmer** [comment]
I am using the version 2.6.2, however this is no flag in the help to tell how to use a text file. May I ask how to add this flag?
Thanks

**Comment by MrOlm** [comment]
Hello,

If you provide a text file with a list of genome locations with the `-g` flag, dRep will load and use those genomes. Sorry the help isn't more helpful- it will be updated in the next upcoming version of dRep.

-Matt

**Comment by Biofarmer** [comment]
Hi Matt, thanks for reply. May I ask if it is fine to run 50k samples with dRep compare? thanks

**Comment by MrOlm** [comment]
That's about at the upper edge of what will work with the current version of dRep. The limiting factor is the RAM needed to do the primary clustering. If it doesn't work for you, doing it in two groups of 25k should work. dRep v3 will be able to handle this better, but I don't expect it to be ready for another couple of weeks.

**Comment by Biofarmer** [comment]
Hi, if the test file is made in window and then upload to linux, is it necessary to remove/transfer the ^M (window format) at end of each line to linux format? or does it not matter for dRep? 
Thanks

**Comment by MrOlm** [comment]
I believe you'll need to convert them to linux format, but I'm actually not positive. It's just using python's default "readlines()" function call

-Matt
