### ISSUE TITLE
param flag

### ISSUE THREAD

**Issue by n1mus** [MrOlm/drep#69]
https://github.com/MrOlm/drep/blob/e3e24408a1137d0b5e1b5a5c836501335bf0e52a/drep/argumentParser.py#L109

Hi,

I was testing dRep and noticed that this is the only param flag that does not have a two-dash flag?

Best wishes,
Sumin

**Comment by MrOlm** [comment]
Hello- thanks for pointing out. This has been fixed in version 2.4.1
