### ISSUE TITLE
Non-symmetrical database

### ISSUE THREAD

**Issue by thh32** [MrOlm/drep#70]
I have been using dRep for the last few days to dRep a bunch of databases, I have just tried running it on a three large (>3000 genomes) datasets when I got the following error;

`The database passed in is not symetrical`

This was after the MASH calculation when it was attempting clustering.

Any idea what has caused this as I have not received this error before.

Thanks for any help you can provide!

**Comment by MrOlm** [comment]
Hi Thomas,

That error probably indicates that one of the genomes that you passed in failed Mash clustering for some reason. Can you ensure that all genomes don't have special characters in them (nothing but A, C, T, G), and especially make sure that none of your genomes have the same filename?

Best,
Matt

**Comment by thh32** [comment]
Hi Matt, thanks for help, turns out it was due to the harddrive formatting, the number of comparisons dRep wanted to do was more than the number of files a single directory can hold, so it crashed and failed part way through. I have redirected the output to another harddrive which is in a different format and now it works fine. Thanks again for a great tool.
