### ISSUE TITLE
Memory too demanding?

### ISSUE THREAD

**Issue by anuravi1234** [MrOlm/drep#72]
Hello, 

I am running dRep on around 400+ genomes. I am running this in a cluster but my analyses stop at CheckM since it requires around 1.2Tb of memory. I remember for CheckM I use the -r (reduced tree) parameter which reduces memory usage drastically. I was wondering if there is an option in dRep to reduce the memory for CheckM or could you please advice any other way?

Thanks!

**Comment by MrOlm** [comment]
Hello,

Wow, that's a lot of memory! I've never had checkM use that much memory before, but I'm actually not too familiar with how it works.

You have a couple of options. You could run checkM on your own (using `-r` or whatever) and then provide the results to dRep using the flag `--genome_information`. Or you could also run checkM in `taxonomy_wf` mode through dRep, but this will just assume that all of your genomes are bacteria and use universal bacterial single copy genes. 

Best,
Matt

**Comment by anuravi1234** [comment]
Hello,

Thank you for answering this question and I used the genomeInfo to add this information and it ran smoothly. I was running the steps separately (filter, cluster, choose, evaluate and analyze). Everything ran smoothly until "evaluate"

I started to get this error:
Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 161, in parseArguments
    self.evaluate_operation(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/drep/controller.py", line 81, in evaluate_operation
    drep.d_evaluate.d_evaluate_wrapper(kwargs['work_directory'],**kwargs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_evaluate.py", line 23, in d_evaluate_wrapper
    to_eval = drep.d_analyze._parse_plot_options(options, evs)
  File "/usr/local/lib/python3.6/site-packages/drep/d_analyze.py", line 1174, in _parse_plot_options
    if args[0] in ['all','a']:
TypeError: 'NoneType' object is not subscriptable

I check if I had any empty files and I didnt find any. 
This was logged in the logger

03-15 13:47 DEBUG    Command to run dRep was: /usr/local/bin/dRep evaluate drep_genomes_100

03-15 13:47 DEBUG    dRep version 2.5.3 was run 

03-15 13:47 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

03-15 13:47 DEBUG    Namespace(debug=False, evaluate=None, operation='evaluate', processors=6, warn_aln=0.25, warn_dist=0.25, warn_sim=0.98, work_directory='drep_genomes_100')
03-15 13:47 DEBUG    Starting the evaluate operation
03-15 13:47 DEBUG    Loading work directory
03-15 13:47 DEBUG    Located: /qib/platforms/Informatics/transfer/incoming/Warren_promethION/project-for-paper/results/long_reads/hybrid-assembly-opera-ms/genome_MAGS/drep_genomes_100
Datatables: ['Sdb', 'Cdb', 'Ndb', 'genomeInfo', 'Bdb', 'Chdb', 'Mdb', 'Wdb', 'genomeInformation']
Cluster files: ['primary_linkage', 'secondary_linkage_cluster_27', 'secondary_linkage_cluster_26', 'secondary_linkage_cluster_9', 'secondary_linkage_cluster_30', 'secondary_linkage_cluster_8', 'secondary_linkage_cluster_13', 'secondary_linkage_cluster_7', 'secondary_linkage_cluster_36', 'secondary_linkage_cluster_25', 'secondary_linkage_cluster_24', 'secondary_linkage_cluster_28', 'secondary_linkage_cluster_37', 'secondary_linkage_cluster_23', 'secondary_linkage_cluster_6', 'secondary_linkage_cluster_33', 'secondary_linkage_cluster_39', 'secondary_linkage_cluster_10', 'secondary_linkage_cluster_34', 'secondary_linkage_cluster_19', 'secondary_linkage_cluster_14', 'secondary_linkage_cluster_1']
Arguments: ['cluster']

could you let me know what could be the problem 

Thanks!
Anu

**Comment by MrOlm** [comment]
Hi Anu,

Let me look into this. To be honest I don't use the `evaluate` module very much, so it hasn't been maintained in a while (so I'm not surprised that it has bugs), but I'll look into fixing it

Best,
Matt

**Comment by anuravi1234** [comment]
Thank you for taking a lot at this and you are right that I am able to obtain the figures and the clustering data without evaluate so I am good with this :) I find the clustering data provided with the dereplicated genomes is really useful!
Thanks for including those!

Anu

**Comment by MrOlm** [comment]
Great! Let me know if you run into any other issues!
