### ISSUE TITLE
assert r in Idb.columns, "{0} missing from GenomeInfo".format(r) AssertionError: completeness missing from GenomeInfo

### ISSUE THREAD

**Issue by weijiaxiaoxing** [MrOlm/drep#79]
Hello,
I am running dRep on 1872 genomes. I've already installed dRep correctly, which were ensured by command "dRep bonus output_directory
-- check_dependencies", and it showed that all dependencies were good. However, when I tried to run dRep dereplicate, it always get error: 
[Weixin@ts-rd350 NCBI_MT_0_10_Chloroflexi_Genomes]$ /home/Weixin/.local/bin/dRep dereplicate chloroflexi_genomes_dRep_99_90_5_wd -g chloroflexi_1872_genomes/*.fna -pa 0.9 -sa 0.99 --genomeInfo combined_qualities.txt -comp 90 -con 5 -p 20
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Traceback (most recent call last):
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 114, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 180, in _validate_genomeInfo
    assert genome in Idb['genome'].tolist(), "{0} missing from GenomeInfo".format(genome)
AssertionError: GCA_000009025.1_Dehalococcoides_mccartyi_CBDB1.fna missing from GenomeInfo

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/Weixin/.local/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 81, in d_filter_wrapper
    Gdb = _get_run_genomeInfo(wd, bdb, **kwargs)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 118, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 161, in _validate_genomeInfo
    assert r in Idb.columns, "{0} missing from GenomeInfo".format(r)
AssertionError: completeness missing from GenomeInfo

I believe the file that I am proving follows this format (top few lines below):
genome,completeness,contamination
Bin_1-contigs.fa,84.48,70.69
Bin_10-contigs.fa,75.61,11.08
Bin_11-contigs.fa,61.68,16.38
Bin_12-contigs.fa,99.25,0
Bin_12_A-contigs.fa,84.68,20.6
The format of partly checkm_out_file is :
genome,completeness,contamination
GCA_003205875.1_Herpetosiphon_llansteffanensis.fna,99.09,1.82
GCA_003253565.1_Thermosporothrix_hazakensis.fna,98.68,10.89
GCA_003228115.1_Chloroflexi_bacterium.fna,98.68,0
GCA_003268475.1_Thermogemmatispora_tikiterensis.fna,98.18,2.97
GCA_003228195.2_Chloroflexi_bacterium.fna,97.19,1.98
GCA_003242625.1_Sphaerobacter_thermophilus.fna,95.33,0.93
GCA_003169735.1_Chloroflexi_bacterium.fna,95.06,2.78
GCA_003228685.1_Chloroflexi_bacterium.fna,94.47,3.96
GCA_003260405.1_Dehalococcoides_mccartyi.fna,94.46,0
GCA_003171065.1_Chloroflexi_bacterium.fna,94.28,0.93

However I have still receiving error messages that genome, completeness etc. is missing from the input file. Any suggestions or something that I am missing?

**Comment by MrOlm** [comment]
Hello,

Yes, it does look like your genomeInfo file is being read incorrectly, and based on the example you gave, it does seem to be formatted properly. A couple of questions- 

First, your file "combined_qualities.txt" is separated by comma's, as indicated in the example you attached, right? It's not separated by tabs?

Second, sometimes when preparing .txt files on a Mac OSX system, weird stuff can happen with "return" characters. Could you potentially run the command as suggested by this website "https://marcelog.github.io/articles/mac_newline_to_unix_eol.html" on your  "combined_qualities.txt" file to see if that fixes the problem?

If this doesn't work and the problem persists, let me know, and I'll add some code to dRep to print out what it thinks your "combined_qualities.txt" file looks like. This should let us know what's going on and why the file isn't being read correctly.

Best,
Matt

**Comment by weijiaxiaoxing** [comment]
Hallo Matt,

Thank you fou your help.
First, my file "combined_qualities.txt" is separated by comma's and l dont't know how to  separate my file by tabs corectly. l am a new in bioinformatic. By the way, my drep version is 2.3.2.It used to be version 2.6.0, but I changed it.

Second,l don't use  Mac OSX system,but l still run the command as your suggestion: cat file.txt | tr '\r' '\n' | tr -s '\n' > file.translated.txt .The file format is below： 
genome,completeness,contamination
GCA_003205875.1_Herpetosiphon_llansteffanensis.fna,99.09,1.82
[GCA_003253565.1_Thermosporothrix_hazakensis.fna,98.68,10.89]
GCA_003228115.1_Chloroflexi_bacterium.fna,98.68,0
GCA_003268475.1_Thermogemmatispora_tikiterensis.fna,98.18,2.97
GCA_003228195.2_Chloroflexi_bacterium.fna,97.19,1.98
GCA_003242625.1_Sphaerobacter_thermophilus.fna,95.33,0.93

Now,this error is still going on:
[Weixin@ts-rd350 NCBI_MT_0_10_Chloroflexi_Genomes]$  dRep dereplicate chloroflexi_1872_genomes_dRep_99_90_5_wd -g chloroflexi_1872_genomes/*.fna -pa 0.9 -sa 0.99 --genomeInfo combined_qualities.txt -comp 90 -con 5 -p 30
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Traceback (most recent call last):
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 114, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 161, in _validate_genomeInfo
    assert r in Idb.columns, "{0} missing from GenomeInfo".format(r)
AssertionError: completeness missing from GenomeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 81, in d_filter_wrapper
    Gdb = _get_run_genomeInfo(wd, bdb, **kwargs)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 118, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/home/Weixin/.local/lib/python3.6/site-packages/drep/d_filter.py", line 161, in _validate_genomeInfo
    assert r in Idb.columns, "{0} missing from GenomeInfo".format(r)
AssertionError: completeness missing from GenomeInfo

Do you have any advice how to fix this errors ?

Best wishes,
Xing

**Comment by MrOlm** [comment]
Hi Xing,

I just pushed a new version of dRep, version 2.6.2, to help troubleshoot this issue. Please install and new version by using the command `pip install drep --upgrade`, and try this again.

After the run is finished, if you look in the file `log/logger.log` you will see what dRep thinks your genomeInformation file looks like. Hopefully this helps us figure out what is going wrong.

Best,
Matt

**Comment by weijiaxiaoxing** [comment]
Hallo Matt,

Thank you fou your help.
I meet the problem when I try to install and new version by using the command pip install drep --upgrade.I fail to upgrade drep.
[Weixin@ts-rd350 NCBI_MT_0_10_Chloroflexi_Genomes]$ pip install drep --upgrade --user Weixin i https://pypi.tuna.tsinghua.edu.cn/simple/
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting https://pypi.tuna.tsinghua.edu.cn/simple/
  Downloading https://pypi.tuna.tsinghua.edu.cn/simple/ (12.5 MB)
     |████████████████████████████████| 12.5 MB 1.6 MB/s 
  ERROR: Cannot unpack file /tmp/pip-unpack-PMWpqd/simple (downloaded from /tmp/pip-req-build-5ZDKYz, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-5ZDKYz

I don't know how to slove it.Thank you again.

Best wishes,
Xing

**Comment by MrOlm** [comment]
Hi Xing,

Unfortunately I am unable to help with this aspect of troubleshooting. Pip / python can get confusing and have specific quarks depending on how it's installed, and I'm no expert in sorting those out. I can assure you that dRep is able to be installed properly if python / pip are set up correctly though. If you have a system administrator you can talk to about this they would be a good person to reach out to. That said, there are a couple of suggestions I can give:

1) Try the command `pip3` instead of `pip` - it seems that you may be using a legacy version of python (python2), which will not work with dRep

2) Try and use a python version manager, like `pyenv` or `conda` to install a fresh version of python outside of your global system installation. This is helpful if you don't have root access to the system

3) Try and completely remove the old version of dRep from your system before re-installing

Good luck!
-Matt
