### ISSUE TITLE
Pair wise mash clustering issue

### ISSUE THREAD

**Issue by shaman-narayanasamy** [MrOlm/drep#8]
Dear Matt,

Me again :) 

I was trying to see if dRep was behaving weirdly due to the datasets/environment. Therefore, I copied the genomes provided within dRep for testing purposes into my input folder and proceeded to run the following command:

`$ dRep dereplicate_wf -p 4 --completeness 0.6 --strain_htr 101 --P_ani 0.6 --S_ani 0.965 --overwrite         --run_tax /scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/RepresentativeBins -g /scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/AllBins/*.fa`

It fails on the clustering step for some reason:

```
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
[====================] 100.00%
2b. Cluster pair-wise MASH clustering
Traceback (most recent call last):
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/env3.4.3/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_wf_operation(**vars(args))
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/controller.py", line 86, in dereplicate_wf_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 287, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(Bdb, data_folder, **kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 106, in cluster_genomes
    Cdb = cluster_mash_database(Mdb, data_folder= data_folder, **kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 662, in cluster_mash_database
    linkage_cutoff= P_Lcutoff)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 355, in cluster_hierarchical
    linkage = scipy.cluster.hierarchy.linkage(arr, method= linkage_method)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/scipy/cluster/hierarchy.py", line 660, in linkage
    n = int(distance.num_obs_y(y))
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/scipy/spatial/distance.py", line 1718, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```

Any idea if this is an issue with my environment. 

Please know that dRep is working very well for our data sets. It is just that we are finding some inconsistencies from time to time and would like to report them to be fixed. We are looking to keep using dRep on more of our data. Looking forward to hear from you. 

Cheers,
Shaman

**Comment by MrOlm** [comment]
Hi Shaman,

Thanks again for helping root out possible bugs in dRep, and I'm happy to hear that your lab is finding it useful.

That error is the result of it not finding any Mash runs for whatever reason. A couple of things:

1) It looks like your command might not be in the correct format; a work directory (where all of the output is stored) is supposed to be immediately after the call to `derepliate_wf`. For example:

```
$ dRep dereplicate_wf /scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/RepresentativeBins -p 4 --completeness 0.6 --strain_htr 101 --P_ani 0.6 --S_ani 0.965 --overwrite --run_tax -g /scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/AllBins/*.fa
```

The output folder would then be:

```
/scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/RepresentativeBins
```

2) The program is able to test itself to see if the environment is causing issues. If you download the "tests" folder, and run the following command from within it:

```
$ ./test_suite.py
```

it should automatically run dRep on the test genomes in a couple of different ways, and automatically compare the results to some pre-computed output.

3) To troubleshoot the issue you're reporting above (assuming that the order of the arguments in the call is not what's causing the problem), there are a couple of things that would be helpful to know:

- could you upload your log? (log/logger.log)
- are there any files in your Mash data folder? (data/MASH_files/sketches/)
- could you upload Bdb? (data_tables/Bdb.csv). That data-table lists all the genomes the program is using as input.

Best,
-Matt

**Comment by shaman-narayanasamy** [comment]
Hi Matt,

Thanks for the usual prompt reply.

1. I didn't realize I was using it wrong all this time. I corrected it, but this did not seem to make any difference.

2. I know about the self test script provided within dRep. The weird thing is that it does not work when I try to run it. Below is what happens when I launch it:

```
$ tests/test_suite.py 
Traceback (most recent call last):
  File "tests/test_suite.py", line 466, in <module>
    test_quick()
  File "tests/test_suite.py", line 462, in test_quick
    rerun_test()
  File "tests/test_suite.py", line 446, in rerun_test
    QuickTests().run()
  File "tests/test_suite.py", line 291, in run
    self.setUp()
  File "tests/test_suite.py", line 283, in setUp
    os.path.join(self.working_wd_loc, 'data'))
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/lib/python3.4/shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/gaiagpfs/users/homedirs/snarayanasamy/repositories/drep/../tests/test_solutions/ecoli_wd/data'
```
or when I launch from the folder:
```
$ ./test_suite.py 
Traceback (most recent call last):
  File "./test_suite.py", line 466, in <module>
    test_quick()
  File "./test_suite.py", line 462, in test_quick
    rerun_test()
  File "./test_suite.py", line 446, in rerun_test
    QuickTests().run()
  File "./test_suite.py", line 291, in run
    self.setUp()
  File "./test_suite.py", line 281, in setUp
    os.mkdir(self.working_wd_loc)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/gaiagpfs/users/homedirs/snarayanasamy/repositories/drep/tests/../tests/test_backend/ecoli_wd'
```
I proceeded without passing these tests because dRep seemed to work for me somehow. I guess I should have made sure this worked first.

3. Please find attached (logger.log and the Bdb.csv) within the attached file:
[dRep_debug.tar.gz](https://github.com/MrOlm/drep/files/922814/dRep_debug.tar.gz)

Inside the MASH_files/sketches folder, I find: Enterococcus_faecalis_TX0104.fa.msh

The weird thing is that this behavior seems specific to the test data provided within dRep. I tried running the same command and added some of my own genomes (on top of those already provided by the test) and it seemed to run rather swimmingly. Let me know if you need anything else.

-Shaman-

**Comment by MrOlm** [comment]
Hi Shaman,

OK, I think I know the cause of both of these issues.

1) I believe the reason the test_suite.py isn't working is due to a dumb error on my part after some recent changes to the test suite. I believe it will work if you make a directory called "test_backend" in the "tests" folder. For example:

```
$ mkdir test_backend
```

If this proves to be the case of course I will fix it in the next version.

2) I believe the reason it isn't working when you run the genomes directly is because the genomes all have different file extensions. This was done on purpose to make sure dRep could handle different extensions, but in this case it appears to have messed up your wildcard statement. In the call you posted in the first message, I now notice that it reads:

`-g /scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/AllBins/*.fa`

This will only catch one genome, as the rest don't actually end in .fa. This should be modified to:

`-g /scratch/users/snarayanasamy/LAO_TS_IMP-v1.3/TemporalBinning/AllBins/*`

As always, thanks again for helping make dRep a better program!

-Matt

**Comment by brooksomics** [comment]
Hey Matt,

I'm having some trouble as well running dRep in my new environment.

I tried the test suite as you suggested to Shaman.

````
$ mkdir test_backend
$ ls ../tests/
genomes  test_backend  test_solutions  test_suite.py
$ ./test_suite.py
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
3 primary clusters made
Step 3. Perform secondary clustering
Running 11 ANIn comparisons- should take ~ 0.6 min
Step 4. Return output
Traceback (most recent call last):
  File "./test_suite.py", line 466, in <module>
    test_quick()
  File "./test_suite.py", line 462, in test_quick
    rerun_test()
  File "./test_suite.py", line 446, in rerun_test
    QuickTests().run()
  File "./test_suite.py", line 292, in run
    self.unit_tests_1()
  File "./test_suite.py", line 325, in unit_tests_1
    assert db1.equals(db2), "{0} is not the same!".format(db)
AssertionError: Ndb is not the same!
````
So I see it complaining about Ndb. I'm using dRep v0.5.5 and according to tests/test_solutions/log/logger.log the most recent test_suite was run on v0.5.4. So maybe there are some old dataframes that need refreshing?

So I reran in a new directory with the provided genomes:
```
dRep dereplicate_wf . -g genomes/* -o -p 16 --run_tax --S_algorithm gANI -sa 0.99 --cent_index /home/ubuntu/scripts/github/centrifuge/indices/b+h+v &> drep.log &
```
Everything works! So perhaps updating your test_solutions/ dir is the answer here?

My problem is unrelated - so i'll start a new thread.

**Comment by MrOlm** [comment]
Hey Bubba,

That's very weird... I just tried it on my system and it worked without error.

Would you mind sending me your Ndb.csv file that's not working? It should be located:

`tests/test_backend/ecoli_wd/data_tables/Ndb.csv`

I can then see what's different about it from the one in the solutions directory

Thanks,
-Matt

**Comment by brooksomics** [comment]
Ndb.csv attached:
[Ndb.txt](https://github.com/MrOlm/drep/files/930373/Ndb.txt)

**Comment by MrOlm** [comment]
Bizarre. This seems to be happening not due to real differences, but because the genomes were loaded in a different order. This may be due to differences in how wildcards are handled on different systems? Either way, the testing suite will be updated to handle this (but it looks like your installation is working fine)

**Comment by brooksomics** [comment]
I suspect you're probably right. I've noticed some odd things making the switch from Gentoo to Ubuntu.

**Comment by shaman-narayanasamy** [comment]
Hi Matt (and Bubba),

Sorry for the lapse in communication. So, here is what I did now:

1. checked out back to the master branch. I assumed you already merged the changes from "my" (shaman_fix) branch and pulled the latest changes.

2. I go into the test folder and create the folder you mentioned.
`cd tests/`
`mkdir test_backend`
`ls -trlh`
```
total 16K
drwxr-xr-x 2 snarayanasamy clusterusers 4.0K Feb 24 14:57 genomes
drwxr-xr-x 3 snarayanasamy clusterusers 4.0K Feb 24 14:57 test_solutions
-rwxr-xr-x 1 snarayanasamy clusterusers  13K Apr  8 17:32 test_suite.py
drwxr-xr-x 2 snarayanasamy clusterusers 4.0K Apr 19 11:19 test_backend
```
3. Launch the test suite. It looks to be better than before, but still getting these errors at the last step :(
`./test_suite.py `
```
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
3 primary clusters made
Step 3. Perform secondary clustering
Running 11 ANIn comparisons- should take ~ 0.6 min
Step 4. Return output
Traceback (most recent call last):
  File "./test_suite.py", line 466, in <module>
    test_quick()
  File "./test_suite.py", line 462, in test_quick
    rerun_test()
  File "./test_suite.py", line 446, in rerun_test
    QuickTests().run()
  File "./test_suite.py", line 292, in run
    self.unit_tests_1()
  File "./test_suite.py", line 325, in unit_tests_1
    assert db1.equals(db2), "{0} is not the same!".format(db)
AssertionError: Cdb is not the same!
```

Just in case you are wondering about my environment, I am running dRep on my computing cluster. It uses the `module` framework to load packages. Therefore, I have the following modules loaded: 
`module list`
```
Currently Loaded Modules:
  1) compiler/icc/2015.3.187         4) mpi/impi/5.0.3.048-iccifort-2015.3.187   7) toolchain/ictce/7.3.5
  2) compiler/ifort/2015.3.187       5) toolchain/iimpi/7.3.5                    8) bio/HMMER/3.1b2-ictce-7.3.5
  3) toolchain/iccifort/2015.3.187   6) numlib/imkl/11.2.3.187-iimpi-7.3.5
```
I also have my python environments loaded:
`pyenv versions`
```
  system
  2.7.3
  2.7.3/envs/env2.7.3
  3.4.3
  3.4.3/envs/env3.4.3
* env2.7.3 (set by /mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/version)
* env3.4.3 (set by /mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/version)
```
Let me know if you need more information.

Cheers!
Shaman

**Comment by MrOlm** [comment]
Hi Sharman,

Would you mind uploading one file for me so that I can confirm what I think is going on- it should be located `tests/test_backend/ecoli_wd/data_tables/Cdb.csv`

If I'm right, this is more of a fake problem due to the ways that different operating systems order things, and I should be able to fix it relatively easily.

Thanks!
-Matt

**Comment by shaman-narayanasamy** [comment]
Hi Matt,

Apologies for the delay. Here you go:

[Cdb.csv.txt](https://github.com/MrOlm/drep/files/954535/Cdb.csv.txt)

Sorry for the weird file extension. Github, for reasons beyond my understanding, does not accept csv files...

Let me know if you need anything else :)

-Shaman-

**Comment by MrOlm** [comment]
Hi Shaman,

So I think this is actually due to the same problem as Bubba was experiencing; differences in the way that different OS handle ordering.

I just pushed an update that to fix that particular issue (v0.5.7). Hopefully that solves it; if not please let me know!

Best,
-Matt

**Comment by shaman-narayanasamy** [comment]
Hi Matt,

Apologies for the delay. I just found the time to test this again. 

I pulled the latest changes (master branch) and ran the test suite. The test seems to work swimmingly! :D

I notice that the test suite seems to print the stdout multiple times now, like so:
```
$ ./test_suite.py 
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
3 primary clusters made
Step 3. Perform secondary clustering
Running 11 ANIn comparisons- should take ~ 0.6 min
Step 4. Return output
Step 1. Parse Arguments
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
3 primary clusters made
3 primary clusters made
Step 3. Perform secondary clustering
Step 3. Perform secondary clustering
Step 4. Return output
Step 4. Return output
Step 1. Parse Arguments
Step 1. Parse Arguments
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
```

Then, I realized that in the `test_backend/ecoli_wd/dereplicated_genomes` folder is completely empty :(

I tested again by copying the genomes somewhere else and launching drep. However, a regular launch causes the error below.
```
$ dRep dereplicate_wf         RepresentativeBins         -p 4         --completeness 0.6         --strain_htr 101         --P_ani 0.6         --S_ani 0.965         --overwrite         --run_tax         -g AllBins/*.fa

Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
[====================] 100.00%
2b. Cluster pair-wise MASH clustering
Traceback (most recent call last):
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/env3.4.3/bin/dRep", line 26, in <module>
    controller.parseArguments(args)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_wf_operation(**vars(args))
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/controller.py", line 86, in dereplicate_wf_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 287, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(Bdb, data_folder, **kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 106, in cluster_genomes
    Cdb = cluster_mash_database(Mdb, data_folder= data_folder, **kwargs)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 662, in cluster_mash_database
    linkage_cutoff= P_Lcutoff)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/drep/d_cluster.py", line 355, in cluster_hierarchical
    linkage = scipy.cluster.hierarchy.linkage(arr, method= linkage_method)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/scipy/cluster/hierarchy.py", line 660, in linkage
    n = int(distance.num_obs_y(y))
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.4.3/envs/env3.4.3/lib/python3.4/site-packages/scipy/spatial/distance.py", line 1718, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```
This seems to be the same error I initially received. Let me know if you need anything else to further debug.

Best regards,
Shaman

**Comment by MrOlm** [comment]
Hi Shaman,

Glad to hear that the test_suite isn't crashing for you anymore!

As far as the other problem, could you please send me your log file (log/logger.log), as well as any tables that were created in data_tables?

Thank you!
-Matt

**Comment by shaman-narayanasamy** [comment]
Hi Matt,

Sorry for the late reply. 

Looks like my last post was a false alarm. I notice that these example genomes seems to be failing because I am using very specific parameters: 

`dRep dereplicate_wf         RepresentativeBins         -p 48         --completeness 0.6         --strain_htr 101         --P_ani 0.6         --S_ani 0.965         --overwrite         -g AllBins/*.fa`

I am not sure if this is a good diagnosis of the problem, but it only fails on those example genomes and not when I use my own genomes/bins.

Therefore, dRep works rather swimmingly on my own genomes and bins, stemming from a real dataset. Specifically, I ran it on more than 12000 bins, ending up with more than 2000 representative genomes. It took approximately 3 days on a 48 threads (and lots of memory). I am not sure if you've ran it on such a large dataset before. Just though I should report it to let you know that it works :)

Let me know if you have more questions. If not, I think we can close this issue :)

Cheers!
Shaman

**Comment by MrOlm** [comment]
Strange about the example genomes, but I'm happy to hear that it worked for you on your real dataset.

Thanks for the report too! I've not tried it on anything that huge, and I'm glad it was able to complete without problems.

Thanks for helping me troubleshoot dRep, and I'll look forward to reading about this giant dataset soon :)

Best,
-Matt

**Comment by fplaza** [comment]
Hello,

I had the same issue.
I figured out it happens when less than 2 genomes pass the checkM filtering.

Adding a simple test should solve this bug.

Best,
Florian

**Comment by Paupiera** [comment]
Hello,

I am getting the same error than the one mentioned above:
"ValueError: The number of observations cannot be determined on an empty distance matrix."
As fplaza, it occurs when less than 2 genomes pass the checkM filtering.

There is any change in the dRep settings/paramters that avoid it ?
Otherwise a substantial fraction of genomes could be lost during the process

Thanks in advance for your help,
Pau

**Comment by MrOlm** [comment]
Hello,

Yes, there are many way to decrease the stringency of genome filtering so that less genomes get filtered out. See here (https://drep.readthedocs.io/en/latest/choosing_parameters.html#importance-of-genome-completeness) for some info on why the genome filtering is done in the first place, and see the GENOME FILTERING OPTIONS: here (https://drep.readthedocs.io/en/latest/module_descriptions.html#dereplicate) for how to control it.

Best,
Matt
