### ISSUE TITLE
dRep report "!!!checkM failed!!!"

### ISSUE THREAD

**Issue by LiZhihua1982** [MrOlm/drep#81]
![image](https://user-images.githubusercontent.com/38903973/84875881-86810300-b0c1-11ea-9d88-4f50bc295221.png)

**Comment by MrOlm** [comment]
A couple of things

1) Can you run `dRep bonus --check_dependencies` to see if checkM is properly installed?

2) Can you run the command again with `--debug` at the end of the command so that we can read the log of why checkM failed?

-Matt

**Comment by LiZhihua1982** [comment]
Dear Dr.Matt,
Thank you very much for your quick reply!
![image](https://user-images.githubusercontent.com/38903973/84965163-1a49e200-b149-11ea-854b-8a30174b120b.png)
![image](https://user-images.githubusercontent.com/38903973/84965205-38afdd80-b149-11ea-9bc8-56913f74f059.png)
![image](https://user-images.githubusercontent.com/38903973/84965232-4b2a1700-b149-11ea-95ae-d3cdf86a1624.png)
I use docker install and condo install, after run, all meet this errors.
Thank you very much!

Best regards

Li Zhihua

**Comment by MrOlm** [comment]
Interesting - it seems to think that only a single genome is being input to the program. Can you confirm that there is more than one genome captured with the wildcard `total/*.fa`?

**Comment by LiZhihua1982** [comment]
![image](https://user-images.githubusercontent.com/38903973/84966028-639b3100-b14b-11ea-8127-b00734591975.png)

**Comment by LiZhihua1982** [comment]
I try again it still error, the detail is below:
![image](https://user-images.githubusercontent.com/38903973/84967321-a0b4f280-b14e-11ea-84bd-6c215cefa2d7.png)
![image](https://user-images.githubusercontent.com/38903973/84967460-f1c4e680-b14e-11ea-8800-72b4c540b6ac.png)
![image](https://user-images.githubusercontent.com/38903973/84967485-02755c80-b14f-11ea-9fd5-3a8cf4321477.png)

**Comment by MrOlm** [comment]
Could you upload your `log/cmd_logs` folder? One of the files in there will be the error that checkM gave when it crashed

**Comment by LiZhihua1982** [comment]
[cmd_logs.zip](https://github.com/MrOlm/drep/files/4795857/cmd_logs.zip)

**Comment by LiZhihua1982** [comment]
Thank you very much!

**Comment by MrOlm** [comment]
Interesting, it's crashing quietly for some reason... a couple of questions

1) Does a file exist here - `/lustre7/home/lzh1982/data/30type/genomes/output2_total/data/checkM/checkM_outdir//results.tsv` ?

2) Try and run the following command and let me know what happens - `checkm lineage_wf /lustre7/home/lzh1982/data/30type/genomes/output2_total/data/prodigal/ /lustre7/home/lzh1982/data/30type/genomes/output2_total/data/checkM/checkM_outdir/ -f /lustre7/home/lzh1982/data/30type/genomes/output2_total/data/checkM/checkM_outdir//results.tsv --tab_table -t 6 --pplacer_threads 6 -g -x faa`

**Comment by LiZhihua1982** [comment]
Here is the another computer result
[different_computer_cmd_logs.zip](https://github.com/MrOlm/drep/files/4795955/different_computer_cmd_logs.zip)

**Comment by LiZhihua1982** [comment]
1. There is no results.tsv
2. 
![image](https://user-images.githubusercontent.com/38903973/84972053-04dcb400-b159-11ea-9249-799bf1965473.png)
![image](https://user-images.githubusercontent.com/38903973/84972081-13c36680-b159-11ea-9d1c-0ef3f9cecb59.png)

**Comment by MrOlm** [comment]
Ah- there's the problem. It says `Fatal Error: exception Out_of_memory`. This is a problem with checkM, not dRep. See more info on it here: https://github.com/Ecogenomics/CheckM/issues/105

Assuming all of your bins are bacterial, you could run dRep with `--checkM_method taxonomy_wf`, which will skip the pplacer step of checkM.

Best,
Matt

**Comment by LiZhihua1982** [comment]
Thank you very much! when the memory is 128G. it works!
