### ISSUE TITLE
dRep cluster: error

### ISSUE THREAD

**Issue by avpg3** [MrOlm/drep#82]
Dear contact, 
I am having this error (see below) when running dRep. I am not sure how to fix it. Any suggestion? 

Thanks, 
Angela P

(drep) [a.penag@magnus bin]$ dRep cluster -g /hpcfs/home/a.penag/01.PROJECTS/01.DROSOPHILA/13.ANI/Dasiri/drep_Dasiri/*.fasta -o drep_Dasiri
Step 1. Parse Arguments
Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
Traceback (most recent call last):
  File "/hpcfs/home/a.penag/.conda/envs/drep/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/hpcfs/home/a.penag/.conda/envs/drep/lib/python3.7/site-packages/drep/controller.py", line 151, in parseArguments
    self.cluster_operation(**vars(args))
  File "/hpcfs/home/a.penag/.conda/envs/drep/lib/python3.7/site-packages/drep/controller.py", line 56, in cluster_operation
    drep.d_cluster.d_cluster_wrapper(kwargs['work_directory'],**kwargs)
  File "/hpcfs/home/a.penag/.conda/envs/drep/lib/python3.7/site-packages/drep/d_cluster.py", line 58, in d_cluster_wrapper
    Cdb, Mdb, Ndb = cluster_genomes(Bdb, data_folder, wd=workDirectory, **kwargs)
  File "/hpcfs/home/a.penag/.conda/envs/drep/lib/python3.7/site-packages/drep/d_cluster.py", line 137, in cluster_genomes
    Mdb = all_vs_all_MASH(Bdb, data_folder, **kwargs)
  File "/hpcfs/home/a.penag/.conda/envs/drep/lib/python3.7/site-packages/drep/d_cluster.py", line 606, in all_vs_all_MASH
    dm.thread_cmds(cmds, logdir=logdir, t=int(p))
**NameError: name 'dm' is not defined**

**Comment by MrOlm** [comment]
Hello Angela,

I will reply to your question here, rather than over email, so that if anyone else happens to have this issue they can check here as well.

This is a really odd error, and it seems like the problem is that dRep is not properly installed. What happens when you run `dRep bonus --check_dependencies`? This could give some clues.

The way to fix this is to delete and re-install dRep from scratch. This would mean removing all traces of dRep (so that when you type `which dRep` nothing shows up), and then re-installing it with either `pip install drep --upgrade` or `conda install drep`.

Best,
Matt

**Comment by avpg3** [comment]
Thanks for the quick reply Matt. 
Here is the output when I run dRep bonus testDir --check_dependencies

<img width="1134" alt="Screen Shot 2020-06-17 at 8 14 01 PM" src="https://user-images.githubusercontent.com/67079319/84963357-285f1a80-b0d7-11ea-81a6-64c9cd2a45b1.png">

**Comment by MrOlm** [comment]
Hi Angela,

OK, this all looks good, but unfortunately I won't be able to help troubleshoot too much. 

Something (probably complicated) is going on with your different python versions that is causing this problem. Someone else had this problem and was able to trace it back to their pip being wrong  https://github.com/MrOlm/drep/issues/73 .

The only solution that I know if is to delete and install from scratch. One way of handling python versions is the program pyenv - using that gives you a python environment separate from everything else, and installing a fresh version of dRep inside pyenv would be a way of fixing this problem.

Let me know if there's anything else I can do to help
-Matt
