### ISSUE TITLE
New feature suggestion: resume

### ISSUE THREAD

**Issue by aelbehery** [MrOlm/drep#83]
Actually, dereplication using dRep can take long time, especially with large number of genomes and many computing clusters put a time limit to any submitted job. So, it would not be uncommon for a dRep job to be terminated by the cluster without being able to finsh. Rerunning dRep from the befinning won't help. So, I would like to see a feature that helps resume from where it stopped.

**Comment by MrOlm** [comment]
Hello,

This feature actually already exists and is built into dRep, though it is not well-advertised. If you run dRep with `--debug` mode, it will save progress as it goes along. If it crashes, if you run the same command on the half-completed directory (again with `--debug` flag), it will load the already completed steps instead of re-running them, and continue on it's way.

Let me know if you run into problems with this feature not working.

Best,
Matt

**Comment by Biofarmer** [comment]
In addition, may I ask if the running time will be longer with --debug than without --debug?

**Comment by cazzlewazzle89** [comment]
@MrOlm 

Sorry to reopen this issue but it seemed neater than starting a new one.
Would running dRep in `--debug` mode allow me to repeat deprelication with a different secondary clustering cutoff?
ie. I have 20k genomes and I want to dereplicate at 99, 98, 97, 96, 95% identity but the secondary clustering takes ~15 hours.
I would love to be able to take the results of the pairwise ANI calculations from the first run and redefine new clusters at each threshold without reclustering.

thanks,
Calum

**Comment by MrOlm** [comment]
Hi Calum,

Yes, if you run a dRep command again with the same dRep directory, it will load the ANI comparisons rather than re-running them. It will also overwrite the Cdb.csv file though, so make sure you copy that file out somewhere safe before running another dRep run.

Best,
Matt

**Comment by mgabriell1** [comment]
Sorry for reopening this issue, but I'm having issues restarting an analysis run using `--debug` mode.
The command I launched is:
`dRep dereplicate -p 16 -g dRep_dereplication/genomes_list --genomeInfo dRep_dereplication/checkm2.quality_report_dRep_input.csv --S_algorithm fastANI --MASH_sketch 100000 --S_ani 0.995 -strW 0 --debug dRep_dereplication/dRep_strains_99.5ANI` which stopped while performing secondary clustering. However I con't find any temporary files for FastANI (the `tmp` directory contains a list of the genomes supplied, while the log shows that mapping was actually performed by FastANI).
Also, relaunching the same command (which I understood is the way to restart an analysis in debug mode) just outputs the message below actually preventing me from restarting the analysis.
```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Both Bdb and a genome list are found- either don't include a genome list or start a new work directory!
```
What could be the issue?

Marco

**Comment by MrOlm** [comment]
Hi Marco,

I believe if you do not include a genome list (e.g. run the same command again without `-g dRep_dereplication/genomes_list`) that should do it

-Matt
