### ISSUE TITLE
the right checkm file format as dRep dereplicate -h indicated, still error

### ISSUE THREAD

**Issue by jianshu93** [MrOlm/drep#86]
no Mattern python env or just in base (all python3), this error keep emerging 

 assert r in Idb.columns, "{0} missing from GenomeInfo".format(r)
AssertionError: completeness missing from GenomeInfo

**Comment by MrOlm** [comment]
Hello,

You need to have the latest dRep version. See my reply to your other comment: https://github.com/MrOlm/drep/issues/85

Best,
Matt
