### ISSUE TITLE
pplacer OOM

### ISSUE THREAD

**Issue by brooksomics** [MrOlm/drep#9]
Hey Matt,

I'm consistently getting an out of memory error (OOM) in my new environment, AWS EC2 m4.4xlarge (16 CPU, 64 Gb RAM).  One option is to rent another machine with higher specs for more money. Another option is to add a low memory flag to dRep. 

I came upon the solution of calling "--reduced_tree" to reduce memory via checkM [here](https://github.com/Ecogenomics/CheckM/issues/37). Also see checkM's options [here](https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands). 

Another thought is to change pplacer parameters, see "Memory Usage" section [here](https://matsen.github.io/pplacer/generated_rst/pplacer.html), but I don't have much experience with this.

I'm happy to send along dRep logs - just let me know what's relevant for you.

As a start here's a system log clip:
```
Apr 18 02:16:29 ip-172-31-20-20 kernel: [92767.295137] Out of memory: Kill process 14057 (pplacer) score 541 or sacrifice child
Apr 18 02:16:29 ip-172-31-20-20 kernel: [92767.299315] Killed process 14057 (pplacer) total-vm:35679400kB, anon-rss:35673656kB, file-rss:0kB
```
And attached is the command log, captured with your favorite `&> mattsfavoritewaytocapture.logs &`.

The end of the log is:
```
$ tail cmd_drep_gANI_gt99.log
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/miniconda3/envs/irep/lib/python3.6/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/home/ubuntu/miniconda3/envs/irep/lib/python3.6/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ubuntu/miniconda3/envs/irep/lib/python3.6/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
FileNotFoundError: File b'/home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/data/centrifuge/GCF_000153905.1_ASM15390v1_genomic.fna_report.tsv' does not exist
```

And the dir indeed doesn't have this file and I think it's because of the OOM terminating the process:
```
$ ls /home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/data/centrifuge/
GCF_000153905.1_ASM15390v1_genomic.fna_hits.tsv    GCF_001404755.1_13470_2_82_genomic.fna_hits.tsv
GCF_000156675.1_ASM15667v1_genomic.fna_hits.tsv    GCF_001404775.1_14207_7_80_genomic.fna_hits.tsv
GCF_000157975.1_ASM15797v1_genomic.fna_hits.tsv    GCF_001404775.1_14207_7_80_genomic.fna_report.tsv
GCF_000373885.1_ASM37388v1_genomic.fna_hits.tsv    GCF_001404935.1_13414_6_41_genomic.fna_hits.tsv
GCF_000424085.1_ASM42408v1_genomic.fna_hits.tsv    GCF_001405215.1_14207_7_44_genomic.fna_hits.tsv
GCF_000424085.1_ASM42408v1_genomic.fna_report.tsv  GCF_001405215.1_14207_7_44_genomic.fna_report.tsv
GCF_000439125.1_ASM43912v1_genomic.fna_hits.tsv    GCF_001405455.1_13470_2_80_genomic.fna_hits.tsv
GCF_000466565.1_ASM46656v1_genomic.fna_hits.tsv    GCF_001405455.1_13470_2_80_genomic.fna_report.tsv
GCF_000484655.1_ASM48465v1_genomic.fna_hits.tsv    GCF_001487165.1_Blautia_massiliensis1_genomic.fna_hits.tsv
GCF_000484655.1_ASM48465v1_genomic.fna_report.tsv  GCF_001487165.1_Blautia_massiliensis1_genomic.fna_report.tsv
GCF_000702025.1_ASM70202v1_genomic.fna_hits.tsv    GCF_900078295.1_PRJEB13136_genomic.fna_hits.tsv
GCF_000765245.1_ASM76524v1_genomic.fna_hits.tsv    GCF_900078295.1_PRJEB13136_genomic.fna_report.tsv
GCF_001404455.1_13414_6_22_genomic.fna_hits.tsv    GCF_900120195.1_PRJEB18016_genomic.fna_hits.tsv
GCF_001404535.1_13414_6_21_genomic.fna_hits.tsv    GCF_900120195.1_PRJEB18016_genomic.fna_report.tsv
GCF_001404535.1_13414_6_21_genomic.fna_report.tsv  GCF_900120295.1_PRJEB18018_genomic.fna_hits.tsv
GCF_001404735.1_14207_7_34_genomic.fna_hits.tsv    GCF_900120295.1_PRJEB18018_genomic.fna_report.tsv
```

[cmd_drep_gANI_gt99.log.txt](https://github.com/MrOlm/drep/files/929873/cmd_drep_gANI_gt99.log.txt)

**Comment by MrOlm** [comment]
Hey Bubba,

1) With regards to checkM filtering, there are a couple of options:

* Run with `--checkM_method taxonomy_wf`. This will skip pplacer entirely. The only downside is that it's not robust to archaea (uses universal bacterial single copy genes)

* Filter the genomes with checkM on your own using whatever parameters are best for your system, and then just run dRep with the `--skipCheckM`` option. This won't work if you want dRep to pick the best genomes.

* Run checkM on your own using whatever parameters are best for your system, make a tab_table of your results, and import them to dRep using `--tab_table`. This will make allow dRep to do the filtering and choose the best genomes based on the checkM results for you.

2) That seems like a problem with centrifuge, not checkM. It looks like a lot of the genomes have a `_hits.tsv` file, but not a `report.tsv` file. I suspect that in cases where there is no `_report.tsv` file, the corresponding `_hits.tsv` file is empty. Could you confirm that for me? If so, I'll just write a patch into the program that's able to handle empty files.

Thanks!
-Matt

**Comment by brooksomics** [comment]
Hey Matt,

**1.** I tried your first suggestion since I'm not too concerned with archaea at the moment...

In a fresh dir, I `--checkM_method taxonomy_wf`:
```
nice dRep dereplicate_wf . -g genomes/* -o -p 16 --checkM_method taxonomy_wf --run_tax --S_algorithm gANI -sa 0.99 --cent_index /home/ubuntu/scripts/github/centrifuge/indices/b+h+v &> drep.log
```
It ended up terminating at the gANI step:
```
$ tail cmd_drep_gANI_gt99.log
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/miniconda3/envs/irep/lib/python3.6/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/home/ubuntu/miniconda3/envs/irep/lib/python3.6/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ubuntu/miniconda3/envs/irep/lib/python3.6/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
FileNotFoundError: File b'/home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/test_mem1/data/gANI_files/GCF_001404535.1_13414_6_21_genomic.fna_vs_GCF_000153905.1_ASM15390v1_genomic.fna.gANI' does not exist
```
Indeed the file does not exist, but the two genomes gANI is trying to compare do exist. Nothing seems odd about the files (i.e. not empty or named weird). Is there there an issue with the `--checkM_method taxonomy_wf` flag? Attached is the logger.log in case that's helpful.

**2.** Yeah, this is really odd - but that's what's going on. In the previously mentioned run there are 22 hits:
```
$ l ../data/centrifuge/*fna_hits.tsv | wc -l
22
```
And 10 reports:
```
$ l ../data/centrifuge/*fna_report.tsv | wc -l
10
```
The centrifuge index I'm using wasn't built on this particular [AMI](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html), but I don't think that should matter...

Ok, this is going in all sorts of directions. Sorry!

[logger.txt](https://github.com/MrOlm/drep/files/930460/logger.txt)

**Comment by MrOlm** [comment]
Hey Bubba,

1) Try the following command:

```
/usr/local/bin/ANIcalculator -genome1fna /home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/test_mem1/data/prodigal/GCF_001404535.1_13414_6_21_genomic.fna.fna -genome2fna /home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/test_mem1/data/prodigal/GCF_000153905.1_ASM15390v1_genomic.fna.fna -outfile /home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/test_mem1/data/gANI_files/GCF_001404535.1_13414_6_21_genomic.fna_vs_GCF_000153905.1_ASM15390v1_genomic.fna.gANI -outdir /home/ubuntu/db/ncbi_Blautia_20170418/dRep/gANI_gt99/test_mem1/data/gANI_files/GCF_001404535.1_13414_6_21_genomic.fna_vs_GCF_000153905.1_ASM15390v1_genomic.fna.gANITEMP
```

Any errors? Are the output files made? That was what dRep tried to run to make that file that doesn't exist

2) Could you upload three files for me: 

1 + 2) For a genome that has both a _hits.tsv and a _report.tsv file, upload both of those

3) For a genome that has only a _hits.tsv file, upload it.

Best,
-Matt
