### ISSUE TITLE
orientation

### ISSUE THREAD

**Issue by jotes35** [MrOlm/drep#90]
Hello developers, I would like to know if its possible to get an option to generate the clusters where the labels are to the right side. Just like the image attached.
![patch2](https://user-images.githubusercontent.com/14283733/93484253-38aead80-f8f1-11ea-9570-686233674aa1.png)

**Comment by MrOlm** [comment]
Hi jotes,

At the moment this is not something that is possible within dRep itself. If you'd like, you could create a dendrogram using the software of your choice using the file "Ndb.csv" resulting from dRep, which contains pair-wise ANI information. That's what's used to make the dendrogram within dRep.

Best,
Matt

**Comment by jotes35** [comment]
Thanks. I will do that
