### ISSUE TITLE
Primary cluster xx was almost not split

### ISSUE THREAD

**Issue by MarcelaHer** [MrOlm/drep#92]
Hi, 
My dereplicated_genomes has 2 MAGs from the same cluster (40_1)
The warnings.txt says: Primary cluster 40 was almost not split. 
Do you know why derep didn't choose the "win" MAG and instead just assigned both of them as my cluster 40?

**Comment by MrOlm** [comment]
Hello,

I'm not sure I understand the question- what do you mean that the dRep didn't choose a winning MAG? Can you show me the output that dRep made that has you concerned?

Best,
Matt

**Comment by MarcelaHer** [comment]
Hi, 
thank you. 
Please find attached, I have two MAGs that were selected as cluster 40, and that got me confused... since Ive always got the "win/selected/perfect" MAG for each single cluster. Ive highlighted the problem in yellow in the table. Thanks!!

[Pipe_Wdb.xlsx](https://github.com/MrOlm/drep/files/5262602/Pipe_Wdb.xlsx)

**Comment by MrOlm** [comment]
Hello,

In this table the `40` means that both genomes are in primary cluster 40, but they are both in separate secondary clusters within primary cluster 40 (40_1 and 40_2). Each of these secondary clusters has its own winner.

The warning refers to the fact these two secondary clusters were almost not split- the ANI between them is on the boarder. If you decrease the secondary ANI threshold (for example by adding `-sa 0.98`), there will likely only be a single winner within primary cluster 40.

Best,
MO

**Comment by MarcelaHer** [comment]
THANK YOU! :-)
