### ISSUE TITLE
CLUSTERING WARNING: Primary cluster 1 has a high self-comparison value

### ISSUE THREAD

**Issue by liupfskygre** [MrOlm/drep#94]
Hi,
    I installed dRep v2.6.2 on MAC to dRep my genomes and found the strange outputs, 11 representatives were picked but only 4 were expected. I tested the same dataset somewhere else and no warnings, got expected 4 genome winners. 

I read the following
`de-replicated genome similarity warns when de-replicated genomes are similar to each other. This is to try and catch cases where similar genomes were split into different primary clusters, and thus failed to be de-replicated.`
maybe some of the genomes were split into different primary clusters??

this is my command used and attached is the log file and warnings

dRep dereplicate -sa 0.97 -p 4 -comp 50 -con 10 --genomeInfo ../checkM_gtdbtk_4_dRep_newName.csv ./*.fa

thanks:)
[logger.log](https://github.com/MrOlm/drep/files/5432482/logger.log)
[warnings.txt](https://github.com/MrOlm/drep/files/5432483/warnings.txt)

**Comment by MrOlm** [comment]
Hello,

Sorry for only noticing this issue now- it feel through the cracks on my to-do list. I don't think the warnings are a big deal- those happen a lot and I tend to ignore them. What makes you think that you should only have 4 representative genomes? It should be possible to look through the produced figures and datatables to figure out why 11 reps were chosen.

Best,
Matt

**Comment by MrOlm** [comment]
Going to close for now, but happy to re-open if you still need help.

**Comment by liupfskygre** [comment]
Hi, sorry for a late reply,
1, I do this analysis on anther server with dRep (I could get the version now), and have 4 produced without any warnings,

2, the winner db looks wired for this run with 11 winners, as you can see here, for each cluster, only one with highest score, but it gave me others with lower scores, i think score is the criteria for the winner, right

here is the winner db from data_tables/Widb.csv
```
genome,score,completeness,contamination,strain_heterogeneity,size,N50,cluster,taxonomy,tax_confidence,cluster_members,closest_cluster_member,furthest_cluster_member,completeness_metric,contamination_metric
2-C20-8_bin.5.fa,91.78056647607174,NA,NA,NA,NA,NA,1_1,NA,NA,9,99.95,97.76,NA,NA
TO55_bin.84.fa,88.3105542956999,NA,NA,NA,NA,NA,1_2,NA,NA,1,NA,NA,NA,NA
TO45_bin.92.fa,87.72086500778622,NA,NA,NA,NA,NA,1_3,NA,NA,1,NA,NA,NA,NA
TO35_bin.67.fa,88.38329490128521,NA,NA,NA,NA,NA,1_4,NA,NA,1,NA,NA,NA,NA
TO65_bin.86.fa,88.38078056011803,NA,NA,NA,NA,NA,1_5,NA,NA,1,NA,NA,NA,NA
pw55_bin.61.fa,86.23031193727495,NA,NA,NA,NA,NA,2_1,NA,NA,7,99.92,99.81,NA,NA
TO45_bin.85.fa,75.29557245437816,NA,NA,NA,NA,NA,2_2,NA,NA,1,NA,NA,NA,NA
GD2_bin.40.fa,79.25927164956101,NA,NA,NA,NA,NA,3_1,NA,NA,9,98.85,98.47,NA,NA
TO55_bin.66.fa,64.98471984228358,NA,NA,NA,NA,NA,3_2,NA,NA,1,NA,NA,NA,NA
TO65_bin.11.fa,84.84733828761587,NA,NA,NA,NA,NA,3_3,NA,NA,1,NA,NA,NA,NA
G35_3_bin.32.fa,84.27587134106159,NA,NA,NA,NA,NA,4_1,NA,NA,7,99.90,98.69,NA,NA
```

not sure if it is bug or it is the case, thanks Matt.
