### ISSUE TITLE
format of input

### ISSUE THREAD

**Issue by Biofarmer** [MrOlm/drep#95]
Hi Dr. Olm,

I am using version 2.6.2, may I ask the format of genome files must be with .fasta? OR .fa, .fna are both accepted?
I tried the compressed files, but it did not work, so I guess the compressed file is not supported, right?

Thanks
Wang

**Comment by MrOlm** [comment]
`.fasta`, `.fa`, `.fna` all work fine. Compressed files only work if you use `compare` and set `--S_algorithm fastANI`

**Comment by Biofarmer** [comment]
Many thanks. In addition, if you see my comment for #28, I think the GC content is still not correct in Chdb.csv, right? I think the CheckM is still use the proteins to calculate, and the genomeInformation.csv is without GC content.

**Comment by MrOlm** [comment]
Yes that's correct- `Chdb.csv` stands for checkM database, and is exactly what checkM reports when run on genes.

**Comment by Biofarmer** [comment]
So, the genome information should go to genomeInformation.csv, right?

**Comment by MrOlm** [comment]
Yes `genomeInformation.csv` has the information calculated on a per-genome level, but GC content isn't calculated or reported because it's not used by any other aspect of dRep (just length and N50, which are used for scoring genomes)

**Comment by Biofarmer** [comment]
Many thanks.
