### ISSUE TITLE
dRep fails when processing files with different paths but the same file name

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [MrOlm/drep#97]
Hi,

Thanks for your work on dRep! I was processing a large set of MAGs and had an error like that of #25 where I had a duplicate file name error due to an internal Pandas call. The actual error is the same in #25, but I checked my file paths and found that are all unique. It seems that having bins with the same name (even if they point to distinct files) will trigger this error as well.

I'm not sure what the code looks like internally but I imagine keying the data frame by the full file path instead of the file name will fix this issue. I can probably work around the problem by symlinking the files to new names but it's a bit of a pain to deconvolute afterwards. Happy to discuss potential solutions though.

**Comment by MrOlm** [comment]
Hello,

For better or worse, dRep as a whole relies on having unique file basenames. All of the output dataframes are keyed this way as well; only file basenames are used when reporting results, not full paths. This has the benefit of making the output files more readable, with the downside being the problem you're encountering. 

If starting from scratch I might do this differently, but as the program stands it would just more time than I have to change it to work with files that have the same basename but different paths. Apologies that dRep isn't working well for your use-case.

Best and thanks for reporting the issue,
Matt

**Comment by nick-youngblut** [comment]
The error of:

```
ValueError: Index contains duplicate entries, cannot reshape
```

does seem to be the user's fault for not making sure all taxon names & paths are unique, but nonetheless it would be nice if drep included a check on this at the start of drep. dRep died with this error after >15 CPU hours

**Comment by jdwinkler-lanzatech** [comment]
I eventually just symlinked my paths to something unique to handle that issue. I suppose dRep could do that internally and just rename the outputs appropriately, but you'd still run the risk of name collisions later.

**Comment by MrOlm** [comment]
FYI, in dRep version 3.1.0 it now checks for this fist thing and will error-out if there are multiple genomes with the same base name

-Matt
